### ISSUE TITLE
Queue | Enable starting checkout flow when loading at appeal detail

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#5721] opened 2018-05-30 15:03 UTC
Currently, we restrict who can see the start attorney checkout flow dropdown within the appeal detail view to users who have `:queue_phase_two` FeatureToggle enabled, *and* if the displayed appeal [is in `loadedQueue`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/QueueDetailView.jsx#L86) (i.e. is assigned to the current user).

However, when the user loads the site directly on the appeal detail view (`/queue/appeals/${vacolsId}`), we never populate `state.loadedQueue`, [only `state.activeCase`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/QueueLoadingScreen.jsx#L29).

We should adjust the condition in `QueueDetailView.getCheckoutFlowDropdown` to check the appeal's Task, which has assignment information (`task.user_id`?). At the moment, though, we don't currently return any tasks when hitting `/queue/${user_id}`

**Comment by evankroske** [comment] 2018-07-16 15:31
Duplicate of https://github.com/department-of-veterans-affairs/caseflow/issues/6222

**Closed by evankroske** 2018-07-16 15:31 UTC
Labels: caseflow-queue, tech-debt, tech-improvement
