### ISSUE TITLE
UserRepositoryError occurs when user tries to get special issues on a legacy appeal

### ISSUE THREAD

**Issue by tomas-nava** [department-of-veterans-affairs/caseflow#9899] opened 2019-03-11 23:20 UTC
[Sentry issue here](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3283/)

**Comment by monfresh** [comment] 2019-03-25 16:42
This is because the `before_action` ends up running a validation in `user_repository` which raises `Caseflow::Error::UserRepositoryError`, but the controller doesn't rescue it. For some reason, I can't reproduce this locally. If I write a controller test with a user who doesn't have access to the appeal, it raises `Caseflow::Error::VacolsRepositoryError`, which is rescued in `ApplicationController`. I will look more into this.

**Comment by annekainicUSDS** [comment] 2019-04-02 22:52
@monfresh @tomas-nava this Sentry alert was triggered again today: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3283/activity/

**Comment by aroltsch** [comment] 2019-04-08 18:12
It might be one of the ways to reproduce it.
Reproduction steps:
    1. It has to do with the combination of a browser back button and a queue back button
    2. Go through legacy checkout, make sure to click “edit issue” link, delete issue or edit issue
    3. Finish checkout, click browser back button, notice it brings you to the disposition screen - which it should not be happening
    4. Click queue back button, it brings you to the special issues page with 400 error response

**Comment by monfresh** [comment] 2019-05-15 13:36
Re-opening because this is still happening. We fixed one scenario that resulted in this error, but it looks like there's another way users can get in this state.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3283/events/334267/

**Comment by jcq** [comment] 2020-01-15 17:36
Just flagging that this error continues to be seen:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6838/

I see similar alerts from Jan 6th, 7th, & 9th as well, to give context on frequency.

**Closed** 2020-01-22 22:25 UTC
Labels: Investigation, caseflow-decisions, foxtrot, priority-low, sentry-alert
