### ISSUE TITLE
Make SC/HLR establishment idempotent

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#5339] opened 2018-04-30 15:18 UTC
When establishing the EP/contentions of Supplemental Claims & Higher Level Reviews, any step in the process can error out, leaving the establishment in a potentially partially created state.

We should make the establishment idempotent, so it can be tried again and again with no harmful side effects.

## Technical Notes
There are many different pathways to doing this. We could cancel the EP, or use the previously created EP. We would need to investigate the implications of this for the NWQ.

## Acceptance Criteria
* Write a design doc explaining our options and trade offs
* Create issues to implement recommended next steps

**Comment by ferlatte** [comment] 2018-07-03 18:04
Right now, this isn't super bad, but when AMA kicks in this gets a lot worse.

**Comment by abbyraskinUSDS** [comment] 2018-07-19 14:53
How many are needed at the point of claim establishment specifically? I am not sure, though I would assume it's however many we're already hitting with our current functionality.

**Comment by ferlatte** [comment] 2018-07-19 22:01
@abbyraskinUSDS I think the issue is: right now, for RAMP review and AMA review, we are only making 2 calls to external services when we establish an end product and they are both doing the same thing. Shane made it sound like AMA reviews were going to require a lot more calls to BGS and VBMS in order to properly establish an end product.

What I'm trying to balance is: the solution I'm considering is probably overkill if we only are going to make 2 external service calls. It's not overkill if we're going to end up making more when we're doing the full AMA review process.

Sorry if I'm not being clear here.

**Comment by abbyraskinUSDS** [comment] 2018-07-20 15:17
That makes sense! I didn't realize it was much more complicated for AMA than RAMP. (there are definitely more values we have to set/send along with the EP, but I didn't think of those as separate services - obviously Shane would know better, so we might need his insight here).

**Comment by ferlatte** [comment] 2018-07-23 04:35
No, this is perfect. Knowing that we've for sure got more things to set for the EP means that we'll have separate service calls in most cases, so it'll be worth doing the more complex solution.

**Comment by ferlatte** [comment] 2018-07-25 18:55
See #6354 #6356 #6357

**Comment by leikkisa** [comment] 2018-08-16 22:43
I am closing this ticket for validation, because it's a research ticket, and Mark created the development tickets for it above.

**Closed by leikkisa** 2018-08-16 22:43 UTC
Labels: In-Validation, Investigation, caseflow-intake, sierra
