### ISSUE TITLE
VBMS cannot find record 

### ISSUE THREAD

**Issue by lomaxap** [department-of-veterans-affairs/caseflow#11695] opened 2019-08-07 20:59 UTC
https://dsva.slack.com/archives/CCB97HZJL/p1565188103098600 VBMS cannot find record by claim number 67421457 when attempting to sync end product establishment.

**Comment by leikkisa** [comment] 2019-09-14 17:33
Dupe of https://github.com/department-of-veterans-affairs/caseflow/issues/11787

I will put this info into that ticket, and close this one.

**Closed by leikkisa** 2019-09-14 17:33 UTC
Labels: batteam, bug-medium-priority, caseflow-intake, foxtrot, priority-medium
