### ISSUE TITLE
Duplicate user in Caseflow/VACOLS

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#7566] opened 2018-10-26 14:44 UTC
Sentry error: 
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2584/events/154781/

We have been seeing that some users don't have slogid in VACOLS.

**Comment by aroltsch** [comment] 2018-10-29 15:21
I am going to keep an eye on this issue. I've checked every single user and they have slogid now. I can't tell when these STAFF records were added because `stadtime` is nil.

**Comment by hschallhorn** [comment] 2019-04-12 16:11
We've had [~40 more](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2584/events/171258/) of these errors since this issue was closed.

**Comment by hschallhorn** [comment] 2019-04-12 16:30
[The most recent error](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2584/events/300965/). [AWS logs](https://console.amazonaws-us-gov.com/cloudwatch/home?region=us-gov-west-1#logEventViewer:group=dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out;stream=i-084e57540d1655ee9;filter=%22ebcbba9b-b59b-4e52-89ef-0f259570f977%22;start=2019-04-11T14:48:48Z).

This particular one was caused by User 4585 having the css_id of "VACOJILLIB" while her sdomainid in VACOLS is "VACOBONAJ"

**Comment by sharonwarner** [comment] 2019-05-31 14:17
Happening here as well: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2584/

**Comment by alisan16** [comment] 2020-03-31 19:18
Closing this as the Sentry error hasn't been seen in 6 months

**Closed by alisan16** 2020-03-31 19:18 UTC
Labels: Source: Sentry Alert, Type: Bug, User: Judge
