### ISSUE TITLE
Diagnostic code is an empty string

### ISSUE THREAD

**Issue by annekainicUSDS** [department-of-veterans-affairs/caseflow#10250] opened 2019-04-02 01:02 UTC
Sentry alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/4074/.  Looks like there was an `ActiveRecord::RecordInvalid` error when trying to update issue dispositions in caseflow. Maybe related to an invalid parameter that as passed: `{ "name": "transaction" }`, but not sure.

**Comment by tomas-nava** [comment] 2019-04-02 23:38
_What happened:_ a user submitted a case review (transaction `6e8e7a20-ce09-4c46-a3c8-540bb9c4590e`) with some empty (`""`) diagnostic codes, and [validation](https://github.com/department-of-veterans-affairs/caseflow/blob/queue/tomas/9885-create-change-disposition-task-and-actions/app/models/decision_issue.rb#L10) failed on the `DecisionIssue` when the review was submitted to [the `case_reviews#complete` endpoint](https://github.com/department-of-veterans-affairs/caseflow/blob/queue/tomas/9885-create-change-disposition-task-and-actions/app/controllers/case_reviews_controller.rb#L12). In this case, the user saw the validation error and successfully resubmitted a minute later (transaction `a80b7294-edd9-46ea-9bc4-e58c83336ceb`) with diagnostic codes filled in, so there was no loss of data.

I'm not sure how those `""` diagnostic codes got into the form parameters; it shouldn't have been possible to save them to the database in the first place because of the same validation. And there are currently no decision issues in production with `""` diagnostic codes (though there are plenty with `nil` diagnostic codes, which is allowed).

The form element for entering the diagnostic code is [a dropdown which is populated from a constants file](https://github.com/department-of-veterans-affairs/caseflow/blob/queue/tomas/9885-create-change-disposition-task-and-actions/client/app/queue/SelectDispositionsView.jsx#L352), so it shouldn't have been possible to select an empty value there.

**Comment by hschallhorn** [comment] 2019-04-18 19:20
Unable to reproduce in dev. Closing until we see this again.

**Closed by hschallhorn** 2019-04-18 19:20 UTC
Labels: bug-low-priority, caseflow-queue
