### ISSUE TITLE
Queue Table | Bold task links, unbold after visiting

### ISSUE THREAD

**Issue by dannysellers** [department-of-veterans-affairs/caseflow#4573] opened 2018-02-07 17:12 UTC
After a recent demo, we discussed implementing a read/unread status similar to Reader: Task links would start out bold by default (unread), and would un-bold after the user loaded them for the first time.

The 'read' status should be tracked per user, as tasks will be viewed/reviewed by multiple people depending on status. We will reset the read status after a task's assignment changes (i.e. if an Attorney views a task, it gets assigned to a Judge, and then re-assigned to the Attorney, the task should appear unread to them).

Barring changes to who a task is assigned to, the 'read' status should persist across sessions. We'll need a new database field to track who's 'read' the task.

This field, `read_by`/`seen_by`, will be an array containing User IDs, such that `is_read = Task.read_by.includes? current_user.css_id`. When a task is [assigned to a user](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/task.rb#L226), `read_by` would be set to `[user.css_id]`.

To mark as read, we'll either need a dedicated endpoint, or it may also make sense to tie this in with pending work on POSTing to `/tasks/:unique_id`, which tentatively will be used to complete / update a task ([spec](https://dsva.slack.com/files/U2L6PJE8N/F94GFQMEF/How_should_we_build_out_task_routes_that_interact_with_VACOLS_case_assignments_))

**Comment by amprokop** [comment] 2018-02-09 15:06
```
We will reset the read status after a task's assignment changes (i.e. if an Attorney views a task, it gets assigned to a Judge, and then re-assigned to the Attorney, the task should appear unread to them).
```
Currently 

```
This field, read_by/seen_by, will be an array containing User IDs, such that is_read = Task.read_by.includes? current_user.css_id. When a task is assigned to a user, read_by would be set to [user.css_id].
```

- What are the reasons we might want to have this be a array column on a `Task` table, rather than a separate table? Would our relational data model lend itself better to a `TaskView` table?

- The `Task` model is currently used by only dispatch. Were we planning to use it? We aren't currently persisting VacolsAssignments themselves at all.

```
To mark as read, we'll either need a dedicated endpoint, or it may also make sense to tie this in with pending work on POSTing to /tasks/:unique_id, which tentatively will be used to complete / update a task 
```

Did we consider `GET /tasks/:unique_id`?

**Comment by dannysellers** [comment] 2018-02-09 17:06
Hmm, ok. I guess I'd forgotten that `tasks` on the frontend are actually `Appeal`s on the backend.

I was also under the impression that Appeal objects would persist between changes to assignment, though if that's not the case, then we would probably need a separate table to track views. I'd love to get an offline explanation of this—I'm not sure I even know where to look in the code to better understand how those processes are handled w/r/t the database.

On the assumption that Appeals persist between review stages, my inclination to make this an attribute of the Appeal was just for simplicity. If all we're doing is tracking a list of IDs, why not have that be an attribute of the model itself? OTOH, if we want to store things like `viewed_at_datetime`, or to track changes to the 'views' independent of changes to the appeal itself (for which we can use `paper_trail`), then it'd make more sense to me to have a separate table.

I was looking at `Task` forgetting the distinction mentioned above, and because it already has state-management logic that seemed to fit our use-case. But if it's not used by queue at all, then never mind 👍 

I think we're both in agreement about using the `/tasks/:unique_id` endpoint for this (though it'd probably use `POST` or `PATCH`). If we/Anya are going to expand that endpoint to update other Appeal attributes, then it definitely makes sense to include `seen_by` in the list of supported attributes.

Postgres supports [arrays](https://www.postgresql.org/docs/9.1/static/arrays.html), as does [rails](http://edgeguides.rubyonrails.org/active_record_postgresql.html#array). Querying by what that array contains isn't covered in either of those links, but should be possible with [something like](https://blog.arkency.com/2014/10/how-to-start-using-arrays-in-rails-with-postgresql/#querying) `Appeal.where("seen_by >@ ?", '{#{current_user.css_id}}')`

**Comment by amprokop** [comment] 2018-02-09 17:30
> Hmm, ok. I guess I'd forgotten that tasks on the frontend are actually Appeals on the backend.

Maybe we can chat about this offline? Tasks on the frontend aren't appeals on the backend afaik.

> I was also under the impression that Appeal objects would persist between changes to assignment

They will. But let's keep in mind that we're thinking forward to AMA appeals as well. They may not use the same Appeal model. Would storing this on the Appeal model restrict us in any way later on? What if a user has two tasks for an appeal— how would we handle this situation if we store this as a field on the Appeal model?

**Comment by amprokop** [comment] 2018-02-09 17:35
> I think we're both in agreement about using the /tasks/:unique_id endpoint for this (though it'd probably use POST or PATCH).

Interesting. Do you see this as functionality that we want to build into our server-client interface? Or is it more a side-effect that happens on the server and is passed to the client?

**Comment by dannysellers** [comment] 2018-02-09 18:18
Yeah, I'm down to chat offline at some point—I don't think this task necessarily needs to be part of Phase 1 or anything.

I say that Tasks on the frontend are Appeals on the backend because, at least in [`fakes/queue_repository.tasks_for_user`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/lib/fakes/queue_repository.rb#L7), Tasks are just hashes created from Appeal data.

If we aren't necessarily going to use the same Appeal model going forward, then having a dedicated table is definitely a better idea.

I'm not sure how to track views if we can't guarantee a one-to-one between the Task model and TaskViews. How are different tasks for the same appeal distinguished in the backend?

As far as the HTTP verb to use—I was thinking we would decouple the act of loading a task (and rendering the task table) from the act of marking it as read. Otherwise, every task would be marked as read as soon as we loaded the page. Adding POST or PATCH behavior to the endpoint would allow us to mark a task as read only on specific events (i.e. when the user visits the task detail page).

**Comment by laurjpeterson** [comment] 2018-08-14 00:47
duplicate of https://github.com/department-of-veterans-affairs/caseflow/issues/5800

**Closed** 2018-08-14 00:47 UTC
Labels: caseflow-queue, foxtrot
