### ISSUE TITLE
`rake db:seed` should work even when user data exists.

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#437] opened 2016-11-14 15:43 UTC
```
VACOLTRUSSES:caseflow-certification vacorusses3$ bundle exec rake db:seed
rake aborted!
ActiveRecord::RecordNotUnique: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_station_id_and_css_id"
DETAIL:  Key (station_id, css_id)=(283, ANNE MERICA) already exists.
: INSERT INTO "users" ("css_id", "station_id") VALUES ($1, $2) RETURNING "id"
/Users/vacorusses3/Developer/caseflow-certification/db/seeds.rb:66:in `create_default_user'
/Users/vacorusses3/Developer/caseflow-certification/db/seeds.rb:70:in `seed'
/Users/vacorusses3/Developer/caseflow-certification/db/seeds.rb:78:in `<top (required)>'
/Users/vacorusses3/.rbenv/versions/2.2.4/bin/bundle:23:in `load'
/Users/vacorusses3/.rbenv/versions/2.2.4/bin/bundle:23:in `<main>'
PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_users_on_station_id_and_css_id"
DETAIL:  Key (station_id, css_id)=(283, ANNE MERICA) already exists.
/Users/vacorusses3/Developer/caseflow-certification/db/seeds.rb:66:in `create_default_user'
/Users/vacorusses3/Developer/caseflow-certification/db/seeds.rb:70:in `seed'
/Users/vacorusses3/Developer/caseflow-certification/db/seeds.rb:78:in `<top (required)>'
/Users/vacorusses3/.rbenv/versions/2.2.4/bin/bundle:23:in `load'
/Users/vacorusses3/.rbenv/versions/2.2.4/bin/bundle:23:in `<main>'
Tasks: TOP => db:seed
```

I am unable to run `rake db:seed` when a user is already there. This command should not error out if the user already exists and continue to create other seed data.

**Comment by joofsh** [comment] 2016-11-15 20:01
@shanear I am able to reproduce this running `rake db:seed` with existing data in the database. However, running `rake db:setup` works properly as it first wipes the DB before seeding. 

I think it is okay as is, but we could potentially make changes to the seeds file if you want to be able to run it more than once (adding more and more records to the DB)? Let me know if you want these changes otherwise I'll close this ticket. Also going to update the README with some info about seeding the db

**Comment by shanear** [comment] 2016-11-15 20:22
@joofsh I'm thinking it'd be nice for `rake db:seed` to start by cleaning the db. But I'll defer to whatever you think is best.

**Comment by askldjd** [comment] 2016-11-16 19:32
In the process of adding `db:setup` and `db:seed` to dev environment, I am encountering the following error in `db:seed` stage. (see also https://github.com/department-of-veterans-affairs/appeals-deployment/pull/209)

Since we are baking a clean AMI and using sqlite database as backend, there is no existing data in Caseflow.

```
TASK [caseflow-certification : apply db seed for dev environment] **************
Wednesday 16 November 2016  14:26:23 -0500 (0:00:00.130)       0:05:06.337 **** 
fatal: [52.222.53.15]: FAILED! => {"changed": true, "cmd": "source ../caseflow-certification_env.sh && bin/rake db:seed", "delta": "0:00:02.263030", "end": "2016-11-16 14:26:25.839095", "failed": true, "rc": 1, "start": "2016-11-16 14:26:23.576065", "stderr": "rake aborted!\nActiveRecord::RecordNotUnique: SQLite3::ConstraintException: columns station_id, css_id are not unique: INSERT INTO \"users\" (\"css_id\", \"station_id\") VALUES (?, ?)\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `step'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `block in each'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `loop'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `each'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:302:in `to_a'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:302:in `block in exec_query'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:281:in `exec_query'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:76:in `exec_insert'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:64:in `insert'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:524:in `_create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/counter_cache.rb:139:in `_create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/locking/optimistic.rb:75:in `_create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:133:in `_create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `block in _create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `_create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/timestamp.rb:57:in `_create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:504:in `create_or_update'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `create_or_update'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:120:in `save'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:37:in `save'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:21:in `save'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block (2 levels) in save'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block in save'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:285:in `save'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:34:in `create'\n/opt/caseflow-certification/src/db/seeds.rb:66:in `create_default_users'\n/opt/caseflow-certification/src/db/seeds.rb:73:in `seed'\n/opt/caseflow-certification/src/db/seeds.rb:81:in `<top (required)>'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/engine.rb:547:in `load_seed'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:251:in `load_seed'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:183:in `block (2 levels) in <top (required)>'\nSQLite3::ConstraintException: columns station_id, css_id are not unique\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `step'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:108:in `block in each'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `loop'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/sqlite3-1.3.11/lib/sqlite3/statement.rb:107:in `each'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:302:in `to_a'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:302:in `block in exec_query'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:484:in `block in log'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract_adapter.rb:478:in `log'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/sqlite3_adapter.rb:281:in `exec_query'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:76:in `exec_insert'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:108:in `insert'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/query_cache.rb:14:in `insert'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/relation.rb:64:in `insert'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:524:in `_create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/counter_cache.rb:139:in `_create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/locking/optimistic.rb:75:in `_create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:133:in `_create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `block in _create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_create_callbacks'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:306:in `_create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/timestamp.rb:57:in `_create_record'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:504:in `create_or_update'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `block in create_or_update'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_save_callbacks'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/callbacks.rb:302:in `create_or_update'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:120:in `save'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/validations.rb:37:in `save'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/attribute_methods/dirty.rb:21:in `save'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block (2 levels) in save'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:220:in `transaction'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:348:in `with_transaction_returning_status'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:286:in `block in save'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:301:in `rollback_active_record_state!'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/transactions.rb:285:in `save'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/persistence.rb:34:in `create'\n/opt/caseflow-certification/src/db/seeds.rb:66:in `create_default_users'\n/opt/caseflow-certification/src/db/seeds.rb:73:in `seed'\n/opt/caseflow-certification/src/db/seeds.rb:81:in `<top (required)>'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/railties-4.2.7.1/lib/rails/engine.rb:547:in `load_seed'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/tasks/database_tasks.rb:251:in `load_seed'\n/opt/caseflow-certification/src/vendor/bundle/ruby/2.2.0/gems/activerecord-4.2.7.1/lib/active_record/railties/databases.rake:183:in `block (2 levels) in <top (required)>'\nTasks: TOP => db:seed\n(See full trace by running task with --trace)", "stdout": "", "stdout_lines": [], "warnings": []}

```

**Closed** 2016-11-17 14:52 UTC
Labels: Current Sprint, in progress
