### ISSUE TITLE
BSE 64649 - Capability to Edit Contentions in Caseflow Intake

### ISSUE THREAD

**Issue by geoffreystienblock** [department-of-veterans-affairs/caseflow#11488] opened 2019-07-23 14:13 UTC
**Requirement:**  Have the Add Issue field be editable at intake within Caseflow so contentions can be properly displayed in VBMS.
**Value Statement:**  As a Caseflow user, I need the ability to edit contentions in the Caseflow Intake screen, so that I can process AMA claims in the most efficient manner.
**Definition of done:**  1.Users are able to edit contention in the Caseflow Intake screen.

**Comment by laurjpeterson** [comment] 2019-07-25 03:44
Duplicate of https://github.com/department-of-veterans-affairs/caseflow/issues/11188, so this can be closed!

**Comment by jimruggiero** [comment] 2019-09-08 00:05
@laurjpeterson can I close this one given your note above?

**Closed** 2019-09-17 03:25 UTC
Labels: AMO, Epic, caseflow-intake, foxtrot
