### ISSUE TITLE
Hearing Worksheet: View issues that need to be heard

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#3797] opened 2017-10-30 19:55 UTC
As a judge, I only want to see issues on on the Hearing Worksheet that are active and could be heard, so that I prepare to hear the relevant issues on the appeal.

### AC:

For all appeals streams:
- Issues with no disposition dates should be displayed
- Issues with disposition dates and disposition codes of '3' or 'L' should be displayed

**Comment by astewarttistatech** [comment] 2017-11-15 16:19
@laurjpeterson What would those issues look like? Are those dispositions something I would see on the UI of the Hearings Worksheet page? Something on the backend? Would the Issues without a decision date display a blank date or a different value? Could that be validated in the backend as well?

**Comment by laurjpeterson** [comment] 2017-11-15 17:26
> What would those issues look like?

There is no change to the hearing worksheet as it is designed today with this ticket. This ticket is basically adding a condition to what issues are displayed. Here's a screenshot of the hearing worksheet section that contains issues. Let me know if this doesn't answer the question.

![image](https://user-images.githubusercontent.com/27704093/32849989-d2040e82-c9fe-11e7-9db3-c4efb2b20184.png)

> Are those dispositions something I would see on the UI of the Hearings Worksheet page? Something on the backend?

No, you would not see the dispositions on the UI at this time. We'd see on the backend if issues with the dispositions as outlined in the AC are pulled onto the worksheet.

> Would the Issues without a decision date display a blank date or a different value?

We do not have a decision date field associated with the issue in the current designs. 

> Could that be validated in the backend as well?

Yes, you could see the issue's decision date on the backend.

cc: @annienguyenUSDS @sharonwarner

**Comment by astewarttistatech** [comment] 2017-11-16 16:55
Sorry to be a pest about this but are there any instructions for gathering/creating this data @sharonwarner?

**Comment by astewarttistatech** [comment] 2017-11-16 20:57
@annienguyenUSDS According to Chris, we might be missing some info about these Issue dispositions. 

There are two kinds of dispositions. For the issues, we're looking for a Veteran who has a pending remand (`BFMPRO = 'REM'`) with at least one remanded issue (`ISSDC in ('3', 'L')`). For the hearing, we need that Veteran to have a hearing that hasn't happened (`HEARING_DISP is null`). @sharonwarner is this correct?

**Comment by sharonwarner** [comment] 2017-11-16 22:07
I can ask @annienguyenUSDS about this in standup tomorrow, but the hearing logic is all in a separate query.

**Comment by annienguyenUSDS** [comment] 2017-11-17 15:42
@astewarttistatech, updated the A/C with Chris.

**Comment by kierachell** [comment] 2017-11-23 16:01
### It works but one question:
- ISSDC = 3
<img width="494" alt="screen shot 2017-11-23 at 10 58 36 am" src="https://user-images.githubusercontent.com/18075411/33181209-577893a0-d03d-11e7-9ddb-f0c73b46f562.png">
<img width="584" alt="screen shot 2017-11-23 at 10 59 03 am" src="https://user-images.githubusercontent.com/18075411/33181214-5a052570-d03d-11e7-9248-6d089f8f6bad.png">

- ISSDC = 3

<img width="717" alt="screen shot 2017-11-23 at 10 56 12 am" src="https://user-images.githubusercontent.com/18075411/33181238-725cf31e-d03d-11e7-9bf8-27cabfa6c8b5.png">
<img width="929" alt="screen shot 2017-11-23 at 10 56 31 am" src="https://user-images.githubusercontent.com/18075411/33181240-73bcabb4-d03d-11e7-8549-a612645394fb.png">


### If there is a withdrawn appeal:
```
OpenStruct ISSKEY="542175W", ISSSEQ=1, ISSDC="W", ISSDCLS=1999-11-16 00:00:00 -0500, ISSDESC=nil, ISSPROG="02", ISSCODE="15", ISSLEV1="03", ISSLEV2="6210", ISSLEV3=nil, ISSPROG_LABEL="Compensation", IS
SCODE_LABEL="Service connection", ISSLEV1_LABEL="All Others", ISSLEV2_LABEL="Chronic otitis externa", ISSLEV3_LABEL=nil
```

And the new appeal has ISSDC=3|L but ISSDCSL is NULL we still show it:
```
ISSKEY="542175", ISSSEQ=1, ISSDC="3", ISSDCLS=nil, ISSDESC=nil, ISSPROG="02", ISSCODE="15", ISSLEV1="03", ISSLEV2="6210", ISSLEV3=nil, ISSPROG_LABEL="Compensation", ISSCODE_LABEL="Service co
nnection", ISSLEV1_LABEL="All Others", ISSLEV2_LABEL="Chronic otitis externa", ISSLEV3_LABEL=nil
```

**Comment by sharonwarner** [comment] 2017-11-28 21:07
@annienguyenUSDS @laurjpeterson 

@kierachell found another case, do we want to filter out withdrawn appeals/issues? For context, here are the possible disposition codes: 

    "1" => "Allowed",
    "3" => "Remanded",
    "4" => "Denied",
    "5" => "Vacated",
    "6" => "Dismissed, Other",
    "8" => "Dismissed, Death",
    "9" => "Withdrawn",
    "A" => "Advance Allowed in Field",
    "B" => "Benefits Granted by AOJ",
    "D" => "Designation of Record",
    "E" => "Advance Withdrawn Death of Veteran",
    "F" => "Advance Withdrawn by Appellant/Rep",
    "G" => "Advance Failure to Respond",
    "L" => "Manlincon Remand",
    "M" => "Merged Appeal",
    "P" => "RAMP Opt-in",
    "Q" => "Recon Motion Withdrawn",
    "R" => "Reconsideration by Letter",
    "V" => "Motion to Vacate Withdrawn",
    "W" => "Withdrawn from Remand",
    "X" => "Remand Failure to Respond"

Maybe we should filter out 9 and W?

**Comment by laurjpeterson** [comment] 2017-11-29 03:10
I agree that withdrawn appeals/issues should not show. Looking again at the list of dispositions, most look like they are not eligible to be heard at a hearing. 

I thought our logic was - for all appeals streams:
- show all issues without dispositions
- if the issue has a disposition, show only issues with dispositions '3' and 'L'. so, do not display issues with any disposition other than '3' and 'L'

@annienguyenUSDS - Is this your understanding as well? I think it is, based on your inclusion of "(any other disposition)" in the AC. But the wording might have made it seem like it only meant grant ('1') or denial dispositions ('4') should not show. 
> issues that have a grant or denial (any other disposition), those issues should not show.

One loophole could be 'P' - RAMP Opt-in. When we originally scoped to just showing '3' and 'L' this disposition was on the list, though, so we may still want to exclude it. I am not sure how this disposition is used.

**Comment by evankroske** [comment] 2017-11-29 15:23
I volunteered to validate this issue. @sharonwarner, when it's ready for validation, could you assign it to me and message me on Slack?

**Comment by sharonwarner** [comment] 2017-11-29 18:55
@laurjpeterson yes, that's true. the problem is that withdrawn appeals don't have disposition dates.

**Comment by annienguyenUSDS** [comment] 2017-12-01 14:47
hey @cmgiven, if you could take a look at the list and see if you know if other types of issues should not be filtered out on the Hearing worksheet.

**Comment by cmgiven** [comment] 2017-12-01 14:54
I don't believe so. My understanding of the reason to include remanded issues is that although they have a disposition, they are still pending. I do not believe that is true of any other disposition.

By the way @sharonwarner, if an issue is withdrawn, the date it was withdrawn is captured by `ISSUES.ISSDCLS`. Not sure if that's what you're looking for.

**Comment by laurjpeterson** [comment] 2017-12-01 15:16
I agree with Chris. 

@sharonwarner to your question about withdrawn appeals/issues. Since they don't have disposition dates but they do have a disposition, I agree that those should be filtered out of the hearing worksheet.

so the updated AC would be:
- show all issues without disposition dates, except withdrawn appeals (dispositions '9' and 'W')
- show all issues without dispositions
- if the issue has a disposition, show only issues with dispositions '3' and 'L'. so, do not display issues with any disposition other than '3' and 'L'

cc: @cmgiven @annienguyenUSDS

**Comment by cmgiven** [comment] 2017-12-01 15:19
I'm not sure what the first bullet is intended to capture. I think the second and third bullets are sufficient.

**Comment by sharonwarner** [comment] 2017-12-01 15:23
@cmgiven got it, thanks. for some reason i thought that withdrawn appeals don't have decision dates.

**Comment by kierachell** [comment] 2017-12-03 23:54
**PASSED**

- I still don't see this show up:
`ISSKEY="3097869", ISSSEQ=1, ISSDC="3", ISSDCLS=2017-09-30 00:00:00 -0500`

but whatever.

**Closed by kierachell** 2017-12-03 23:54 UTC
Labels: caseflow-hearing-prep, In-Validation, requirements-incorrect, tango
