### ISSUE TITLE
Legacy Opt-in | Add issue | Rated and non-rated issue modals

### ISSUE THREAD

**Issue by suzchap** [department-of-veterans-affairs/caseflow#7334] opened 2018-10-10 17:21 UTC
## Story
[Mural showing all opt-in screens](https://app.mural.co/t/workqueue2001/m/workqueue2001/1538676663322/098da798af658862105ea8d4d5aeb03fa7aaf99a)

When a user has a legacy appeal, they will be allowed to "opt-in" to move one or more of those issues into an AMA lane. The AMA paper forms will have a question on them for the applicant to acknowledge that by checking that box, they understand that any legacy issues listed on that form will be moved out of the legacy lane and into the new AMA lane.

This ticket is focused on changing the primary call to action button label, it's destination, and what happens if there isn't a rated issue match.

## Technical notes
- A legacy appeal is active if `active?` is true 🙂(see: https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/legacy_appeal.rb#L494)
- A legacy appeal is eligible if the `soc_date` is set AND either the `soc_date` is within the last 60 days OR the `nod_date` is within the last 372 days. Note that the legacy appeal does not have to be active to be eligible.

## Acceptance criteria
- On the add rating issue and the add non-rating issue modals, the primary call-to-action button is normally labeled "Add this issue" but if the veteran has an active and/or eligible legacy appeal, the button instead should say "next". See technical notes for definitions of eligible and active

## Notes
- Clicking "next" will eventually take the user to the VACOLS modal #7335 , but make it a placeholder for now
- On the "unidentified issue" modal, there is no change (they do NOT get presented with the VACOLS modal)
- If there is no eligible or active legacy appeal for the veteran, there is no change (no VACOLS modal for any sort of issue)

## Mocks
<img width="657" alt="screen shot 2018-10-10 at 2 15 11 pm" src="https://user-images.githubusercontent.com/11219417/46757054-00c77600-cc97-11e8-9354-fb370b328043.png">

## How to Validate
(no need, Shane's got this :muscle:)

**Comment by leikkisa** [comment] 2018-11-19 23:56
I think that this is currently only handling rating request issues.

**Comment by shanear** [comment] 2018-11-20 00:20
![screen shot 2018-11-19 at 7 19 47 pm](https://user-images.githubusercontent.com/1596259/48743220-1897ff80-ec30-11e8-93a9-a021dac373f4.png)
This is still showing up even when the feature flag is turned off 🙁

**Comment by leikkisa** [comment] 2018-11-20 00:37
I was planning on including the nonrating part in my current PR, but I'm thinking it might make more sense to do in a separate PR on this original ticket.  

Another thing that I think might be an issue is that based on my current PR, it sounds like they should be able to select an ineligible legacy issue (but then it will be marked as ineligible), but I think only the eligible legacy issues are showing up.

**Comment by shanear** [comment] 2018-11-20 01:18
Never mind 🙃. Some feature flag and deployment stuff was the cause. It is working! 👍

**Comment by leikkisa** [comment] 2018-11-21 22:46
This was already validated, but I added the nonrating modal to this ticket, so moved it here in case you want to validate that.

**Comment by shanear** [comment] 2018-11-26 17:38
>This was already validated for rating, but I added the nonrating modal to this ticket, so moved it here in case you want to validate that.

Good call. I validated it 👍

**Closed by shanear** 2018-11-26 17:38 UTC
Labels: In-Validation, caseflow-intake, sierra, validation-failed
