### ISSUE TITLE
Fix assigned_to_location returning "Case storage" for legacy appeals

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#13262] opened 2020-01-27 15:15 UTC
VLJ support has reported that the "Assignee" filter in their organization table contains assignees that should not be there, such as "Case storage". This is caused by our preference to grab the assigned_to_label of an [active task over one that is on hold](https://github.com/department-of-veterans-affairs/caseflow/blob/2da86f8f58addc7c464d33967039c3e52adde58e/app/models/legacy_appeal.rb#L742). 

For legacy appeals, when a colocated task is put on hold, `assigned_to_location` will return "Case storage".

```ruby
task = ColocatedTask.on_hold.where(appeal_type: LegacyAppeal.name, assigned_to_type: User.name).last
appeal = task.appeal
puts appeal.structure_render(:status)
LegacyAppeal [status]
├── RootTask assigned
└── OtherColocatedTask on_hold
    └── OtherColocatedTask on_hold
        └── TimedHoldTask assigned
```
Because `assigned_to_location` ignores tasks that are hidden from queue table view (`TimedHoldTask`s) it will pull the `assigned_to_label` of the only other active task, the root task.

### AC
- [ ] `assigned_to_location` of a legacy case with open `ColocatedTask`s returns the assignee of the on hold task, not case storage
- [ ] [`assignees_for_vacols_id`](https://github.com/department-of-veterans-affairs/caseflow/blob/b5f73f3e5bb0cd6429fd2d9540c69c79454da7d4/app/jobs/update_cached_appeals_attributes_job.rb#L217) uses same logic

**Comment by ajspotts** [comment] 2020-01-31 18:15
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | |||||||
3 | ||||
5 | 
8 |  
```
This logic is fairly complex because it is based on the board's business need to determine who was last responsible for an appeal, rather than just who the task is currently assigned to, so we should be careful to only change the logic as intended in this ticket and no more.

**Closed** 2023-04-25 15:51 UTC
Labels: Feature: queue-table-view, Team: Echo 🐬, Priority: Medium
