### ISSUE TITLE
Add instructions to reassigned tasks of inactive users

### ISSUE THREAD

**Issue by hschallhorn** [department-of-veterans-affairs/caseflow#12506] opened 2019-10-29 18:57 UTC
Spun out of #12483.

[Some slack chatter.](https://dsva.slack.com/archives/CJL810329/p1572369656018000?thread_ts=1572295303.028100&cid=CJL810329)

We should be documenting reasoning why we are cancelling or reassigning tasks of inactive users so that the history exists in the database. An additional benefit of doing this is so that users can see why they are receiving a task or why downstream children were cancelled.

### AC
- [ ] When a user's tasks are reassigned or cancelled in the reassign rake task, add instructions as to why the task was created, reassigned, or cancelled

**Comment by lowellrex** [comment] 2019-10-31 13:53
Note: Run this _verbiage_ by design/product before releasing into the wild. Also, make sure to put this copy in `COPY.json` so design/product can more easily update this.

_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | ||||
2 | ||||||||
3 | ||||||
5 | 
8 | 
```

Estimating this at 2. Maybe a 3 because we may want to display this particular type of message different than how we display other task instructions. Possible 3 because it may be tricky to pass the instructions to new tasks created by callback hooks, will also need to update `task.reassign()` function. Maybe a 1 because we may be able to "diff the task trees" after the fact and append the instructions to any new tasks that were created, will still be tricky to decide where to put this particular logic.

**Closed** 2019-12-05 20:29 UTC
Labels: content ✍🏽, echo
