### ISSUE TITLE
Establish claim fails for higher level review and supplemental claim flows when adding a non-rating issue

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#5903] opened 2018-06-12 23:34 UTC
When a non-rating issue is added to a HLR or SC, the resulting call to create contentions in VBMS throws an error.

## Acceptance Criteria
- HLR and SC with non-rating issues should correctly create the EP and associated contentions in VBMS

## Technical Notes
This is the XML blob with the VBMS error in it
```
VBMS::HTTPError: status_code=500, body=<env:Envelope xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Header/><env:Body><env:Fault><faultcode>env:Server</faultcode><faultstring>Error validating ClaimService data input. GUID: f9bc41eb-fafc-482b-a8e0-3f4e6a56e033</faultstring><detail><ns4:dataValidationFaultDetailBean xmlns:ns4="http://vbms.vba.va.gov/external/ClaimService/v4" xmlns:ns3="http://vbms.vba.va.gov/cdm/participant/v4" xmlns:ns1="http://vbms.vba.va.gov/cdm/common/v4" xmlns:ns0="http://vbms.vba.va.gov/cdm/claim/v4"><ns4:formFieldErrors><ns4:fieldName>Title</ns4:fieldName><ns4:errorType>MINIMUM_LENGTH_NOT_SATISFIED</ns4:errorType><ns4:message>The minimum data length for the Title within the contentionsToCreate was not satisfied: The Title must not be empty.</ns4:message></ns4:formFieldErrors></ns4:dataValidationFaultDetailBean></detail></env:Fault></env:Body></env:Envelope>, request=#<VBMS::Requests::CreateContentions:0x007fa818257d90 @veteran_file_number="984562357", @claim_id="600131031", @contentions=[nil, "Service connection for pain disorder is granted with an evaluation of 70 percent effective May 1, 2013.", "Entitlement to individual unemployability is granted effective May 1, 2013."]>
```

**Comment by leahbannon** [comment] 2018-06-12 23:43
* I was using 984562357 
* enter date
* selected 2 check boxes for issues
* clicked Add Issue > chose Unknown from dropdown > wrote no description
* click Establish EP

**Comment by leahbannon** [comment] 2018-06-12 23:47
This is related to anything with adding additional non-rated issues. It breaks no matter what category or description I add.

**Comment by leikkisa** [comment] 2018-06-19 18:14
@leahbannon Does it work when you do add a description?

**Comment by leikkisa** [comment] 2018-06-19 20:12
@abbyraskinUSDS @leahbannon 

So upon reading Leah's comments in #5903, it seems like the contentions only fail when the description is blank. Leah can you confirm? If this is the case, there is a different solution, some of the stuff we talked about in the design/validation meeting we had.

I greyed out the "Add issue" button if there's an issue with a blank description, and have some data clean-up happening so anything without a category or description won't get sent to the back end (before we just had it filtering empty categories because we weren't sure if descriptions were required).  If the bug is only with empty descriptions, this will at least fix the bug.  I haven't merged yet though, will wait to hear back.

In addition, we can either prevent establishing the EP if there's an issue without category or description, but then we need to add a delete button for the issue that has been added.  Another thing we can do is let them submit it and have it error, returning them to the page and saying that they need to fill those in.

**Comment by leahbannon** [comment] 2018-06-20 18:11
I can confirm this fails if the description is blank. It works fine if both category + description are included. I didn't get to test no category + description. 

How do we want to handle someone selecting an comp issue checkbox, choosing a category in the add issue dropdown, and then not including anything? Should we allow them to proceed and ignore it? Show an error message telling them to remove the category or add a description when they click create EP?

**Comment by abbyraskinUSDS** [comment] 2018-06-20 18:39
Did AMO say whether the description field should be mandatory?

**Comment by leikkisa** [comment] 2018-06-20 19:57
It seems like it is mandatory based on the error Leah was getting.  So that answers one question! I think the rest of what we need to figure out is design oriented.

**Comment by abbyraskinUSDS** [comment] 2018-06-21 13:40
OK, I meant more as a business rule, does it need to be filled in. We could just pass the category as the contention. If they just select "Apportionment" with no description, I would think they could still create the EP. We should confirm with AMO.

**Comment by abbyraskinUSDS** [comment] 2018-06-22 14:43
@leikkisa should i add the validation messages to this ticket, or create a new one?

**Comment by leikkisa** [comment] 2018-06-22 17:43
I think the right ticket to add to is actually this one:
https://waffle.io/department-of-veterans-affairs/caseflow/cards/5af4bd8267ae37001de55adc

I think I should clean up the code on this ticket and move it to validation because it's not failing anymore.  This and the other ticket have gotten a little mixed up.

**Comment by leikkisa** [comment] 2018-07-23 21:45
888451290 should be a good number for this one.

**Comment by leikkisa** [comment] 2018-08-14 18:56
@suzchap I'm moving this to done because Sandra successfully did it on her last round of VBMS testing.

**Closed** 2018-08-14 18:56 UTC
Labels: bug-medium-priority, caseflow-intake, sierra
