### ISSUE TITLE
[Post Mortem] VBMS SSL Errors

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#3037] opened 2017-08-22 13:29 UTC
Date: 08/18/2017
Authors: Sharon Warner
Status: VBMS team debugging issue 

## Summary
Starting August 16th, approximately 1% of our VBMS calls have resulted in VBMS errors. We notified the VBMS team, determined this is true across many other applications that hit VBMS, and the VBMS team is working to resolve.

## Root Causes
The VBMS team performed maintenance the night of August 16th which had unintended consequences.

## Trigger
A seemingly random assortment of API calls (<1%) to VBMS result in SSL errors.

## Resolution
We notified the VBMS team through email, created a ticket through NDS, and the VBMS team is working on a resolution.

## Detection
We got a sentry alert on slack at 11:40 PM on August 16th. https://sentry.ds.va.gov/department-of-veterans-affairs/efolder/issues/366/

## What went well?
 - VBMS team was aware of the issue and gave us statistics early on so that we know the problem is not isolated to Caseflow.
 - Michael Fraysher from BEP called us to coordinate proxy testing. We were seen as a team they trust.

## What didn't go well?
 - We should have a way to quickly gather and categorize VA errors. We didn't know the error statistics until much later. Grafana charts might need tuning, or we need better stats in the app collector.

## Action Item
Find a better way to categorize error https://github.com/department-of-veterans-affairs/appeals-deployment/issues/807

**Comment by askldjd** [comment] 2017-08-22 14:04
Here's some update:

I started with strictly using curl against the VBMS main url (https://services.vbms.vba.va.gov) and could not reproduce this problem.

Then I went on uat and prod and started an infinite loop document fetch using a single thread
```ruby
d = Document.last; i=0; while true do puts i; VBMSService.fetch_document_file(d); i+=1; end
```

I was able to reproduce this problem in UAT and Prod. Here are the number of requests it takes for this to happen:

Prod: 1352, 1695, 2925
UAT: 8426, 12764

Overall, the low error rate makes this problem fairly difficult to debug using live packet capture. I have pinged VBMS ProdOps team with this data and see how they want to proceed forward.

**Comment by askldjd** [comment] 2017-08-22 21:41
Aaron Sisk from VBMS replied and there hasn't been any update. The ESD ticket is I16077948FY17.

**Comment by kierachell** [comment] 2017-08-29 13:21
Seems like the errors have been resolved. Is there any action items for us to handle?

What about a configurable retry logic for our VBMSService, since we have several errors that just seem to pop up here and there:
- SSL errors
- SOAPError
- NetworkTimeout

@joofsh had a PR for `connect_vbms` that was sorta doing that

**Comment by askldjd** [comment] 2017-12-06 03:25
Closing this. We have Envoy now to resolve these occasional SSL errors. :)

![image](https://user-images.githubusercontent.com/3258724/33643083-1243bef4-da0b-11e7-9991-56f4a8f8aafd.png)

**Closed by askldjd** 2017-12-06 03:25 UTC
Labels: post-mortem
