### ISSUE TITLE
Investigate Bad State For Judge Queue post Attorney Assignment

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#15620] opened 2020-11-18 19:53 UTC
## Description
We had a user end up on a queue page with only phantom tasks that had 100+ days waiting. Bat team confirmed there were no actual cases in that state, but we should check we are properly clearing state to avoid startling users and worrying them.

If the user clicks on one of these phantom tasks it will result in a permissions error as they are being linked to `queue/appeals/undefined` 

![image](https://user-images.githubusercontent.com/6129479/99580093-17c80e80-29ad-11eb-8053-dc2ff9c23c52.png)

> They were not in my normal Caseflow queue "cases to assigned to you" (which currently has 14) or under "cases to be assigned." (currently 21)
> It's a page I've never seen before that popped up after I transferred an AMA case to an attorney. And this just lists "your cases" and appears to include both cases assigned to me (the 14 above) and these weird phantom cases.

## Acceptance criteria
- [ ] Investigate State behavior after VLJ assigns AMA cases to an Attorney for bugs
- [ ] Fix or file tickets to fix any bugs discovered

## Background/context/resources
[Bat Team Discussion](https://dsva.slack.com/archives/CHX8FMP28/p1605645496065700)

**Comment by ajspotts** [comment] 2020-12-08 17:07
This issue has come up again in 🦇 for the same user in a different [ticket](https://dsva.slack.com/archives/CHX8FMP28/p1607445750092300)

**Comment by hschallhorn** [comment] 2020-12-08 20:36
### Steps to reproduce:
1. Log in as a bvaaaaaabshire
1. go to their assign queue http://localhost:3000/queue/BVAAABSHIRE/assign
1. click on any ama appeal
1. assign the task to any attorney
1. Click through your pages without refreshing (phantom tasks should start on the second page)
1. Check out the props of your components in the dev console, there should be around 67 phantom tasks being passed to QueueTableBuilder
![Screen Shot 2020-12-08 at 3 05 40 PM](https://user-images.githubusercontent.com/45575454/101535576-dbae1b00-3966-11eb-9ed1-c851d5f23ed3.png)
7. Click a phantom task and note error

### What the heck are they?

These "tasks" seem to be differently formed than the legitimate tasks

Standard legacy tasks|phantom tasks
---|---
![Screen Shot 2020-12-08 at 3 12 15 PM](https://user-images.githubusercontent.com/45575454/101536341-df8e6d00-3967-11eb-8b3f-1abd50399980.png)|![Screen Shot 2020-12-08 at 3 12 23 PM](https://user-images.githubusercontent.com/45575454/101536348-e1583080-3967-11eb-94ab-351fed06131b.png)

Looking at the task tree for one of the appeals results in:
```ruby
                                                                ┌────────────────────────────────────────────────────────────────────────┐
Appeal 71 (direct_review) ───── │ ID   │ STATUS    │ ASGN_BY     │ ASGN_TO     │ UPDATED_AT              │
└── RootTask                    │ 177  │ on_hold   │             │ Bva         │ 2020-11-30 15:17:05 UTC │
    ├── DistributionTask        │ 178  │ completed │             │ Bva         │ 2020-11-30 15:17:05 UTC │
    ├── JudgeAssignTask         │ 179  │ completed │             │ BVAAABSHIRE │ 2020-12-08 19:52:58 UTC │
    └── JudgeDecisionReviewTask │ 3466 │ on_hold   │ BVAAABSHIRE │ BVAAABSHIRE │ 2020-12-08 19:52:58 UTC │
        └── AttorneyTask        │ 3467 │ assigned  │ BVAAABSHIRE │ BVAEERDMAN  │ 2020-12-08 19:52:58 UTC │
                                └────────────────────────────────────────────────────────────────────────┘
```

Looks like these are all tasks

### Where these come from
These tasks are legacy tasks [passed into the judge queue](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client%2Fapp%2Fqueue%2FJudgeDecisionReviewTaskListView.jsx#L51) through assignedTasks to [add them to tasks that come through queue config in the assigned tab](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client%2Fapp%2Fqueue%2FJudgeDecisionReviewTaskListView.jsx#L51). These tasks are selected by the [`judgeLegacyDecisionReviewTasksSelector`](https://github.com/department-of-veterans-affairs/caseflow/blob/aea0b24b8e570af5b5548a1374d82cc2ca64f7ff/client%2Fapp%2Fqueue%2Fselectors.js#L168-L171). These phantom tasks do indeed have a label of "Review"
![Screen Shot 2020-12-08 at 3 10 45 PM](https://user-images.githubusercontent.com/45575454/101536157-a1914900-3967-11eb-8982-ed65b2b276c4.png). This leads me to believe that this is an issue of tasks from the previous queue endpoint (assign queue) not being cleared out when we receive legacy tasks when the new queue loads.


### How do we set legacy tasks in our store from the back end?
Any time a queue is visited, we [request all tasks assigned to the user](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client%2Fapp%2Fqueue%2FQueueLoadingScreen.jsx#L106-L110) from the back end. Legacy tasks are loaded from the legacy tasks controller [here](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client%2Fapp%2Fqueue%2FQueueLoadingScreen.jsx#L50) and set in the store with [`onReceiveQueue`](https://github.com/department-of-veterans-affairs/caseflow/blob/77e79bd619e33ea3d6480c0e8ef2d669cd2b0353/client%2Fapp%2Fqueue%2FQueueLoadingScreen.jsx#L51-L54). This coincides with the [`receiveQueueDetails`](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client%2Fapp%2Fqueue%2Freducers.js#L57-L69) reducer which specifically uses `merge`, meaning old tasks are not cleared out of store.


### Things I ruled out
1. incorrect ama tasks coming through queue config on the back end
1. incorrect legacy tasks coming from the back end 

### Implementation idea
Write a test that fails with the current implementation. Would be nice to catch this with automated testing rather than user reports.

1. Update `receiveQueueDetails` to use `set` rather than merge.
1. Create a new action that does not mess with other actions that use `onReceiveQueue` that just sets legacy tasks when we get them from the back end
1. Pass legacy tasks through queue config and stop checking state for judge queues and passing `assignedTasks` to queue table builder (attorney task list view would also need to be updated)

**Closed** 2023-04-25 15:43 UTC
Labels: Type: Investigation, Type: Bug, User: Judge, Stakeholder: BVA, Source: Bat Team, Team: Echo 🐬, Priority: Low
