### ISSUE TITLE
Post AMA Foxtrot technical debt brainstorming session

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#9552] opened 2019-02-20 19:16 UTC
@aroltsch commented on [Wed Feb 06 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49)

I created this ticket to start entering any tech debt refactors we could work on after the AMA deadline. This is just a brainstorming session kind of ticket so any ideas are welcome. We will then create subsequent tickets to tackle individual problems. 

1. Use New Relic to find large DB transactions and break them up into smaller transactions if possible
1. Get rid of legacy tasks
1. Speed up feature tests
1. Fix n+1 queries
1. BGS caching
1. Fix logout button
1. Refactor attorney_case_reviews 

---

@monfresh commented on [Thu Feb 07 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49#issuecomment-461454137)

This is a great list. I would also recommend using the [coverband](https://github.com/danmayer/coverband) gem, which will let us know which lines of code are invoked the most in production. This will allows us to prioritize improvements.

---

@mdbenjam commented on [Thu Feb 07 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49#issuecomment-461465660)

🙌 Great list!

I would add turning on bullet in tests to 4.

One other thought:
- Refactor attorney and judge flows. They're super complicated right now, and I think we should probably get rid of `EditModalBase` and `DecisionReviewBase`. Two higher level components I suggested adding that I think were a bad direction.

---

@youngfreezyVA commented on [Thu Feb 07 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49#issuecomment-461479504)

Awesome list! I will keep adding items as I think of them. one thought: I think we should look into whether we want to keep `Flow` or not. there's no easy way to handle `defaultProps` with Flow https://github.com/facebook/flow/issues/1660. 

---

@monfresh commented on [Thu Feb 07 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49#issuecomment-461481197)

Another thing I've noticed is that we use Ruby a lot for queries where we can use ActiveRecord/SQL instead. Is there a reason for that? I would add that to the general DB performance theme.

---

@mdbenjam commented on [Thu Feb 07 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49#issuecomment-461492313)

I echo getting rid of flow. I don't think it solves a concrete problem for us, and have found it slows down development.

---

@aroltsch commented on [Thu Feb 07 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49#issuecomment-461564414)

Clean up feature flags. 

---

@aroltsch commented on [Thu Feb 07 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49#issuecomment-461564651)

`ama_decision_issues` is enabled for all so let's get rid of `ama_decision_issues` flag in the code and any old code around that.

---

@aroltsch commented on [Fri Feb 08 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49#issuecomment-461943828)

Improve FE sentry error description that shows up in Slack

---

@aroltsch commented on [Fri Feb 08 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49#issuecomment-461944337)

Refactor seed data 

---

@joeyyang commented on [Fri Feb 08 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49#issuecomment-461945334)

> Refactor seed data

Include data in the seed data such that there is data for every code path and feature in the application, so a developer running the application locally can verify that things work.

---

@laurjpeterson commented on [Fri Feb 08 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49#issuecomment-461947052)

Leave behind documentation so people in 2070 can understand our code! h/t @joeyyang 

---

@aroltsch commented on [Tue Feb 12 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49#issuecomment-462943550)

Rails hanging locally

---

@monfresh commented on [Thu Feb 14 2019](https://github.com/department-of-veterans-affairs/dsva-vacols/issues/49#issuecomment-463693312)

Don't use exceptions for flow control. Why? Raising an exception is slow. It's also [discouraged](https://github.com/rubocop-hq/ruby-style-guide#no-exceptional-flows) by the official Ruby Style Guide.

From [_The Complete Guide to Rails Performance_](https://www.railsspeed.com/):

> the thing that makes exceptions so expensive in Ruby is all the work required to gather up a stack trace and package it in [the exception's backtrace method](https://ruby-doc.org/core-2.5.0/Exception.html#method-i-backtrace).

For example, we have a bunch of instances where we rescue from various ActiveRecord errors such as `ActiveRecord::RecordNotFound` or `ActiveRecord::RecordInvalid`. This is because we use methods like `find` that will raise an error. Instead, we should use `find_by` and use regular logic to deal with the expected error scenarios. Similarly, when creating or updating a record, instead of using `save!` or other similar bang methods that raise errors, we should initialize the record and then check if it is valid before updating or saving it.

Here are a couple of benchmarks that show how exceptions are slower:
### Validating a record:
```ruby
require "benchmark/ips"

def slow
  task = Task.new(status: "on_hold")
  task.save!
  "task valid"
rescue ActiveRecord::RecordInvalid
  "invalid task"
end

def fast
  task = Task.new(status: "on_hold")
  if task.valid?
    task.save
    "task valid"
  else
    "invalid task"
  end
end

Benchmark.ips do |x|
  x.report("exception") { slow }
  x.report("if_else") { fast }
  x.compare!
end
```
Result:
```
Comparison:
             if_else:     1724.3 i/s
           exception:      374.5 i/s - 4.60x  slower
```
### Finding a record:
```ruby
require "benchmark/ips"

def slow
  task = Task.find(1000)
  task.closed_at = Time.zone.now
rescue ActiveRecord::RecordNotFound
  "could not find task"
end

def fast
  task = Task.find_by(id: 1000)
  if task
    task.closed_at = Time.zone.now
  else
    "could not find task"
  end
end

Benchmark.ips do |x|
  x.report("exception") { slow }
  x.report("if_else") { fast }
  x.compare!
end
```
Result:
```
Comparison:
             if_else:     1144.0 i/s
           exception:      923.5 i/s - 1.24x  slower
```

Another way to think about exceptions is that they are meant to represent unexpected scenarios. Invalid data is more often than not a common and expected occurrence. We expect users to enter invalid data, such as invalid Document IDs.

**Comment by aroltsch** [comment] 2019-02-21 13:45
Clean up duplicate user records in Caseflow DB.

**Comment by monfresh** [comment] 2019-02-27 02:14
Update code complexity Rubocop settings like Class/Module/Method Length and ABC size to match default settings. This will ensure the code quality keeps improving.

**Comment by joeyyang** [comment] 2019-02-28 18:59
Include top-of-file comments for `.rb`, `.js`, and `.jsx` (here's a [tech spec](https://github.com/department-of-veterans-affairs/caseflow/issues/9619) I wrote)

**Comment by mdbenjam** [comment] 2019-04-04 18:50
Development setup fixes:
1. Fix freezing rails server (it would freeze for me regularly when I made some types of changes to the backend, and would require a restart)
2. Combine our development and test FACOLS containers into one container. i.e. have two schemas within the database. I think this will reduce the overhead we experience running two containers.
3. Try to reduce resource use of FACOLS. https://github.com/department-of-veterans-affairs/caseflow/blob/master/local/vacols/vacols_copy_1_tablespaces.sql#L3 I reduced the numbers specified here from what VACOLS had, but we can probably cut them down even more!
4. Reduce seed time. Running `rake db:seed` takes a long time. I think I might be the culprit here with this line: https://github.com/department-of-veterans-affairs/caseflow/blob/master/db/seeds.rb#L1046 Work with @lomaxap to remove it.
5. Slow application startup. We load a lot of things when the application, and setup a lot of test data. I think a lot is called by this: https://github.com/department-of-veterans-affairs/caseflow/blob/master/lib/fakes/initializer.rb#L56. We could try to do this lazily instead.
6. We run initializers we shouldn't run on rake commands. i.e. https://github.com/department-of-veterans-affairs/caseflow/blob/master/config/initializers/shoryuken.rb#L14 we shouldn't need localstack to be running to run `rake db:migrate`

Closing out my frontend technical debt ticket and copying it all here: https://github.com/department-of-veterans-affairs/caseflow/issues/9592

1) CSS in the application
   - We have no real organization of our CSS. A lot is in a common file, some are in files specific to components, and some are in the component files themselves. We should standardize on an approach.
   - My preference is in-component styles.
   - There are likely lots of styles that can be removed.
2) Component clean up
   - Lots of our components are messy. They have lots of props, some are only used in 1-2 places. Some of the components need very specific css classes applied to work.
   - Components should be drop in and should just work.
   - We need to add new styling components so that developers don't have to write CSS. For example an `<IndentText>` component and a `<Note>` component that grays out text. I'd like to encapsulate our commonly used styles into components.
3) Consolidate Caseflow Frontend Toolkit.
   - About a year ago one of our developers started moving some of our components to a separate repo called caseflow-frontend-toolkit. The problem is only a small subset of components were moved over and there wasn't buy in from the team.
   - We either need to go all in on the toolkit or fold it back into Caseflow. I think if we get our components into a solid state where there isn't much churn, moving them to the toolkit is a good idea. Otherwise we need to probably just fold them back in.
4) Too much state in redux
    - When we moved to use redux we put everything in redux and left nothing in local state. I think this has made our frontend more complex than necessary.
    - I don't know that it makes sense to remove things from redux, but it might be good to set guidelines for when things should be in redux and when they should be in local state.
5) Apps are in separate router hierarchies so that moving from one app to another requires page loads.
   - Not sure if this is something we should definitely do, but I think it would be nice if all of our apps were under one react router so that moving between them was more seamless.

**Comment by pkarman** [comment] 2019-04-04 18:55
could we turn each of these into its own ticket and make this an Epic?

**Closed** 2023-04-25 15:58 UTC
Labels: Type: Tech-Improvement, Team: Foxtrot 🦊, Product: caseflow-intake, Source: Sentry Alert, Priority: Medium
