### ISSUE TITLE
Support "Out of Service" mode

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow#544] opened 2016-12-07 21:55 UTC
When external dependencies go down, we need to quickly declare the application to be out of service. Ideally, if `OUT_OF_SERVICE` is defined, it will prevent user from making changes to the site.

See also https://github.com/department-of-veterans-affairs/appeals-deployment/issues/270

**Comment by shanear** [comment] 2016-12-09 21:36
this is a duplicate of #248. closing

**Closed by shanear** 2016-12-09 21:36 UTC
Labels: Triage
