### ISSUE TITLE
Appeal DTA Errors | Set the DTA payee code for Appeal DTA errors correctly based on historic data

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#8676] opened 2019-01-13 01:43 UTC
For appeals intake, users do not input the payee code of the claimant.

If we create a follow up supplemental claim, then we don't know what payee code the claimant should be when we create the EPs.

Is there a way to properly determine the payee code even though the intake at the Board did not select it. 

AMO Said if it would help, we could narrow the list down to:
<img width="533" alt="screen shot 2019-01-15 at 9 55 27 am" src="https://user-images.githubusercontent.com/1596259/51199708-591c9e00-18ac-11e9-9bdf-505664f75b51.png">

related to https://github.com/department-of-veterans-affairs/caseflow/issues/8649

## Acceptance Criteria
- When setting the payee code on an 040 EP generated by a Board Appeal DTA error, use the logic from https://github.com/department-of-veterans-affairs/caseflow/issues/8649 to determine what it should be set to.

### Validation
- Find or create a HLR or SC with a non-Veteran claimant. This will ensure that Veteran has an end product which stores the payee code for that claimant.
- Create an Appeal with the same Veteran. Select the same claimant as the claimant.
- Have Colin decide an issue on the Appeal with a DTA error
- Check that the payee code on the new Supplemental Claim is populated correctly for the claimant.

**Comment by leikkisa** [comment] 2019-01-29 23:04
Just taking some notes here:
C&P is for compensation and pension
CH35 is an Education award, which right now does not require payee code
DIC is available to a spouse or child for a deceased veteran - ask AMO if this should always be used for deceased veterans or if we might ever want to use the regular "spouse" or "child"

Institutional Vets seems related to Vets that have a fiduciary, more info here: https://www.knowva.ebenefits.va.gov/system/templates/selfservice/va_ssnew/help/customer/locale/en-US/portal/554400000001018/content/554400000014264/M21-1,-Part-III,-Subpart-v,-Chapter-6,-Section-E---Institutional-Awards-Specific-to-Incompetent-Veterans

**Comment by leikkisa** [comment] 2019-02-01 18:56
It seems like we can only automatically select the payee code in the case that the claimant has a previous claim for the same Veteran file number.  I wonder if this will always be the case (since it's an appeal and presumably there was an original claim), but if not then we'll need to find another solution for the Appeal DTA Supplemental Claims.

Some info from Nathan Jolly and Mary Kate:
Nathan: I confirmed with the dev team that VBMS only defaults a Payee Code if the dependent is already on a claim. Otherwise, when the user enters the desired payee code, VBMS will present any current dependents that may fall under that code and give the option of adding a new dependent. If you setup defaults for all Payee codes you are going to run into issues when there are multiple spouse records which are handled differently.

Mary Kate: Correct – that’s when there’s a system issue - if you would establish a claim using a payee code that is already assigned to another participant on that file OR if the participant already has a payee code on this file and you choose a different one.

**Comment by leikkisa** [comment] 2019-02-01 19:18
On second thought, it sounds like the constraint is that the same payee code can't be used twice, and that if a participant has had one payee code in the past that it can't change.  This might be something we can handle (e.g. check if first child has been used, and if so, a different child would get second child).  There aren't any obvious ones for second spouse but we can ask about that.

**Comment by leikkisa** [comment] 2019-02-01 19:35
Mary Kate is also thinking maybe they'll always have a previous claim since these are appeals, so we might not need to worry about it. We should probably go with previous claim, and if there is none, it would get surfaced by a failure.

**Comment by jiahuang** [comment] 2019-02-01 21:50
Had further talks with Sally, and proposal for now is:
- find appeal claimant
- find previous claim for that veteran file number
	- use payee code from there. This is similar to the previous PRs but without the default relationship type guess.

If we cannot find a prior payee code for the claimant:
- throw error, do not establish SC
- if DTA SC creation fails, then the Appeal that kicked it off shows up as failed in the asyncable jobs page
- if DTA SC creation succeeds, but the sync fails then only SC shows up as failed in the asyncable jobs page

**Comment by steve-gov** [comment] 2019-02-14 17:24
Set up a board appeal for a spouse at https://appeals.cf.uat.ds.va.gov/queue/appeals/5bf0bff8-17b0-45ef-b9bf-6cb0ab547816 and requested outcoding as DTA ERROR.

**Comment by steve-gov** [comment] 2019-02-20 16:59
Setting up a first-child (payee `011`) DTA SC from a board appeal.

**Comment by Sjones352** [comment] 2019-03-13 23:52
@leikkisa and @pkarman can someone be so kind and provide validation instructions for this one. I would to continue with what @steve-gov had done in the previous comment but first I need to understand validation instructions.

**Comment by pkarman** [comment] 2019-03-14 13:43
@Sjones352 Do the Validation instructions in the issue description (top) need clarifying? Which step isn't clear?

**Comment by Sjones352** [comment] 2019-03-14 19:41
### Step 1 Higher Level Review
<img width="1680" alt="Screen Shot 2019-03-14 at 3 27 50 PM" src="https://user-images.githubusercontent.com/23080951/54386280-f9096480-466e-11e9-8b2a-bc06975cf395.png">
<img width="1680" alt="Screen Shot 2019-03-14 at 3 28 07 PM" src="https://user-images.githubusercontent.com/23080951/54386282-f9096480-466e-11e9-8783-cad508dc6516.png">
<img width="1421" alt="Screen Shot 2019-03-14 at 3 29 10 PM" src="https://user-images.githubusercontent.com/23080951/54386283-f9096480-466e-11e9-8041-84aca74194d3.png">
<img width="1406" alt="Screen Shot 2019-03-14 at 3 29 38 PM" src="https://user-images.githubusercontent.com/23080951/54386284-f9096480-466e-11e9-99c0-d8b2392d9dc1.png">

###  Step 2 Appeal created
<img width="1369" alt="Screen Shot 2019-03-14 at 3 33 12 PM" src="https://user-images.githubusercontent.com/23080951/54386285-f9a1fb00-466e-11e9-8687-b5370a90016a.png">
<img width="1397" alt="Screen Shot 2019-03-14 at 3 35 21 PM" src="https://user-images.githubusercontent.com/23080951/54386286-f9a1fb00-466e-11e9-83ab-bc9847dbbf17.png">
<img width="1354" alt="Screen Shot 2019-03-14 at 3 35 44 PM" src="https://user-images.githubusercontent.com/23080951/54386288-fa3a9180-466e-11e9-9e4b-2bed4f172940.png">

### Step 3 
Asking Colin decide an issue on the Appeal with a DTA error

**Comment by Sjones352** [comment] 2019-03-20 15:42
Following up with Colin on this issue.

**Comment by Sjones352** [comment] 2019-03-26 14:50
Reached out to Colin again but he has not replied yet

**Comment by Sjones352** [comment] 2019-03-26 15:12
Colin has validated this issue so closing it.
<img width="859" alt="Screen Shot 2019-03-26 at 11 09 48 AM" src="https://user-images.githubusercontent.com/23080951/55008815-f5070c00-4fb7-11e9-808f-3f8080396a55.png">

**Closed by Sjones352** 2019-03-26 15:12 UTC
Labels: In-Validation, caseflow-intake, sierra
