### ISSUE TITLE
API: Effectuation alerts for non-comp/pension

### ISSUE THREAD

**Issue by marvokdolor-gov** [department-of-veterans-affairs/caseflow#9480] opened 2019-02-19 13:32 UTC
### Goal
Add an effectuation alert to the decision`alerts` array **if** it is eligible for appeal.
```
...
{
  "type": "bva_decision_effectuation",
  "details": {
    "bvaDecisionDate": "2019-05-01",
    "aojDecisionDate": "2019-07-15"
  }
}
...
```
- [ ] @cmgiven to verify the above

### Context
- Whether an effectuation can be appealed depends on the specifics of what is being granted.
- If a board grant is made on a decision that IS non-comp or pension, effectuation is tracked via Caseflow, see #8299.
- Connects to #8840 and #9163

**Comment by cmgiven** [comment] 2019-03-05 16:00
I believe this is a status, not an alert?

A status is used to describe what's currently happening on an appeal. An alert is used to describe an action that the Veteran can take.

**Comment by marvokdolor-gov** [comment] 2019-03-05 16:29
Makes sense. 
Mind updating the sample code to line up with the correct approach please?

**Comment by cmgiven** [comment] 2019-03-05 16:50
I'm not clear on what the issue is for. Looks like we already have the status. Is this maybe indicating that the `amaPostDecision` alert does not currently appear for VBA effectuation of Board decisions?

**Comment by marvokdolor-gov** [comment] 2019-03-05 16:52
@mc-usds mind chiming in here whenever you have a minute please?

**Comment by mc-usds** [comment] 2019-03-06 15:30
Oh this was for effectuations that do not have an EP.  At the time I wasn't sure if there needed to be an alert for that case. My understanding is that we will only include an effectuation alert if the effectuation has an EP in VBMS.  

Closing this.

**Closed by mc-usds** 2019-03-06 15:30 UTC
Labels: Triage, appeal-status, appeals-status-api
