### ISSUE TITLE
Add Hearing icon to queue/case views

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#7478] opened 2018-10-20 00:12 UTC
When judges are assigning work to their attorneys, they want to see if a hearing has been held for a case. We think this will be useful to more users than just judges, so will apply this to more than just judge views. 

## AC
- Wherever there is a table (attorneys, judges assign/review, co-located, generic), there is an icon indicating that a hearing has been held on the case
- This indicator only shows up when a hearing has the disposition type of held

Note:
- We only have this for legacy appeals right now.
- We may need to adjust this when AMA appeals start to have hearings. This is because the hearing docket type indicator and hearing held indicator could be redundant. 

## Mocks
@sneha-pai to add by 10/24. This will be an engineering task that someone can pick up when they have downtime.

**Comment by joeyyang** [comment] 2018-11-01 22:06
Hi @sneha-pai! I'm almost ready to get to this in the next day or two, just checking in on mocks.

**Comment by lowellrex** [comment] 2018-11-01 22:10
Perhaps we will use the "H" badge from this mock from ticket #6963?
![image](https://user-images.githubusercontent.com/1598889/45507289-a6063180-b75f-11e8-951c-5f5b73afe2ba.png)

**Comment by laurjpeterson** [comment] 2018-12-05 22:39
i think we can use mocks from this search results tickets for incorporating the `H` badge into queue table views

https://github.com/department-of-veterans-affairs/caseflow/issues/7718

**Comment by lowellrex** [comment] 2019-01-11 14:50
The hearing badge currently only shows up on the case search page. The remaining work to be done here is to make the badge show up on the various queue pages.

## Steps to reproduce:
* Log in as `BVALSPORER` in local test environment
* Search for Veteran ID `213912991`
* Observe the hearing badge appears
* Return to `/queue` and find the row for "Jadyn N Daugherty (213912991)" in one of the tabs
* Observe that there is no hearing badge

cc @joeyyang adding this to the work we have to do next sprint

**Comment by lowellrex** [comment] 2019-02-07 16:41
Re-opening this to resolve the bug [temporarily fixed by hiding the hearing badge](https://github.com/department-of-veterans-affairs/caseflow/pull/9271) from all pages.

**Comment by lowellrex** [comment] 2019-02-07 21:23
🐛 🔫 SMALL? The effort here is in finding the root cause. Reproducing it and making sure it doesn't happen again will likely be quicker than the investigation.

Examples of the error are [in Sentry](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/2991/). Perhaps this is a result of the appeal ID not being available at some point during the React lifecycle.

Nuts and bolts of the error is that we are returning a 404 after a GET request to `/appeals/undefined/hearings`.

**Closed** 2019-02-15 00:30 UTC
Labels: caseflow-queue, enhancement, foxtrot, queue-table-view
