### ISSUE TITLE
EPIC | Hearing Disposition Flows

### ISSUE THREAD

**Issue by MeredithStewart** [department-of-veterans-affairs/caseflow#8472] opened 2018-12-28 19:15 UTC
## User Stories: 

* As a hearing coordinator, I need to be able to postpone a Veteran immediately, send to "Schedule Veterans," for someone else to reschedule, or add an admin action that needs to be completed prior to scheduling Veterans. 

* As a Judge, I need to be able to postpone a Veteran and send it to "Schedule Veterans," or make a note about admin actions that are needed based on information they receive during the hearing. 

* As a hearing coordinator, I need to be able to know when to check to see if a Veteran has submitted a request for postponement after a no show hearing disposition. 

* As a hearing coordinator, I need appeals to continue forward if dispositions have been marked held or cancelled. 

## Epic Tickets 
* Held Flow 
* Canceled Flow
* No Show Flow 
* Postponement Flow - Hearing Schedule  
* Postponement Flow - Hearing Prep

**Comment by ShellySmithDSVA** [comment] 2019-01-13 22:31
I have an epic for this under ticket #8650. I'll merge the info on this ticket with the other.

**Comment by ShellySmithDSVA** [comment] 2019-01-23 20:14
Duplicate of #8650

**Closed by ShellySmithDSVA** 2019-01-23 20:14 UTC
Labels: caseflow-hearing-prep, caseflow-hearing-schedule, tango
