### ISSUE TITLE
Hearing Prep | Check with Justin on RO Tech Set-Up

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#4989] opened 2018-03-28 21:11 UTC
Check with Justin on RO Tech Set-Up   - who owns it, can we influence it? 
1. Some ROs only have one monitor
1. Quiet keyboards?

**Comment by lakohl** [comment] 2018-04-08 17:42
According to Justin this is still the purview of the Board

**Comment by annienguyenUSDS** [comment] 2018-07-18 17:32
Closing since we have https://github.com/department-of-veterans-affairs/appeals-design-research/issues/760 & confirmed keyboards in hearing rooms.

**Closed by annienguyenUSDS** 2018-07-18 17:32 UTC
Labels: caseflow-hearing-prep, icebox, tango
