### ISSUE TITLE
Work History | Completed tasks display twice in a row on Work History table

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1599] opened 2017-04-17 14:42 UTC
**Description**
A user reported that the Work History page displayed a duplicate claim after each completed task (see example below). This happened while working claims over the weekend, on 4/15.

**Example**
![image](https://cloud.githubusercontent.com/assets/4042181/25092029/ef8cee5c-2359-11e7-86b7-f32e1c98e159.png)**

**Comment by abbyraskin** [comment] 2017-04-17 14:43
@kierachell have you seen this one before?

**Comment by shanear** [comment] 2017-04-17 16:44
@abbyraskin I can't reproduce this.

Is the issue still happening? Do we know any more details about when/how it happened? Was it just once? Is it a persistent issue?

**Comment by abbyraskin** [comment] 2017-04-17 17:05
@shanear he noticed it when he ran out of claims this past Saturday, then returned to the Work History page. He said there are no claims in his queue to work so he can't check if it's still happening.

**Comment by kierachell** [comment] 2017-04-17 19:08
I have not seen that. Will investigate.

**Comment by shanear** [comment] 2017-04-19 15:41
@abbyraskin sending this your way, closing if we don't see the error again and can't reproduce.

**Comment by abbyraskin** [comment] 2017-04-19 15:45
I'll check with our users.

**Comment by abbyraskin** [comment] 2017-04-19 20:51
Closing this -- hasn't happened since last week, we can reexamine if it reemerges.

**Closed** 2017-04-19 20:52 UTC
Labels: bug-medium-priority, caseflow-dispatch, In Progress, tango
