### ISSUE TITLE
Form 8| Preview| Not Capturing Edited Changes

### ISSUE THREAD

**Issue by Sjones352** [department-of-veterans-affairs/caseflow#1529] opened 2017-04-11 13:33 UTC
**Add the following Severity Level Labels:** 
- [ ]    bug-high-priority - Data loss, data corruption or system unavailable  
- [x]    bug-medium-priority - Important functionality is unavailable but there is a workaround
- [ ]    bug-low-priority - Secondary functionality is unavailable and there is a workaround
- [ ]    bug-ui - Cosmetic issues or some functionality unavailable but has a simple workaround 

# Description
 User reports that "going back" to change something in the narrative I typed - hit preview again - my changes are not saved?  Tried multiple times, still preview does not display my changes. 

## Reproduction Steps

1. User enters information on form 8.
2. User clicks preview Completed Form 8.
3. User reviews Form 8.
4. User goes back and makes edits.
5. Edits 9B with new data.
6. Clicks preview Completed Form 8.
7. Form 8 does not show edited information.

**Validated in the following Envrionment(s)**
- [x] Dev
- [x] UAT
- [ ] Preprod
- [ ] Prod

**Scenario 1 -**

## Logs:

n/a

## Sentry:

n/a

### Screenshot1
Here is a “before” shot
<img width="805" alt="screen shot 2017-04-12 at 8 32 11 am" src="https://cloud.githubusercontent.com/assets/23080951/24957928/8f5d6f04-1f5b-11e7-979e-f39df9583b67.png">

### Screenshot2
I want to go back, and remove the text in the parentheses ()… like this:
<img width="623" alt="screen shot 2017-04-12 at 8 32 28 am" src="https://cloud.githubusercontent.com/assets/23080951/24957980/b45f9836-1f5b-11e7-8eba-c6d8f8bbd142.png">

### Screenshot3
Now, when I submitted the report – it would stay the original input text, but this time I got this, which is correct.

<img width="810" alt="screen shot 2017-04-12 at 8 33 18 am" src="https://cloud.githubusercontent.com/assets/23080951/24958032/e10cf0ea-1f5b-11e7-8f05-f921964716e2.png">

### Screenshot4
So… I tried to change the next bit. … and changed the original text to the following.
<img width="763" alt="screen shot 2017-04-12 at 8 37 11 am" src="https://cloud.githubusercontent.com/assets/23080951/24958067/09406632-1f5c-11e7-9b7b-15cf8b89f497.png">

### Screenshot5
But when I previewed, I got the OLD text:
<img width="818" alt="screen shot 2017-04-12 at 8 37 29 am" src="https://cloud.githubusercontent.com/assets/23080951/24958143/508195e8-1f5c-11e7-9738-013aae9c49f0.png">

### Screenshot6
So I guess – the BVA hearing portion does not reflect changes in PREVIEW.  ??
But, once Certified, the corrected text is presented.
 
<img width="821" alt="screen shot 2017-04-12 at 8 37 46 am" src="https://cloud.githubusercontent.com/assets/23080951/24958174/778c9bd8-1f5c-11e7-952b-3f19d33ffa14.png">

**_Scenario 1 - [TITLE]_**
Edit Scenario
# Related Issues
**_Support_**
https://github.com/department-of-veterans-affairs/appeals-support/issues/115

**_Engineering_**

**Comment by Sjones352** [comment] 2017-04-11 13:34
### User replied
Weirdest thing – previewing the Form 8 did not reflect the changes, but Certifying it DID.    The uploaded Form 8 did show the latest changes.
 
So I’m not sure it’s worth complaining??

**Comment by amprokop** [comment] 2017-04-24 15:43
We should pick up this issue even though we'll be hiding the Form 8, because we need to make sure changes in the UI are reflected in Form 8. First step is to try to reproduce. Does this issue happen only when we navigate back in the browser to the Form 8 preview page, maybe?

**Comment by amprokop** [comment] 2017-04-24 17:47
This will start as an investigation, but the dev may need to fix an issue if there is one.

**Comment by amprokop** [comment] 2017-09-07 14:30
Closing for now, we've fixed several bugs since then, I'm ready to call this resolved if it doesn't recur.

**Closed by amprokop** 2017-09-07 14:30 UTC
Labels: bug-medium-priority, caseflow-certification, foxtrot, Triage
