### ISSUE TITLE
Intake | RAMP EndProductNotFound error needs EP assignment

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#9946] opened 2019-03-13 22:37 UTC
e.g. https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3992/events/270606/

When a new RAMP refiling Intake is started, there is an initial check to see if all existing EPs are active. If the `EndProductEstablishment` for an existing RampElection row has a `nil` `reference_id` then it will raise a `EstablishedEndProductNotFound` error.

Before raising that error, we should try and check for an existing EP matching the date and code the veteran and assign it to the EPE. It may be that there are orphans on the Caseflow side and orphans on the VBMS side that merely need to be connected.

### Tech notes

* Could either rescue the exception in https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/ramp_review.rb#L85 or let EPE `.sync!` do the matching attempt itself. Probably better to do it in RampReview since it is RAMP specific.

**Comment by leikkisa** [comment] 2019-04-04 01:06
We have not fully diagnosed the problem, but here is my attempt at summarizing what we know so far.

There are 2463 established RAMP Elections that have a successful intake, but that are missing an End Product Establishment.

1668 Are not connected to an existing end product. The last one of these was intaken on.  We believe these are from before using end product establishments and were not backfilled.

795 are connected to an existing end product, and so should not have an end product establishment.  There was previously a bug in the code which could lead to these being connected to a canceled end product.  This bug was fixed in late February, allowing only active end products to be connected.  The instances of the missing end product establishments seem to have stopped at that time.

58 of them have multiple intakes, which seems to be caused by the RampElection being rolled back, and intaken again.

**Comment by leikkisa** [comment] 2019-04-10 18:52
#### Validation
This is going to be difficult to manually validate, because in UAT there are no RampElections missing an EndProductEstablishment, and the code doesn't allow new ones to be created like that.

So I suggest we validate it by looking for this error in Slack. Let's take a look at it after Wednesday, April 17th and see if there were any recent instances of this.

**Comment by Sjones352** [comment] 2019-04-23 23:25
Looked through the alert slack messages since April  17th and I see no errors so closing the issue.

**Closed by Sjones352** 2019-04-23 23:25 UTC
Labels: Data, In-Progress, Ready for Dev, caseflow-intake, sierra
