### ISSUE TITLE
Turn on virtual hearings toggle for users

### ISSUE THREAD

**Issue by chandracarney** [department-of-veterans-affairs/caseflow#13795] opened 2020-03-25 21:09 UTC
## Description
Turn on virtual hearings feature for users to pilot Caseflow (Gen2) virtual hearings scheduling. Write script to add all VLJs and POAs.

## Acceptance criteria
Virtual hearings scheduling available for:
- [x] 1 Hearing Coordinator 

Virtual hearings functionality available for:
- [ ] All VLJs
- [ ] All POAs

**Comment by ferristseng** [comment] 2020-03-30 19:14
Closing because the VLJs and POAs should have read access without the flag turned on. I confirmed that this morning: https://dsva.slack.com/archives/C3EAF3Q15/p1585582379087600

**Closed by ferristseng** 2020-03-30 19:14 UTC
Labels: Priority: High, Product: caseflow-hearings, Stakeholder: BVA, Team: Tango 💃
