### ISSUE TITLE
Failing RAMP test

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#7703] opened 2018-11-02 22:00 UTC
```
Edit issues Higher-Level Reviews when there is a rating end product shows request issues and allows adding/removing issues - spec.feature.intake.edit_spec
spec/feature/intake/edit_spec.rb
Failure/Error:
  expect(Fakes::VBMSService).to have_received(:create_contentions!).once.with(
    veteran_file_number: veteran.file_number,
    claim_id: rating_epe.reference_id,
    contention_descriptions: [
      RequestIssue::UNIDENTIFIED_ISSUE_MSG,
      "PTSD denied",
      "Left knee granted"
    ],
    special_issues: [],
    user: current_user

  #<Fakes::VBMSService (class)> received :create_contentions! with unexpected arguments
    expected: ({:veteran_file_number=>"12341234", :claim_id=>"FAKECLAIMID", :contention_descriptions=>["UNIDENTIFIED...e: "Lauren Roth", email: "test@example.com", roles: ["Mail Intake"], selected_regional_office: nil>})
         got: ({:veteran_file_number=>"12341234", :claim_id=>"FAKECLAIMID", :contention_descriptions=>["Active Duty ...e: "Lauren Roth", email: "test@example.com", roles: ["Mail Intake"], selected_regional_office: nil>}) (1 time)
              ({:veteran_file_number=>"12341234", :claim_id=>"FAKECLAIMID", :contention_descriptions=>["Left knee gr...e: "Lauren Roth", email: "test@example.com", roles: ["Mail Intake"], selected_regional_office: nil>}) (1 time)
./spec/feature/intake/edit_spec.rb:357:in `block (4 levels) in <top (required)>'
```

https://circleci.com/gh/department-of-veterans-affairs/caseflow/19584?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link

**Comment by pkarman** [comment] 2018-11-06 16:56
The exact behavior is that the rating and nonrating request issues are getting assigned to the wrong EndProductEstablishment records. I am investigating.

**Comment by pkarman** [comment] 2018-11-06 18:55
This was a regression caused by `profile_date` not being sent as part of `RatingIssue.ui_hash`.

**Closed** 2018-11-07 15:22 UTC
Labels: Flakey test, In-Progress, caseflow-intake, sierra
