### ISSUE TITLE
Loading Indicator | Server Error just kinda... hangs

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#3538] opened 2017-10-05 19:14 UTC
# Description
When there is a s serverload error, we just kinda... hang. 

## Reproduction Steps

**Scenario 1 -**

1. Go to Hearings
1. Get a 404 response on the backend
1. See loading indicator hang

**Validated in the following Environment(s)**
- [ ] Dev
- [X] UAT
- [ ] Preprod
- [ ] Prod

## Logs:
```
original(pin): null
▶response(pin)
▶req(pin): { method: "GET", url: "/hearings/…", headers: {…} }
xhr(pin): { }
text(pin): "{"errors":["Response not found"]}"
statusText(pin): "Not Found"
statusCode(pin): 404
status(pin): 404
statusType(pin): 4
info(pin): false
ok(pin): false
```

## Screenshots
**_Scenario 1 - [Loading]_**
<img width="729" alt="screen shot 2017-10-05 at 3 02 21 pm" src="https://user-images.githubusercontent.com/18075411/31247832-d41934e8-a9df-11e7-818a-d421ff4412dc.png">

**Comment by sharonwarner** [comment] 2017-10-10 19:46
Duplicate of #3548

**Closed by sharonwarner** 2017-10-10 19:46 UTC
Labels: bug-low-priority, caseflow-hearing-prep, tango
