### ISSUE TITLE
Case details: Display hearing information for unscheduled hearings

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#4843] opened 2018-03-13 17:14 UTC
In the Queue task details page, we currently fetch and display info for all scheduled hearings or held/cancelled hearings. We currently do not display any hearing preference information if a hearing was requested but not yet scheduled, since `appeal.hearings` will not return hearings that have not been scheduled.

In the happy path, this is fine for Queue Phase 2, since appeals should not be assigned to attorneys if any hearings have not been held. But if an appeal were to be mistakenly assigned to an attorney, we would display misleading information.

In the appeal serializer, we could use `appeal.hearing_pending?` and `appeal.sanitized_hearing_request_type` to return something like `{type: object.sanitized_hearing_request_type, scheduled: false}` if a hearing is requested but not yet scheduled.

# AC
- [ ] If a hearing is requested but not scheduled, display the hearing preference and `Hearing date: Pending scheduling`
- [ ] Notify Jim

**Comment by sharonwarner** [comment] 2018-12-18 18:30
@laurjpeterson This ticket is not fixed by the PR above. We still won't show unscheduled hearings. We're only updating the page to show hearings with null dispositions.

**Comment by laurjpeterson** [comment] 2019-05-30 22:55
Note: We now have Schedule Hearing tasks for both legacy and AMA appeals that can indicate whether a hearing is pending scheduling or not.

**Comment by laurjpeterson** [comment] 2019-09-04 19:27
@jimruggiero - this is actually part of case details, not search. so will remove it from the case search epic.

**Comment by hschallhorn** [comment] 2020-01-09 14:50
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | ||||||
3 | |||||||||
5 | 
8 | 
```
Ticket is well written. If all goes as described, should be fairly simple with some additions to the serializer and some front end refactoring. "2-10" lines of code on the back end - Kevin. May want to float changes by design when PR is ready to review. However, this ticket is pretty old, code may have shifted since them. Sometimes things just don't go as planned.

**Comment by drsjt1** [comment] 2021-02-22 18:55
Re-evaluate ?

**Closed** 2023-04-25 16:00 UTC
Labels: Product: caseflow-queue, Feature: case-details, Team: Echo 🐬, release-notes
