### ISSUE TITLE
Determine how to backfill decision issues that were created prior to ama_decision_issues feature flag

### ISSUE THREAD

**Issue by aroltsch** [department-of-veterans-affairs/caseflow#8971] opened 2019-01-26 13:53 UTC
AC:
Determine how to backfill decision issues that were created prior to ama_decision_issues feature flag

**Comment by laurjpeterson** [comment] 2019-01-28 23:47
@aroltsch I emailed you a sample spreadsheet. I wonder if we'll need more information from attorneys on which attorney magic decision issues are connected to which request issues. While investigating if a script would work, can you also investigate if there's any way for us to do this in the UI?

**Comment by laurjpeterson** [comment] 2019-01-30 19:51
Notes:
- what do we do about diagnostic codes?
- building a UI would be more work than parsing the excel spreadsheet
- @shanear - can you check my understanding here?
   - AMO creates an EP (for grants and remands)
   - Claims assistant (or some other VBA user) receives end product in VBMS
   - Claims assistant (or some other VBA user) looks at appeal decision and enters issue data into VBMS (VBMS-R, I believe)
   - Therefore, the decision issue text already lives in a field in VBMS
- @shanear - if i'm correct, could you help @aroltsch get the data/access she needs to look at that field in VBMS? we think we should make sure to match the way the issue is listed in VBMS when we backfill this in Caseflow

**Comment by laurjpeterson** [comment] 2019-02-01 00:06
List of things I think we need to backfill or be aware of (note that this gh issue may just be for decision_issues):
- decision_issues in Caseflow DB
- which request_issues each decision_issue maps to in Caseflow DB
- VBMS field (Issue description?) that Caseflow would use as the next request_issue if the Veteran requested a review on the BVA decision (is it called issue description? i think the field is in VBMS-R)

**Comment by aroltsch** [comment] 2019-02-05 13:09
@shanear could you please assist on where to find this data in VBMS?

**Comment by laurjpeterson** [comment] 2019-02-07 18:22
*Notes from convo yesterday:*
- all post-RAMP appeals dispatched (note: we have them dispatched through 01/23/2019 now)
- find Veteran, find EP code
  - make sure all Veterans have it - if they don't, find out why
- find the rating that is connected to that EP
- find the issue description in that rating
- use that issue description as the `decision_issue`
- link request and decision issues
  - if 1:1, connect request to decision issues


AMA EPs - note: these might be being established through SHARE not VBMS

EP    Claim Label
030BGR    Board Grant Rating
030BGNR    Board Grant Non-Rating
040BDE    Board DTA Error
040BDEIMO    Board DTA Error with IMO
030BGRPMC    PMC Board Grant Rating
030BGNRPMC    PMC Board Grant Non-Rating
040BDEIMOPMC    PMC Board DTA Error - w/IMO
040BDEPMC    PMC Board DTA Error

**Comment by aroltsch** [comment] 2019-02-21 13:33
For each appeal none of the EPs are processed:
- create decision issues based on spreadsheet
- set vbms_uploaded_at on decision_document
- decision_document.process!
- cancel old RAMP EP (Shane will ask AMO if that's ok)

**Comment by shanear** [comment] 2019-02-23 16:44
Alright, the spreadsheet has been backfilled 🎆

Some of the RAMP EPs had already been processed so I wasn't able to perfectly backfill them. Most weren't, which is nice. I have the results of the backfill saved, and can send that encrypted to whoever needs it.

Did a little bit of validation:

Find any appeals with a decision doc that have request issues that have not been closed or have no decision issues:
```
appeals = Appeal.all.select do |appeal|
  !appeal.decision_documents.empty? && appeal.request_issues.any? do |request_issue|
    !request_issue.closed_status && request_issue.decision_issues.empty?
  end
end
```

```
appeals.count
=> 18
```

So there is still more backfilling to be done.


```
appeals.map(&:decision_documents).map(&:first).map(&:decision_date)

=> => [Wed, 13 Feb 2019, Thu, 07 Feb 2019, Thu, 07 Feb 2019, Tue, 12 Feb 2019, Tue, 29 Jan 2019, Mon, 04 Feb 2019, Fri, 08 Feb 2019, Fri, 08 Feb 2019, Fri, 01 Feb 2019, Tue, 29 Jan 2019, Fri, 08 Feb 2019, Tue, 29 Jan 2019, Tue, 29 Jan 2019, Fri, 08 Feb 2019, Mon, 07 Jan 2019, Fri, 01 Feb 2019, Tue, 29 Jan 2019, Fri, 01 Feb 2019]
```

Decision dates corroborate what Nicholas was saying earlier. That there were still some decisions between end of Jan and mid Feb that still need to be backfilled. Waiting on those.

**Comment by aroltsch** [comment] 2019-02-25 13:55
Wow, thanks Shane!!!

**Comment by shanear** [comment] 2019-03-06 22:47
There are now only 2 appeals without decision issues, both of which are a duplicates that the board is dealing with. Closing this one.

**Closed by shanear** 2019-03-06 22:47 UTC
Labels: In-Progress, caseflow-decisions, foxtrot, sierra

**Comment by laurjpeterson** [comment] 2019-03-18 20:23
Noting that when backfilling decision issues, we took the approach to append the Request issue disposition to the front of the Request issue. 

So, decision issues for the RAMP appeal pilot period (Oct - ~Feb) will look something like this:
![image](https://user-images.githubusercontent.com/27704093/54561055-22413200-499a-11e9-9552-59ab3fb56a7d.png)
