### ISSUE TITLE
Funny business with 10A, 10B and 10C

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#342] opened 2015-12-08 14:24 UTC
![screenshot from 2015-12-08 09 23 05](https://cloud.githubusercontent.com/assets/132447/11657833/5ad5e85c-9d8d-11e5-8cee-54a49ae541ab.png)

![image](https://cloud.githubusercontent.com/assets/132447/11657849/6a69356c-9d8d-11e5-97b6-153e42e32894.png)

**Comment by paultag** [comment] 2015-12-08 14:31
(Seems like `No` always gets checked, and yes is the only responsive one)

**Comment by plusjeff** [comment] 2015-12-08 21:13
@KHarshawat  @paultag To clarify, is the issue is that 10C should not have a value if 10B is 'No' or 'N/A'?

**Comment by alex** [comment] 2015-12-08 21:13
I think the bug is that both things are checked in 10A?

**Comment by KHarshawat** [comment] 2015-12-08 21:15
Right now `no` in 10a is always selected on the actual form 8  even if you select yes in the questions page.

@paultag  identified the bug

**Comment by paultag** [comment] 2015-12-08 21:17
@joesoftware yeah, check 10A output in the PDF when marking "yes" on 10A

**Comment by webinista** [comment] 2015-12-08 21:21
The problem is between this line in `locals`:  `selected: @kase.hearing_requested?` and how the template actually works to build `id` and `name` strings.

**Comment by plusjeff** [comment] 2015-12-08 21:27
Actually, it looks like the problem is on https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/controllers/web_controller.rb#L86

The issue is that for a user like Joe Snuffy that has a default value of 10A as No. But then, the value is changed to Yes and the default value still exists.

Good find, because this issue will impact all fields that have a default value. The code in the controller was just fine since we weren't asking questions that we could derive from VACOLS data, but now that the user has the ability to modify the answers, we need to just take user input and not use any data from the initial_fields.

**Comment by paultag** [comment] 2015-12-08 21:30
Awesome.

Also, let's be sure that the disabled forms are actually ignored from the user (Like, by opening up the form and editing the HTML before POST'ing), in case it is somehow modified

**Comment by plusjeff** [comment] 2015-12-08 21:31
:+1: -- coding it up now

**Comment by paultag** [comment] 2015-12-08 21:31
Lordy I love this team

**Comment by plusjeff** [comment] 2015-12-08 21:33
For my own notes, disabled fields are:

- 2. File No
- 15. Name and Location of Certifying Office
- 16. Organization Element Certifying Appeal

**Comment by plusjeff** [comment] 2015-12-08 21:47
There's also a bug that this makes super noticeable, because default values are no longer pulled. Some of the radio fields don't populate for non-10 fields. Investigating this here too.

**Comment by plusjeff** [comment] 2015-12-08 21:49
Fields that need to be checked and/or fixed (all radio fields):

- [ ] 8B
- [ ] 8C
- [ ] 9A
- [ ] 10A
- [ ] 10B
- [ ] 11A
- [ ] 11B
- [ ] 12B
- [ ] 13

**Closed** 2015-12-08 23:28 UTC
Labels: backend, bug, in progress
