### ISSUE TITLE
Caseworker | Reset Test Data Failure/Time Out

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#825] opened 2017-02-06 14:45 UTC
**Description**

When Dispatch is accessed by a caseworker in UAT, there are no claims to establish. When the caseworker clicks the link to reset the claims, the page goes blank. This seems to be caused by duplicate test data in VACOLS.

Link to error log: https://dsva.slack.com/files/kierachell/F40PS2V88/duplicatevacolsdata.txt

**Expected**
1.There are no duplicates of test data in VACOLS
2. A caseworker should be able to reset data and then be able to establish a claim

**Environment Found:** UAT
**Browsers Found:** IE, Chrome, FF, Safari

**Screenshots:** 
<img width="1383" alt="screen shot 2017-02-06 at 9 48 59 am" src="https://cloud.githubusercontent.com/assets/23038505/22651589/917e8990-ec51-11e6-981b-4684e50c2ed8.png">
<img width="1379" alt="screen shot 2017-02-06 at 9 49 09 am" src="https://cloud.githubusercontent.com/assets/23038505/22651588/917ba414-ec51-11e6-9f56-cee34309b942.png">

**Associated Issues/Stories**

**Reported by:** Alexis Stewart

**Comment by kierachell** [comment] 2017-02-17 03:53
duplicate of https://github.com/department-of-veterans-affairs/caseflow/issues/888

**Closed by kierachell** 2017-02-17 03:53 UTC
Labels: bug, caseflow-dispatch, Current Sprint
