### ISSUE TITLE
Automatic Case Distribution failures

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#11713] opened 2019-08-09 13:44 UTC
We noticed that some Distributions get stuck in the `pending` state because an error occurred along the way. The state should be changed to `error`, but for some reason, it is not. If a Distribution is `pending`, then it blocks judges from trying again because we have a validation that won't allow a Distribution to be created if there is already an existing one for that same judge in the `pending` state. While tracing the error for some of those `pending` Distributions, I noticed that for 2 of them, the error was the same:
How I searched the logs:
```
awslogs get dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out ALL --start='8/7/2019 11:17:30' --end='8/7/2019 11:18:00' | grep "StartDistributionJob"
```
Error:
```
StartDistributionJob failed: PG::NotNullViolation: ERROR:  null value in column "appeal_id" violates not-null constraint
```
It looks like this happened when trying to create a JudgeAssignTask without an `appeal_id`:
https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/docket.rb#L72

I haven't yet figured out how that happened.

In addition, I looked up how many Distributions we have in `error` state, and there were 340. I looked up the last one and this was the error:
```
StartDistributionJob failed: PG::UniqueViolation: ERROR:  duplicate key value violates unique constraint "index_distributed_cases_on_case_id"
```

Slack thread:
https://dsva.slack.com/archives/CHX8FMP28/p1565121226268200

**Comment by pkarman** [comment] 2019-08-13 17:10
All the pending Distribution records were deleted when this ticket was opened.

**Comment by pkarman** [comment] 2019-08-13 21:51
`duplicate key value violates unique constraint "index_distributed_cases_on_case_id"` is happening frequently and is probably at the root of many failures.

**Comment by pkarman** [comment] 2019-08-15 16:23
Now we are seeing errors in Sentry: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6114/events/433162/

**Comment by pkarman** [comment] 2019-08-15 20:15
The problem is consistently with the SQL in https://github.com/department-of-veterans-affairs/caseflow/blame/master/app/models/vacols/case_docket.rb#L238 where VACOLS cases are being distributed more than once.

My suspicion is that some data has changed in VACOLS that is triggering whatever logic Caseflow uses to identify them. This may be a business flow bug, or a problem in the SQL, and it will require more investigation.

**Comment by pkarman** [comment] 2019-08-19 17:33
Comments from @amprokop 

> My first guess would be that someone or something is sending an appeal back to case storage after it's been distributed. Case distribution looks for appeals in location 81 and 83 (which are both case storage if memory serves, something is different about the two locations but i can't remember what).
https://github.com/department-of-veterans-affairs/caseflow/blob/1405be2e9fde453737ffcb286e3a19f516e1a162/app/models/vacols/case_docket.rb#L70    
> The first thing I would check is the PRIORLOC table for previous locations of the affected appeals. The PRIORLOC table should tell you who changed the location back to case storage and when. My guess is the right course of action is to tell whoever did that that they shouldn't, and have them reassign appeals in VACOLS back to the correct judge who should be working the case.
> The constraint on case id was put in place for safety, since we believed appeals should not be distributed by the algorithm twice. Another  possibility — there is some remand loop that we didn't account for. For example, I am not sure what happens with CAVC appeals that are then remanded to BVA — would BVA staff then assign them back to case storage in VACOLS? That also might cause this error.
> But the PRIORLOC table should tell you the story hopefully.

**Comment by pkarman** [comment] 2019-08-19 17:36
Confirmed that the problematic cases are assigned to location 81 or 83 in VACOLS and should not be. We are working around each one manually depending on its specifics. In the case where we need to distribute it, we are following https://github.com/department-of-veterans-affairs/caseflow/wiki/Bat-Team#if-an-automatic-case-distribution-job-fails-to-run-and-errors-with-activerecordrecordnotunique-how-do-i-fix-it

**Comment by pkarman** [comment] 2019-08-20 19:56
We continue to see errors where the Distribution job is stuck in "pending" for hours/days. The `StartDistribution` job is either not created or not executed for some reason.

As a workaround, we could add/modify a scheduled job to check for pending Distribution jobs older than 1 hour and create StartDistribution jobs for them.

**Comment by pkarman** [comment] 2019-09-11 12:43
Based on conversation with @laurjpeterson we have identified at least one instance where it is legitimate for a case to be re-distributed. An example of its task tree:

```
LegacyAppeal 655275
├── RootTask on_hold, 2019-03-15 18:15:38 UTC
│   ├── HearingTask cancelled, 2019-03-28 16:36:53 UTC
│   │   ├── ScheduleHearingTask completed, 2019-03-28 16:36:52 UTC
│   │   └── AssignHearingDispositionTask cancelled, 2019-04-23 14:28:56 UTC
│   └── TrackVeteranTask in_progress, 2019-04-23 15:00:18 UTC
└── ScheduleHearingColocatedTask completed, 2019-03-15 19:12:59 UTC
    └── ScheduleHearingColocatedTask completed, 2019-03-15 19:12:59 UTC
```

* more than a RootTask
* all tasks either cancelled or completed (closed) except for active `TrackVeteranTask`
* tasks include completed `ScheduleHearingColocatedTask` and cancelled `HearingTask`

In these cases we follow the procedure in https://github.com/department-of-veterans-affairs/caseflow/issues/11713#issuecomment-522679100 and update the value of `case_id` in the existing DistributedCase record.

**Comment by laurjpeterson** [comment] 2019-09-17 22:02
Yep, this is a legitimate scenario where a case is distributed a second time. It's not uncommon to see processing errors with legacy hearing cases - somehow, the request for a legacy hearing was missed, the attorney or judge identified this when reviewing the Veteran's file, they add an administrative action saying the hearing was missed, and the appeal goes backwards in the process for hearing scheduling.

**Comment by kevmo** [comment] 2019-10-17 14:02
```
1 | 
2 |
3 | ||||||
5 | ||||||
8 | |||
```

 ### AC
1. Understand problem that is occurring. Write a tech spec, then write a ticket. 
2. Simultaneously have at least 1 team member building subject matter expertise in Automatic Case Distribution. This is important!

Estimating at a 5.  We are thinking of this as being time-boxed.  If it's going to take more than a 3's worth of effort, bring it up to the rest of the team. ❤️ communication! ❤️ 

History:
- Written by USDS people. @amprokop reviewed & is resource.  ACD has not evolved much since it's implementation in early 2019.  Anya, Lowell, and Peter also possess knowledge of this.

**Comment by pkarman** [comment] 2019-10-29 18:39
Note there is an outstanding PR on this to work around the problem. See #12190 -- it just needs to be extended to fit the business cases where re-distribution is legit.

**Comment by lomky** [comment] 2019-10-31 19:31
Reference and update the ACD wiki https://github.com/department-of-veterans-affairs/caseflow/wiki/Automatic-Case-Distribution

**Comment by pkarman** [comment] 2019-11-06 15:51
See https://dsva.slack.com/archives/C3EAF3Q15/p1572991590133500 for one background on why cases might change location to VACOLS and then come back again.

**Comment by yoomlam** [comment] 2019-11-13 23:22
PR #12190 is an attempt to address this ticket.  Add other case scenarios to the `RedistributedCase.ok_to_redistribute?` method in order to have such appeals automatically redistributed.

**Closed** 2023-04-25 15:55 UTC
Labels: Type: Bug, Feature: auto-case-distribution, Source: Bat Team, Team: Echo 🐬, Priority: High
