### ISSUE TITLE
Document list | Docs newest to oldest by default

### ISSUE THREAD

**Issue by gnakm** [department-of-veterans-affairs/caseflow#2000] opened 2017-05-15 19:02 UTC
Currently, the Receipt Date is displayed oldest to newest. Instead, we should display this list newest-oldest by default.

## AC
- The Receipt Dates are displayed newest (most recent date) to oldest by default

**Comment by abbyraskin** [comment] 2017-05-17 14:54
Closing, duplicate of #2018 :)

**Closed by abbyraskin** 2017-05-17 14:54 UTC
Labels: bug-medium-priority, caseflow-reader, Ready for Dev, whiskey
