### ISSUE TITLE
Form 8 | Pre-populated Fields | Missing data and unable to manually enter

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#865] opened 2017-02-09 17:13 UTC
# Description
User is having any issues with form 8. The pre-populated slots are not being populated, nor can she enter some fields manually. User can not enter the file number, question#2, nor can she enter into questions 15 and 16. However, she can enter information into question #3. See the screenshot below
User URL is: https://certification.cf.ds.va.gov/certifications/new/3030564

**Environment:**
- [x] Production
- [ ] UAT
- [ ] Demo
- [ ] Development

**Type of Bug:**
- [ ] Performance
- [ ] Design
- [ ] Security
- [x] Functional

**Severity Level:** 
- [ ]    5 - Data loss, data corruption or system unavailable  
- [x]    4 - Important functionality is unavailable with no workaround 
- [ ]    3 - Important functionality is unavailable but has a reasonable workaround 
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround 
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround 
 
# Reproduction Steps
**_Scenario 1 - Missing pre-populated data_**
1. In VACOLS, enter Vet ID #.
1. Click on the **_Certify_** button in VACOLS to launch Caseflow Certification.  
1. `Electronic Form 8 ` page will be displayed with pre-populated values.
**Results**:  Values missing for question 2.   

**_Scenario 2 - Unable to enter values in questions 2, 15, 16_**
1. Continuing from Scenario 1.
1. Enter required values for questions 2 - 16.  
**Results**:  User is unable to enter values in question 2, 15, & 16.

## Screenshots
**_Scenario 1 - Missing pre-populated data_**
![form 8](https://cloud.githubusercontent.com/assets/23316043/22790510/6dca907e-eeb4-11e6-839a-40a9ab30db1c.PNG)

# Related Issues
Form 8: Pre-populated fields: no data: unable to manually enter [#52](https://github.com/department-of-veterans-affairs/appeals-support/issues/52)

**Comment by nikitarockz** [comment] 2017-02-09 18:03
@orischwartz I assigned this one to you because the word on the street is that you have a quick fix. As this is a production issue, please pick it up at your earliest convenience.

**Comment by shanear** [comment] 2017-02-09 18:40
@nikitarockz this is a duplicate of #610, which i re-opened in response to this incident

**Comment by shanear** [comment] 2017-02-09 18:40
going to go ahead and close this one.

**Closed by shanear** 2017-02-09 18:40 UTC
Labels: bug, caseflow-certification, foxtrot, Ready for Dev
