### ISSUE TITLE
Reader: When table is sorted, assistive technology should report that it is sorted

### ISSUE THREAD

**Issue by alisan16** [department-of-veterans-affairs/caseflow#12243] opened 2019-09-27 21:14 UTC
When sort functions are applied such as Receipt Date and document Type the sort that is applied is not read by assistive technology programs. These sorts should read as content updated for assistive technology users. (New: 08/27/2019) see above same area the column header should read something link “document type select button to sort” then once sorted it should read something like “document type sorted ascending”

<img width="1163" alt="Screen Shot 2019-09-27 at 5 14 23 PM" src="https://user-images.githubusercontent.com/1198106/65802639-44d2b580-e14a-11e9-8790-494d093505d7.png">

**Comment by araposo-tistatech** [comment] 2020-05-26 14:53
duplicate of #12136

**Closed** 2020-05-26 14:53 UTC
Labels: Product: caseflow-reader, Team: Foxtrot 🦊, Type: Accessibility
