### ISSUE TITLE
Decision Review | Decision Type: Distinguish New and Material allowances

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1421] opened 2017-04-03 14:14 UTC
**Context**

Sometimes BVA grants a claim to reopen an issue due to new and material evidence -- in this scenario, Caseflow recognizes the new and material allowance as a grant, even if there's no monetary grant associated and thus no EP to create.

For example, if a claimant is has 1 issue remanded and 1 issue granted for new and material evidence, Caseflow thinks this is a partial grant, even though it should be established as a remand. Currently users have no way to change the Decision Type in Caseflow.

**Story**
-  Detect new and material allowances in VACOLS and disregard them when determining whether a decision is a full grant, partial grant, or remand.

 - Specifically, we should disregard the disposition of any issue where:

```sql
ISSPROG = '02' and ISSCODE = '15' and ISSLEV1 = '04'
```

## Acceptance Criteria
- Validate that if an appeal contains any issues where ISSPROG = '02' and ISSCODE = '15' and ISSLEV1 = '04' in VACOLS, Caseflow disregards the disposition of these issues when determining whether it is a full grant, remand, or partial grant.

**Comment by abbyraskin** [comment] 2017-04-03 14:15
@cmgiven can you elaborate on how to detect new and material issues?

**Comment by cmgiven** [comment] 2017-04-04 14:02
The vast majority of these are to establish service connection for a compensation claim. As such, we should disregard the disposition of any issue where:

```sql
ISSPROG = '02' and ISSCODE = '15' and ISSLEV1 = '04'
```

There are a handful of cases where "new and material" is only established in comments on the issue. For example, if the issue is new and material evidence relating to the character of discharge or the cause of death on a DIC claim. The above will catch 98% of the new and material issues, however, and an even larger share if we disregard DIC issues, as I believe we are still not CESTing them.

**Comment by abbyraskin** [comment] 2017-04-05 14:25
Thanks @cmgiven. Updating AC.

**Comment by abbyraskin** [comment] 2017-04-05 14:31
One more question for the sake of prioritization...Do you know how often this occurs @cmgiven? Nicholas estimated 5-10%.

**Comment by cmgiven** [comment] 2017-04-05 14:51
Nicholas FTW! 5.7% of FG/PG/remand cases. 13.8% if I look only at what would otherwise be marked as full grants or partial grants.

```r
cases <- query("
  select BFKEY,

  count(case when ISSDC = '1' then 1 end) as ALLOWED,

  count(case when ISSDC = '3' then 1 end) as REMANDED,

  count(case when
  ISSPROG = '02' and ISSCODE = '15' and ISSLEV1 = '04'
  then 1 end) as NM,

  count(case when
  ISSPROG = '02' and ISSCODE = '15' and ISSLEV1 = '04' and ISSDC = '1'
  then 1 end) as ALLOWED_NM,

  count(case when
  ISSPROG = '02' and ISSCODE = '15' and ISSLEV1 = '04' and ISSDC = '3'
  then 1 end) as REMANDED_NM

  from BRIEFF
  left join ISSUES on BRIEFF.BFKEY = ISSUES.ISSKEY

  where BFDDEC >= date '2015-10-01' and BFDDEC < date '2016-10-01'
    and BFDC in ('1', '3')

  group by BFKEY
") %>%
  mutate(
    is_allowed = ALLOWED > 0,
    but_not_grant = is_allowed & ALLOWED - ALLOWED_NM <= 0
  )

sum(cases$but_not_grant) / nrow(cases)
sum(cases$but_not_grant) / sum(cases$is_allowed)
```

**Comment by nicholasholtz** [comment] 2017-04-10 14:38
@joofsh

**Potential Dispositions: New and Material**

The "new and material" arises when a claim has been previously denied (by the RO or Board) and become final by result of either not being appealed or being appealed and denied. If a new and material claim is granted, then the issue itself will be considered on the merits. Generally, a "new and material grant" is not relevant to ARC; the only way it becomes relevant is if the resulting merits issue is granted or remanded. [Can get into much more detail if you'd like....]

| N&M Dispo | Merits Dispo | Appeal Handled by Dispatch?* |
|---|---|---|
| Denied | N/A | N/A |
| Grant | Denied | Not handled |
| Grant | Remanded | Treat merits issue _only_ as a Remand; ignore N&M |
| Grant | Grant | Treat merits issue _only_ as a Full Grant; ignore N&M |

*Suggested handling is assuming no other issues on the appeal, and thus subject to change. For example, if the N&M was granted, and the merits remanded, suggesting a "Remand" and ignoring any other potential issues that could make this a "Partial Remand".

**Comment by joofsh** [comment] 2017-04-20 17:42
This one might be hard to validate. Let me know if you need help @kierachell

**Comment by kierachell** [comment] 2017-04-20 18:42
**PASSED**
I changed some some issues and codes around was able to make a Partial Grant into a Remand and back
<img width="958" alt="screen shot 2017-04-20 at 2 27 48 pm" src="https://cloud.githubusercontent.com/assets/18075411/25246991/7dfff556-25d7-11e7-88bc-02f808fe56d9.png">
<img width="943" alt="screen shot 2017-04-20 at 2 29 49 pm" src="https://cloud.githubusercontent.com/assets/18075411/25246992/7e0b810a-25d7-11e7-83ad-ea8cd8d72b98.png">
<img width="633" alt="screen shot 2017-04-20 at 2 29 53 pm" src="https://cloud.githubusercontent.com/assets/18075411/25246994/7e130038-25d7-11e7-88de-7bbc1a464aac.png">
<img width="1061" alt="screen shot 2017-04-20 at 2 40 49 pm" src="https://cloud.githubusercontent.com/assets/18075411/25246995/7e1e6446-25d7-11e7-827a-d3582b1048b3.png">
<img width="943" alt="screen shot 2017-04-20 at 2 40 52 pm" src="https://cloud.githubusercontent.com/assets/18075411/25246996/7e296bde-25d7-11e7-86c5-fc049e8af2fa.png">
<img width="936" alt="screen shot 2017-04-20 at 2 41 15 pm" src="https://cloud.githubusercontent.com/assets/18075411/25246997/7e2c9b92-25d7-11e7-93f4-c305f3de28b1.png">

**Closed by kierachell** 2017-04-20 18:42 UTC
Labels: caseflow-dispatch, In Validation, tango
