### ISSUE TITLE
BVA | Intake claims listed with a G code disposition in VACOLS

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#14476] opened 2020-06-05 18:48 UTC
## User or job story
As a BVA Intake user, I need to be able to intake claims listed with a G code disposition in VACOLS

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by RebeccaBaumTT** [comment] 2020-06-09 21:13
This is a duplicate of #13893. I am closing it as such.

**Closed by RebeccaBaumTT** 2020-06-09 21:13 UTC
Labels: Eng: Backend Work Group, Priority: Medium, Stakeholder: BVA, Team: Foxtrot 🦊, Type: Enhancement, User: VBA Intake
