### ISSUE TITLE
Average FreeableMemory LessThanThreshold | eFolder-Prod-Freeable-Memory

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#3921] opened 2017-11-14 20:54 UTC
**Impacted Service** | Appeals CloudWatch

**AlarmName** | dsva-appeals-efolder-prod-freeable-memory

**AlarmDescription** | RDS: 25% of the value for the instance as the threshold

**Reason** | Threshold Crossed: 1 datapoint [1.8744950784E9 (14/11/17 20:31:00)] was less than the threshold (1.875E9). 

Screenshots: 
![pagerdutyalert](https://user-images.githubusercontent.com/23038505/32804062-b57c7714-c953-11e7-9d6b-bed103ec8454.png)
<img width="628" alt="screen shot 2017-11-14 at 3 50 51 pm" src="https://user-images.githubusercontent.com/23038505/32804075-bf6df6a8-c953-11e7-94ea-92b8be9d7858.png">

**Comment by kierachell** [comment] 2017-11-14 22:48
### 13:45 spike:

#### Network ops
<img width="508" alt="screen shot 2017-11-14 at 5 45 57 pm" src="https://user-images.githubusercontent.com/18075411/32809200-fc5fcab8-c963-11e7-87e3-9da2b6527896.png">

##### Freeable memory
<img width="1234" alt="screen shot 2017-11-14 at 5 46 23 pm" src="https://user-images.githubusercontent.com/18075411/32809201-fc713802-c963-11e7-8874-6668edeb7dea.png">

**Comment by kierachell** [comment] 2017-11-15 00:44
### Slow/heavy DB queries: `seq scan` = bad

#### https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/services/download_documents.rb#L42
```
explain (analyze, buffers) select * from documents order by document_id limit 10;
                                                               QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=909160.20..909160.22 rows=10 width=1130) (actual time=54159.897..54159.925 rows=10 loops=1)
   Buffers: shared hit=195794 read=311071
   ->  Sort  (cost=909160.20..940977.64 rows=12726978 width=1130) (actual time=54159.894..54159.903 rows=10 loops=1)
         Sort Key: document_id
         Sort Method: top-N heapsort  Memory: 29kB
         Buffers: shared hit=195794 read=311071
         ->  Seq Scan on documents  (cost=0.00..634134.78 rows=12726978 width=1130) (actual time=0.010..33153.051 rows=12550840 loops=1)
               Buffers: shared hit=195794 read=311071
 Planning time: 0.135 ms
 Execution time: 54159.982 ms
(10 rows)
```

#### https://github.com/department-of-veterans-affairs/caseflow-efolder/blob/master/app/controllers/api/v1/files_controller.rb#L36

```
explain (analyze, buffers) select * from downloads order by user_id, id limit 10;
                                                         QUERY PLAN
-----------------------------------------------------------------------------------------------------------------------------
 Limit  (cost=3233.44..3233.46 rows=10 width=140) (actual time=161.857..161.885 rows=10 loops=1)
   Buffers: shared hit=1242
   ->  Sort  (cost=3233.44..3390.94 rows=63001 width=140) (actual time=161.854..161.863 rows=10 loops=1)
         Sort Key: user_id, id
         Sort Method: top-N heapsort  Memory: 26kB
         Buffers: shared hit=1242
         ->  Seq Scan on downloads  (cost=0.00..1872.01 rows=63001 width=140) (actual time=0.008..78.616 rows=63003 loops=1)
               Buffers: shared hit=1242
 Planning time: 0.101 ms
 Execution time: 161.927 ms
(10 rows)
```

**Comment by kierachell** [comment] 2017-11-15 01:47
### Why does SaveFilesToS3 trigger like a 1000 commits:
<img width="224" alt="screen shot 2017-11-14 at 8 45 01 pm" src="https://user-images.githubusercontent.com/18075411/32814408-0270e446-c97d-11e7-9e69-30457b9f7ed6.png">

Can this be batched?

**Comment by aroltsch** [comment] 2017-11-15 19:19
Looking at New relic the slowest query is Document find:
![image](https://user-images.githubusercontent.com/3811786/32855368-6f4dc93e-ca0f-11e7-9c4b-5d98d1b9c24c.png)

Query: 

```
SELECT  "documents".* FROM "documents" WHERE "documents"."download_id" = $? AND "documents"."document_id" = $?  ORDER BY "documents"."received_at" DESC, "documents"."id" ASC LIMIT ? 
```


Digging into it more, the query is called from the files controller which is called by the reader job. 
Stack Trace:
![image](https://user-images.githubusercontent.com/3811786/32855421-91a50b5a-ca0f-11e7-8187-650e2a6a423c.png)


Checking the DB indexes on the `documents` table, it doesn't have an index for [download_id, document_id] combination. 


Solutions:
1. Add index to the documents table on [download_id, document_id]
2.

**Comment by sunil-sadasivan** [comment] 2017-11-15 19:37
Good find @aroltsch! 1.27s for a db query is way too long.  If this looks to be a common path which it looks to be, 👍  from me on adding a compound db index there.

**Comment by mdbenjam** [comment] 2017-11-15 20:39
Great investigation! New Relic is proving super useful already!!!

**Comment by mdbenjam** [comment] 2017-11-15 20:40
Also fixing this will shave over a second off this endpoint. That's incredible!

**Comment by nickheiner-usds** [comment] 2017-11-15 20:50
❤️ for New Relic usage.

Also, documenting our New Relic usage really helps me point to examples when I need to justify spending money on it.

**Comment by aroltsch** [comment] 2017-11-15 20:59
Yeah, New Relic is awesome!!!

**Comment by askldjd** [comment] 2017-11-18 18:05
So the index has been added, it is unclear if there are any effects to the DB resource utilization.

The connection count reduced to Wednesday's level, but it is still abnormally high when we used to hover between 30-40 connection two weeks ago. 

There is no evidence of memory reduction either.

![image](https://user-images.githubusercontent.com/3258724/32983280-25affa42-cc60-11e7-9782-81b79ed74645.png)

![image](https://user-images.githubusercontent.com/3258724/32983293-5d2aeed2-cc60-11e7-908c-6ba7c7b7dae9.png)


While I see the slow query reported in NR, there are other reports that shows Document.find is _typically_ very fast (<1ms). So if it is unclear to me if the slow query is just an occasional outlier.

![image](https://user-images.githubusercontent.com/3258724/32983336-f8e227b4-cc60-11e7-8ac7-b6ab74457259.png)

**Comment by sunil-sadasivan** [comment] 2017-11-18 22:01
Thanks @askldjd for the update here. 

I think there are a few things happening here, and I'm not entirely sure if the background job is the culprit.  The timing of the background job and the reader roll out is almost similar in timing.  Seeing these peaks throughout M-F leads me to believe this is also caused by the load from real-time reader usage instead of from the background job. 

The background job hits efolder at a regular rate of at most 3 users / 5 mins and doesn't scale up or down during business hours.  However, the increased connections and memory usage seem to follow a pattern of increased usage from business hours. 

Taking a look at throughput for the efolder Documents API.  It does look like we're hitting increased load during business hours.   This looks to hit close to **700 requests per minute**  to the `api/documents#show` route. 

<img width="953" alt="screenshot 2017-11-18 16 41 54" src="https://user-images.githubusercontent.com/31223104/32985057-a437b2fa-cc7f-11e7-82c9-8c25a463d775.png">
https://rpm.newrelic.com/accounts/1788458/applications/81190810/transactions#sort_by=throughput&id=5b22436f6e74726f6c6c65722f6170692f76312f646f63756d656e74732f73686f77222c22225d

This load patterns to the `api/documents#show` route is leading me to suspect that these are the patterns due to reader client downloads as we talked about yesterday.  ie. If we limit document downloads from the client side, this should relieve db connection pressure.  My conclusion is to focus on reducing the amount of efolder express API calls the client makes. 

Curious if this makes sense @askldjd @kierachell?    

> Can the job be optimized to spread out load more evenly? If not, can the job be scheduled to run in non-business hours?

- The BG job is only meant to reduce our calls and spread the load of our VBMS dependency, this does not help reduce efolderX load from the client.  This already runs at a consistent, spread out rate right now.  I am quite skeptical of the bg job being the culprit, though I'm eager/happy to turn it off as a test during business hours.  Let me know if you think this needs to be done @askldjd.  

(Again, my intuition is the increased load from client side is causing eX load issues as shown in the new relic image above)

**Comment by kierachell** [comment] 2017-11-18 22:26
- I agree, I think the job just pushed us over the edge because of the following issue:
https://github.com/department-of-veterans-affairs/caseflow/issues/3412

- Just browsing 2 cases each with 20 small PDFs:
![requests](https://user-images.githubusercontent.com/18075411/32985288-7f67d4c2-cc85-11e7-86c2-c44ddaec5d72.gif)


I was able to generate 300+ requests and 50+MB of data. Maybe 30% from disk cache. Assuming most cases have 100+ documents... this will be problematic when scaled to 700 users.

**Comment by sunil-sadasivan** [comment] 2017-11-18 22:44
@kierachell just to be clear with the culprit, this looks like it's the reader client fetches from efolderX causing excessive load, not necessarily the bg job is that correct.  

I'm just trying to be explicit and understanding of the exact cause here.   (the bg job != reader client :) )

**Comment by kierachell** [comment] 2017-11-18 23:07
Correct, it is not the culprit, and it definitely not helping eFolder (only VBMS maybe; still have to investigate those 50k hourly hits).

**Comment by sunil-sadasivan** [comment] 2017-11-18 23:11
Agreed, I'm digging into the 60k VBMS spikes as well.  (My hope is that was due to the onboarding of new reader users over the past two weeks and that we won't see them again)

I'm adding S3 counters to efolderX at the moment.

**Comment by sunil-sadasivan** [comment] 2017-11-19 00:09
Just a follow up to my comment [above](https://github.com/department-of-veterans-affairs/caseflow/issues/3921#issuecomment-345474643)  

The background job does _not_ call the `api/v1/document#show` route.  This is only hit from the reader client from separate browsers.  The bg job does call the files API:

<img width="1470" alt="screenshot 2017-11-18 19 08 24" src="https://user-images.githubusercontent.com/31223104/32985920-e80a500a-cc93-11e7-8eb2-32830b971fbe.png">
This looks to be at peak around 40 requests/min.

**Comment by askldjd** [comment] 2017-11-19 17:04
@sunil-sadasivan 

I am not sure if background job is the culprit. Like @kierachell said, we probably have several performance issues here and each adds to the load.

> Taking a look at throughput for the efolder Documents API. It does look like we're hitting increased load during business hours. This looks to hit close to 700 requests per minute to the api/documents#show route.

I was trying to confirm the 700 req per minute, but I can't get to the data anymore in NR. So I used Prometheus to track the same data.

This is the eX `api/documents#show` call per minute during Nov 16 business hours.
![image](https://user-images.githubusercontent.com/3258724/32992904-9d2e79cc-cd1e-11e7-8c4c-5a07bb42f7a7.png)

According to Prometheus, we hit **9400 request per minute** at peak , which translates to about 156 request per second. This essentially answered my question on why we have 200 DB connections open. It looks like we really are serving 200 request concurrently in eX.

I am not sure how to get this data to agree with NR.

The next obvious question is why are we downloading so much? I thought we cache the PDFs in the browsers. This behavior is as if our users are streaming PDFs continuously during business hours

**Comment by askldjd** [comment] 2017-11-19 17:24
I also want to state the end goal once again so we don't lose sight. DB memory/connection, EC2 loads, CSR loads are all symptoms of the real problem - VPN bandwidth.

The hard cap for the VPN tunnel is 500 Mbps, and I would like to stay below 250 Mbps for safety. The limit applies to both current setup, and the future setup under Direct Connect. Whatever we do, we need to focus on reducing the bandwidth number.

**Comment by sunil-sadasivan** [comment] 2017-11-20 01:07
Thanks @askldjd, with @mdbenjam out this week... I think it'd be good to get someone on the whiskey team to understand why we're triggering so many document downloads from the client.  If we can limit this, this will likely help resolve the symptoms caused by a high number of doc downloads. 

I'm going to look into the client side logic tomorrow and see what I can find.  

I'd like to tag @dannysellers or @tejans24 who both have knowledge of the reader client side to see if either of them have some thoughts.

**Comment by kierachell** [comment] 2017-11-20 13:49
#### New index:

- Just checked it again since it was built and I say it was a good optimization:
```
SELECT
    relid::regclass AS table,
    indexrelid::regclass AS index,
    pg_size_pretty(pg_relation_size(indexrelid::regclass)) AS index_size,
    idx_tup_read,
    idx_tup_fetch,
    idx_scan
FROM
    pg_stat_user_indexes
    JOIN pg_index USING (indexrelid)
WHERE
    idx_scan > 100
    AND indisunique IS FALSE ORDER BY idx_scan DESC;
```

- Gives me:

```
   table   |                     index                      | index_size | idx_tup_read | idx_tup_fetch | idx_scan
-----------+------------------------------------------------+------------+--------------+---------------+----------
 documents | index_documents_on_download_id_and_document_id | 938 MB     |     24295292 |      22401666 |  1509980
 users     | index_users_on_css_id_and_station_id           | 56 kB      |        96857 |         96857 |    96859
 downloads | downloads_completed_at                         | 5472 kB    |     47307261 |      46252431 |    87004
 downloads | downloads_manifest_fetched_at                  | 5192 kB    |    127625758 |     125464955 |    49614
 searches  | searches_created_at                            | 1768 kB    |      7558853 |       2645796 |    44157
 searches  | searches_status_created_at                     | 4040 kB    |      7520239 |       2607182 |    17884
```

From a 2 day weekend. So that's good that it is faster now.


### This does not solve the database DDOSing problem we have tho

**Comment by nickheiner-usds** [comment] 2017-11-20 15:39
> Also that's pretty insane how we have 300+ requests for just 2 cases of 20 PDF docs. Looks like we're trying to DOS ourselves.

Hmm, yes, that is odd and worth looking in to further.

What are S3 counters?

> I was trying to confirm the 700 req per minute, but I can't get to the data anymore in NR (I don't know why).

Our trial is running out.

> I also want to state the end goal once again so we don't lose sight. DB memory/connection, EC2 loads, CSR loads are all symptoms of the real problem - VPN bandwidth.

:+1: 💯. We definitely need to keep the real problem in sight. And if we can solve any problem by just scaling up, we should do it. It'll be much more cost effective to use more server resources instead of burning team time.

**Comment by nickheiner-usds** [comment] 2017-11-20 16:16
> What are S3 counters?

Ah, looks like this just refers to Prometheus metrics.

**Comment by sunil-sadasivan** [comment] 2017-11-20 16:56
Yeah apologies for not being more explicit there.  Over time, we should be hitting s3 more over vbms.  We can infer a cache miss/hit rate for the docs API by measuring s3 vs VBMS requests.

**Comment by askldjd** [comment] 2017-11-20 17:55
> And if we can solve any problem by just scaling up, we should do it. It'll be much more cost effective to use more server resources instead of burning team time.

I don't fully agree with this. Reasonable engineering principle and best practices still applies. I am much more cautious of solutions that requires vertical scaling (e.g. RDS) than horizontal scaling because you can only play this card so many times.

In short term, scaling up might make sense. In long term, it may not. A classic example is VACOLS. The inefficiencies of VACOLS UI is the root cause of why VACOLS DB can not migrate to the cloud today. VACOLS DB is also vertically scaled up to the limit such that its size impacts VM migration and recovery. 

Software inefficiencies should be treated as a technical debt. Optimization should be performed routinely to minimize impact to the long term sustainability of the project.

**Comment by sunil-sadasivan** [comment] 2017-11-20 18:07
I'd agree with @askldjd on this, especially knowing that we have hit a limit of vertical scaling with our CSR.  This boundary led us to understand that we're seeing excessive client requests which is likely a suboptimal user experience and something we should optimize.  

There is certainly a trade-off of developer velocity and taking debt vs taking a step back to figure out the root cause.  I think it's better to look at each occurrence of needing to make this trade-off with different assumptions of what is the reasonable course of action.

**Comment by kierachell** [comment] 2017-11-21 02:33
> And if we can solve any problem by just scaling up, we should do it. It'll be much more cost effective to use more server resources instead of burning team time.

does burning future teams' time count? or is the idea to provide employment for the future appeals modernization teams?

**Comment by nickheiner-usds** [comment] 2017-11-22 17:02
> > And if we can solve any problem by just scaling up, we should do it. It'll be much more cost effective to use more server resources instead of burning team time.
>
> I don't fully agree with this. Reasonable engineering principle and best practices still applies.

Agreed. We don't want to write disastrously bad code. I guess I'd just like us to keep scaling up as an option, instead of treating our current instance size as a constraint.

**Comment by aroltsch** [comment] 2017-11-30 13:54
Hey @NickHeiner @sunil-sadasivan are there any more action items from this post mortem? 
We've already done two things:
1. https://github.com/department-of-veterans-affairs/caseflow/pull/3951
2. https://github.com/department-of-veterans-affairs/caseflow-efolder/pull/707

**Comment by sunil-sadasivan** [comment] 2017-11-30 14:02
@aroltsch I believe we can close this one now.  We can follow up if there are future incidents.

**Closed** 2017-11-30 14:13 UTC
Labels: In-Progress, post-mortem, prod-alert, whiskey
