### ISSUE TITLE
Handle invalid address characters when establishing claim

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#9688] opened 2019-02-27 23:48 UTC
Japanese address had an invalid character, so the claim failed to establish. Note that I believe we need the addresses to match in the systems for the claim establishment to succeed.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/3276/events/260130/

**Comment by pkarman** [comment] 2019-03-22 00:58
dupe of #7911

**Closed by pkarman** 2019-03-22 00:58 UTC
Labels: Triage, caseflow-intake, sierra
