### ISSUE TITLE
Caseworker: Priority order of assigned cases

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#359] opened 2016-10-24 17:05 UTC
As a Caseworker, I want the case assigned to me to be in priority order.

### Acceptance Criteria
1. Verify when I click "Establish Next Claim" button, the task assigned to me should be the highest priority task according to the following rules:
  - All full grants (oldest to newest) first.
  - then all remands/partial grants (oldest to newest).

### Implementation Notes:
- Flip order tasks are created in background job
- Refactor task sorting logic to be oldest first

### Sub-tasks

- [ ] QA discovery and scripting

**Comment by KHarshawat** [comment] 2016-11-07 02:11
@lakohl is this a dupe of a story we created last sprint? If so could you please mark as such and close?

**Comment by KHarshawat** [comment] 2016-11-07 02:11
@lakohl can you please add appropriate mocks here?

**Comment by KHarshawat** [comment] 2016-11-07 20:31
Closing as a dupe of https://github.com/department-of-veterans-affairs/caseflow-certification/issues/386

**Comment by lakohl** [comment] 2016-11-08 13:56
@KHarshawat mocks have been made for this already - we just needed to answer the research question. My understanding is that Bill does all full grants and the partial grants get divided up among the other employees (and Bill if he is done with the full grants.) @abbyraskin can you confirm?

**Comment by abbyraskin** [comment] 2016-11-08 14:54
Yes - that is how it works today according to coaches. I am confirming with Bill today as well.

**Comment by shanear** [comment] 2016-11-18 16:39
Moving this to triage since it's not yet ready for development.

**Comment by abbyraskin** [comment] 2016-11-18 19:16
The priority today is to process all full grants (oldest to newest), then all remands/partial grants (oldest to newest).

**Comment by sharonwarner** [comment] 2016-11-29 15:36
On hold til the order of tasks is confirmed.

**Comment by shanear** [comment] 2016-12-01 18:32
@sharonwarner for issues that are blocked like this just add the `blocked` label and keep them in progress

**Comment by lakohl** [comment] 2016-12-02 18:20
I think we should go with what Abby says the priority is today: Full Grants first then Partial Grants /Remands. In each instance the oldest case would always be processed first. 

*I can foresee one caveat: today, some employees only have the ability to process Partial Grants/Remands. If this persists, using the rule above, can we decide the kind of case they are assigned based on the employees' login credentials?

**Comment by abbyraskin** [comment] 2016-12-02 19:23
The coaches would like all employees to process any type of decision moving forward. Carolyn didn't feel comfortable distributing all full grants to a single user, even though this has been the practice historically. (If this isn't rolled out in practice, some sort of decision-type limitation based on login credentials could prove useful, but I think we're good to move forward without it for now.)

**Comment by KHarshawat** [comment] 2016-12-03 04:00
Yay! This makes things much easier :)

**Comment by nikitarockz** [comment] 2016-12-06 16:04
I updated the user story to correctly reflect the final decision on priority order.

**Comment by astewarttistatech** [comment] 2016-12-08 15:15
@lakohl are there still no mocks to go off of or are we just not using them for this issue?

**Comment by astewarttistatech** [comment] 2016-12-08 15:19
@lakohl Can this be tested in Dev? It doesn't seem I cannot make anything thats not a Full Grant.

**Comment by lakohl** [comment] 2016-12-08 16:48
@astewarttistatech for Milestones 1 & 2 Caseflow Dispatch is only going to handle Full Grants

**Comment by astewarttistatech** [comment] 2016-12-08 19:02
This issue is being moved to blocked due to the fact it currently cannot be tested. Please refer to Lara's comment above. 

@shanear next steps?

**Comment by sharonwarner** [comment] 2016-12-12 15:40
VA data can't be mocked in our test database.

**Comment by kierachell** [comment] 2016-12-30 15:04
Where/how can we see the priority anyway?
<img width="868" alt="screen shot 2016-12-30 at 10 03 08" src="https://cloud.githubusercontent.com/assets/18075411/21567074/4c0f43c4-ce77-11e6-87c6-4d9389235a6e.png">
The only ordering I see is by vacols_id.

Can we get deidentified data and preload that?

**Comment by lakohl** [comment] 2016-12-30 17:28
@kierachell I'm not sure that I am understanding your question. But, I'll take a stab... 

Right now to gather the cases they need to work, AMC caseworkers run a number of reports in VACOLS. One is for cases in 'history/archive status' within a specified date range. These are always Full Grants as full grants are assigned to 'history' once they have a BVA decision. Other kinds of grants e.g. Partial Grants and Remands, will have a different location (I believe it's 98 for ones dispatched to AMC) and are gathered by running a different report.

Right now the priority at AMC is to work Full Grants first and then Remands. That would mean putting full grants at the top of our queue and feeding those to caseworkers first. Perhaps we could build out this VACOLS query and then add the one for Partial Grants/Remands later.

**Comment by shanear** [comment] 2017-01-12 20:12
Works! validated on UAT

**Closed** 2017-01-12 20:12 UTC
Labels: blocked, caseflow-dispatch
