### ISSUE TITLE
File Number not found for Claim ID

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#11787] opened 2019-08-15 18:19 UTC
### Story
During Intake, after the Veteran search has successfully found a Veteran record, all the existing EPs for the Veteran are synced before proceeding to the next Intake step. During the EP sync, VBMS gets an error from BGS that results in VBMSError::FileNumberNotFoundForClaimId exception.

This seems to happen if the EP is cancelled, and there were never contentions created on it.

### Context
Slack thread: See https://dsva.slack.com/archives/CHX8FMP28/p1565887240386800
Sentry alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6642/events/485188/

## External requests
ESCP Service Request: SR-002150 (status closed, moved to VBMS)
https://escp.aac.va.gov/ServiceRequest/Details/13607

YourIT Incidents

review type | review id | claim id | YourIT INC | Link | Status
--- | --- | --- | --- | --- 
RampElection | 145909 | 67421457 | INC7690720 | https://yourit.va.gov/va?id=ticket&table=incident&sys_id=84e54998dbdcc0d4ceac76740f961978
SupplementalClaim | 158156 | 74793215 | INC7974656 | https://yourit.va.gov/va?id=ticket&table=incident&sys_id=08f84847dba044d0eab2f3421f9619dd
HLR | 78149 | Cancelled
SC | 386606 | 78137915 | INC10874112 | https://yourit.va.gov/va?id=ticket&table=incident&sys_id=4dd6e927dbb09890f37af50d0f961950 | Resolved

**Comment by leikkisa** [comment] 2019-09-14 17:30
Adding info from a duplicate ticket
https://dsva.slack.com/archives/CCB97HZJL/p1565188103098600 VBMS cannot find record by claim number 67421457 when attempting to sync end product establishment.

**Comment by leikkisa** [comment] 2019-09-14 17:33
Update from meeting on Tuesday:
There's also SR 1101900 for this

During the meeting, we found that VBMS has additional validation checking the veteran's participant ID during list contentions that they believe should not be there, so they are planning on removing it.

I am moving this to the backlog instead of ready for dev, pending updates on that change, in case we don't need to code an alert for this.

**Comment by pkarman** [comment] 2019-09-27 13:00
I got notice that SR-002150 was closed as resolved.

As of this morning we are still receiving the error though:
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/6642/events/485188/

**Comment by jcq** [comment] 2019-10-17 19:49
participant id | review type | review id
--- | --- | --- 
10237330 | SupplementalClaim | 158156

**Comment by leikkisa** [comment] 2020-01-27 23:46
Per this conversation with Martina, one of these EPs has been canceled and therefore is no longer causing the error. We looked into the other EP, which got cleared a long time ago. It was a Ramp Election, and the syncing process at this point was used to create the ramp issues.  The RE does already have Ramp Issues created.

I decided to update the RampElection EndProductEstablishment's synced_status to "CLR", with the last_action_date as the synced_at date.  This will prevent it from trying to sync anymore and will stop the error.

The root cause of this issue has not yet been fixed, but this closes out the active cases of this. We can move it towards a more longer term request.

https://dsva.slack.com/archives/C54QCEHAL/p1580160341088200

**Comment by leikkisa** [comment] 2020-05-21 18:05
Re-opening this ticket, as we have a new occurrence of this error.

**Comment by leikkisa** [comment] 2020-06-11 00:08
INC10874112 looks like it's resolved now, we're able to successfully fetch contentions for the veteran's end products.

A note from the last BGS meeting - the theory was that the file number was missing somewhere in the veteran's data.  @wdrougas-tista and I looked at the veteran's data today (fetching the veteran info and person info using the participant ID), and the file number was always populated. Someone may have fixed the data before we looked because fetching the contentions is now working as well.

**Closed** 2023-04-25 15:55 UTC
Labels: Team: Foxtrot 🦊, Product: caseflow-intake, Type: Bug, Integration: VBMS, Source: Bat Team, Priority: Medium, Source: Upstream-error
