### ISSUE TITLE
Reader issue: Scroll bar scroller hidden by header & footer

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#1647] opened 2017-04-20 16:10 UTC
Putting in issue at @mdbenjam's request.

The document header and footer is covering the scroll bar in Reader, resulting in a situation where the scroller gets hidden.

It is less obvious on docs with fewer pages, but still present. Single page:
![single page scroll bar](https://cloud.githubusercontent.com/assets/16781398/25240711/9074e59a-25c1-11e7-81de-0f8fc77cb032.PNG)

For documents with more pages (here, header and footer for a doc with 129 pages), the scroller completely disappears:

Header:
![header](https://cloud.githubusercontent.com/assets/16781398/25240912/313c5d00-25c2-11e7-9e6d-432566f81313.PNG)

Footer:
![footer](https://cloud.githubusercontent.com/assets/16781398/25240928/3d494cca-25c2-11e7-8c34-7c187bf712fd.png)

@abbyraskin @gnakm @NickHeiner @tejans24

**Comment by mdbenjam** [comment] 2017-04-27 20:26
This is a duplicate of #1650. Closing and fixing in #1763

**Closed by mdbenjam** 2017-04-27 20:26 UTC
Labels: bug, caseflow-reader, whiskey
