### ISSUE TITLE
Explore "Page not found" issue

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/caseflow#577] opened 2016-02-01 17:17 UTC
This happened during usability testing...

One participant clicked certify to launch Caseflow, then clicked “PIV Card” to log in to the VA, typed her VACOLS credentials into Caseflow, and then received “page not found” in IE9 (she refreshed and
then the page loaded fine).

![image](https://cloud.githubusercontent.com/assets/12674895/12724622/ba22f7d0-c8dc-11e5-952e-9adb13c9346d.png)

![image](https://cloud.githubusercontent.com/assets/12674895/12724640/c96477be-c8dc-11e5-8ae0-b0d3e9409194.png)

![image](https://cloud.githubusercontent.com/assets/12674895/12724650/d7c205ba-c8dc-11e5-88a6-496df975afe8.png)

![image](https://cloud.githubusercontent.com/assets/12674895/12724801/913b58b6-c8dd-11e5-95a0-15dd07329845.png)

**Comment by paultag** [comment] 2016-02-01 20:29
This is a dupe of #560 - but this has a better bug report; closing 560

**Comment by paultag** [comment] 2016-02-05 16:09
@maryannbrody do you have the date and time this happened?

**Comment by KHarshawat** [comment] 2016-02-27 14:13
@paultag is this good to close? If so, plz do

**Closed** 2016-02-29 14:57 UTC
Labels: backend, bug, Rollout Phase 1, user-research
