### ISSUE TITLE
Bring back hidden form fields

### ISSUE THREAD

**Issue by paultag** [department-of-veterans-affairs/caseflow#332] opened 2015-12-07 16:33 UTC

**Comment by paultag** [comment] 2015-12-07 16:33
Not targeting rollout with this one yet, I'll leave targeting this to @KHarshawat

**Comment by KHarshawat** [comment] 2015-12-07 23:57
Let's scope this for the limited rollout milestone but with the caveat that we need significant testing to make sure this works as intended. Don't want to end up with it being buggy when we roll out more broadly.

**Comment by webinista** [comment] 2015-12-09 19:54
So what does this look like. Are we showing / hiding? Disabling irrelevant fields? I think the latter might be less confusing for the user. Plus it eliminates the need to complete #223.

**Comment by webinista** [comment] 2015-12-10 21:17
See #263 for mockups of related fields
![413fa3a4-9aa6-11e5-9c91-ce0c58e2c6b6](https://cloud.githubusercontent.com/assets/354277/11728727/6c52d216-9f59-11e5-8881-d95be8138101.png)

**Comment by webinista** [comment] 2015-12-10 22:33
@KHarshawat Can you verify that this is how show/hiding fields should work now with these additional fields?

- [ ] If 10A == yes, show and require 10B, otherwise hide 10B and remove `required` attribute and class name.
- [ ] If 11A == yes, require 11B.
- [ ] If 11A == no,  hide 11B, and remove `required` attribute, class name
- [ ] If 5A, 6A, or 7A contain data, show 5B, 6B, or 7B.

**Comment by webinista** [comment] 2015-12-14 23:08
Assigning to @KHarshawat who is still working through the logic for this.

**Comment by webinista** [comment] 2015-12-16 21:33
Related to #401, #399

**Comment by KHarshawat** [comment] 2015-12-18 23:57
Ok, untangling a couple issues here and articulating for clarity.  cc/ @webinista 

The first is whether we show/hide or disable questions. I'm torn b/c show/hide moves the page around a bit but disabling a question can be confusing. After some thought, I think show/hide with a sliding animation is the right option. Show/hide also helps remove the jankiness for an "N/A" option.

The second issue is which questions do we show/hide and when? This took a lot of thinking. I had to re-write some of the questions to make a proper decision tree which will mean a little more work (specifically on 8A- 9B). I've outlined how it should work below and included a mock for what 8A-9B should look like. in the code quotes you'll see how the show/hide logic should be applied and when questions are required. 


**5A**/**6A**/**7A** (If these have content show 5B/6B/7B respectively)
**5B**/**6B**/**7B** (required if shown)

------

**8A** Specify appellant representative: `(required)`
- Power of attorney `(show 8B)`
- Agent `(show 8C)`
- Service organization `(show 9A)`
- No representative

**8B** Veteran has chosen a power of attorney, the authority recognizing such is: `(required if shown)`
- Located in the veteran’s appeal file
- Located in another VA file `(show "Specify other VA file" text field)`
	- "Specify other VA" file text field

**8C** Representative is an agent, is he/she on the accredited list? `(required if shown)`
- Yes
- No

**9A** Representative is a service organization, is VA Form 646 or equivalant of record? `(required if shown)`
- Yes
- No `(show 9B)`

**9B** VA form 646 is not of record, explain.
- Text field

*For 8A-9B see the mock below*
![image](https://cloud.githubusercontent.com/assets/6335546/11909721/a399f8fc-a59f-11e5-9790-a61fd624e362.png)

------

**10A** Was a hearing requested? `(required)`
- Yes `(Show 10B, 10C)`
- No

**10B** If the hearing was held, is transcript on file? `(optional)`
- Yes
- No 

**10C** If the hearing was requested but not held, explain `(optional)`
- Text Field

**11A** Are contested claims procedures applciable in this case? `(required)`
- Yes `(Show 11B)`
- No

**11B** Have the requirements of 38 U.S.C. 7105A been followed for all contested claims? 
- Yes
- No

**13** Records to be forwarded to Board of Veterans' Appeals
- CF OR XCF
- INACTIVE CF
- ...
- Other `(Show specify other text field)`
	- Specify other text field

----------

Finally, there's the question of whether we should go back to only showing questions we don't already have answers for. I'm going to suggested we punt on this for now. We did this because we assumed that our data was always going to be accurate and because it provided a simpler user experience. What we found in usability studies was that, more often than not, our data was wrong and the user had no way of fixing it. So for now let's stay conservative and show all the questions (barring any logic described above), pre-filling the fields as necessary but still allowing the user to edit them. *Eventually* we will re-add the feature to only show questions we need answers for but likely with a separate `Suggested Questions` view like the mock below. These would be all the questions we don't already think we have the data for from the database.

![image](https://cloud.githubusercontent.com/assets/6335546/11908728/ab5cd1a6-a593-11e5-9767-e2e8da77a55f.png)

**Comment by webinista** [comment] 2015-12-21 17:03
Blocked by #281, since we're adding another radio-button type.

@alex @paultag I assume this also requires changes to the controller that handles this form.

**Comment by webinista** [comment] 2015-12-28 18:35
@KHarshawat two questions for you re. Question 13.

1. Should the _Specify Other_ field for 13 be required if it's shown?
1. Should the _Specify Other_ field be cleared if the user _unchecks_ question 13?

**Closed** 2016-01-08 21:16 UTC
Labels: frontend, in progress
