### ISSUE TITLE
Timing bug: Certifications that encounter a VBMS error after starting will show up as blank for 48 hours

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow#464] opened 2016-11-18 17:23 UTC
![image](https://cloud.githubusercontent.com/assets/16327036/20402160/9dcf61c8-acc9-11e6-8f75-ddeac2f31197.png)

This is a Certification that started but encountered an error before ever being populated. It displays as blank for [48 hours](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/certification.rb#L12).

### Example sequence

A request to `/certifications/new/XXXX` is made, triggering:

```ruby
Certification.find_or_create_by_vacols_id(XXXX).start!
```
1. Certification record is created
1. start! inserts the form8 record, , setting the `updated_at` attribute to now
1. initiate VBMS request `VBMS::Requests::ListDocuments`
1. Timeout/error on above request
1. Never reach the form8 `update_attributes` command.

The form8 record is never actually filled with data but its updated_at attribute shows it was last populated now. So when the user refreshes this case, they'll continue seeing blanks for 48 hours.

### Possible solutions 
Transactionalize the form8 update. If appeal fetch fails, form8 update should also fail.

Change initially introduced in #393

### Sub-Tasks

- [ ] Add automated test to simulate.

**Comment by amprokop** [comment] 2016-11-18 17:55
thanks @orischwartz

**Comment by amprokop** [comment] 2016-11-28 16:04
Investigating this now. Here's the code from `certification.rb`:

```
  def start!
    # if we haven't yet started the form8
    # or if we last updated it earlier than 48 hours ago,
    # refresh it with new data.
    if form8_started_at.nil? || form8.updated_at < 48.hours.ago
      form8.update_from_appeal(appeal)
    end

    update_attributes!(
      already_certified:   calculate_already_certified,
      vacols_data_missing: calculate_vacols_data_missing,
      nod_matching_at:     calculate_nod_matching_at,
      form9_matching_at:   calculate_form9_matching_at,
      soc_matching_at:     calculate_soc_matching_at,
      ssocs_required:      calculate_ssocs_required,
      ssocs_matching_at:   calculcate_ssocs_matching_at,
      form8_started_at:    (certification_status == :started) ? now : nil
    )

    certification_status
  end
```

Note that we populate the form with appeal data `if form8_started_at.nil? || form8.updated_at < 48.hours.ago`. If `form8.update_from_appeal` raises an exception, then if we reload, `form8.updated_at` will be present since we've already created the form8 row, but `form8_started_at` on the certification model won't be set, since we didn't reach the `update_attributes!` block due to the raised exception. Right?

I attempted to reproduce this locally by raising an error in `lib/fakes/appeal_repository.rb`:

```
  def self.fetch_documents_for(appeal)
    raise "error"
    return unless appeal.documents.blank?
    appeal.documents = @documents || []
  end
```

as expected, the app crashes on `/certifications/new/123C`:
![image](https://cloud.githubusercontent.com/assets/3781835/20675284/c13c4da4-b559-11e6-950b-5be58affe6b4.png)
but when i remove the error and reload, all is well and the data is populated. 

*however*, if i also remove the nil check for `form8_started_at` and change the conditional to 
```
    if form8.updated_at < 48.hours.ago
      form8.update_from_appeal(appeal)
    end
```

then i can reproduce this bug. the app crashes on `/certifications/new/123C`, and on reload, the form8 is blank.
![image](https://cloud.githubusercontent.com/assets/3781835/20675481/6c40f326-b55a-11e6-9823-4b31208e180a.png)

**Comment by amprokop** [comment] 2016-11-28 16:31
After discussing with @shanear, we found that the `certification.start!` logged by Sentry in these errors was an old one:
![image](https://cloud.githubusercontent.com/assets/3781835/20676470/cd55c274-b55d-11e6-8ab2-5f46d082daca.png)
The release that this bug was present in had commit hash `cfd779f`, with the latest changes checked in on oct 28th. On November 14th, I merged changes to master that should fix this particular error. I wouldn't be shocked if other timeout errors pop up, but I think we can mark this as fixed for now.

**Closed by amprokop** 2016-11-28 16:31 UTC
Labels: bug, caseflow-certification, in progress
