### ISSUE TITLE
Expanding eFolder Express access for private attorneys

### ISSUE THREAD

**Issue by nicholasholtz** [department-of-veterans-affairs/caseflow#9838] opened 2019-03-07 18:35 UTC
Creating a specific issue addressing the question of eX access exclusively, for ease in OIT tracking. This fits in with https://github.com/department-of-veterans-affairs/caseflow/issues/7774 and https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/624#issuecomment-333321781.

**Comment by nicholasholtz** [comment] 2019-03-07 19:58
From the Board:

> Provide accredited private attorney access to Caseflow and E-folder express.
> - Limitations on access restricted to a single POA (accredited attorney) within a law firm.

**Comment by laurjpeterson** [comment] 2019-05-30 04:54
Closing this one because we've confirmed that private attorneys can get access to eFolder Express through the CSEM process.

**Closed by laurjpeterson** 2019-05-30 04:54 UTC
Labels: BVA, Post-AMA Requirement
