### ISSUE TITLE
Remove the PDF preview page if ENV[]

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#847] opened 2017-02-07 21:36 UTC
## Remove this page entirely ##
![image](https://cloud.githubusercontent.com/assets/3781835/22710702/62b29628-ed4c-11e6-804c-424e14a80f8e.png)

**Comment by shanear** [comment] 2017-02-07 22:42
this is a duplicate of #848

**Comment by shanear** [comment] 2017-02-09 15:07
yeah this is a dup

**Closed by shanear** 2017-02-09 15:07 UTC
