### ISSUE TITLE
Investigate source of "File Number does not exist within the system" error

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5544] opened 2018-05-15 13:17 UTC
We saw `File Number does not exist within the system.` when hitting `/appeals/3033525/document_count`. 

(Sentry appears to be naively grouping this one with other `VBMS::HTTPError`s, it only happened once as I'm creating this ticket)

Potentially the file number is just incorrect in VACOLS.

https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/1359/events/65619/

# AC
- Determine if the file number in this error is correct, and diagnose why VBMS might be returning this error

**Comment by evankroske** [comment] 2018-05-15 17:36
See also https://github.com/department-of-veterans-affairs/dsva-vbms/issues/102

**Comment by evankroske** [comment] 2018-09-05 19:49
Just logged in as the user and visited the address, and I was unable to reproduce this issue. I think it's been fixed on the VBMS side.

**Closed by evankroske** 2018-09-05 19:49 UTC
