### ISSUE TITLE
Document count numbers are not the same in Queue and Reader. 

### ISSUE THREAD

**Issue by kevmo** [department-of-veterans-affairs/caseflow#13261] opened 2020-01-27 15:06 UTC
## Description
At least one user has reported that document counts have large discrepancies  between the Case details page in Queue, and the document count in Reader.  

## Background/context/resources

VLJ user is reporting that there is a  document count discrepancy between the Case details page in Queue, and the document count in Reader. Case URL: https://appeals.cf.ds.va.gov/queue/appeals/4007370.

Initially reported [here](https://dsva.slack.com/archives/CHX8FMP28/p1580136098066200).

![Queue](https://user-images.githubusercontent.com/1034221/73185865-d8ae9100-40ec-11ea-82e9-008666a988d8.jpg)
![Reader](https://user-images.githubusercontent.com/1034221/73185938-f976e680-40ec-11ea-896c-55d4a0360bc5.jpg)

## Technical notes
Issue confirmed to exist by Bat team. 

This veteran appellant has multiple cases. When navigating to cases, they all show the same 382 documents.

All documents for a veteran should be in a single efolder in vbms, not split by cases.

**Comment by yoomlam** [comment] 2020-01-27 15:14
The "View 716 docs" appears on https://appeals.cf.ds.va.gov/queue/appeals/4007370, so labeling this ticket as 'echo'. Either Queue or Reader needs to update the document count.

**Comment by yoomlam** [comment] 2020-01-27 16:21
Tips from Peter: https://dsva.slack.com/archives/CHX8FMP28/p1580140720071300?thread_ts=1580136098.066200&cid=CHX8FMP28

**Comment by yoomlam** [comment] 2020-01-29 19:34
Another related support issue: https://dsva.slack.com/archives/CHX8FMP28/p1580326239095400

**Comment by yoomlam** [comment] 2020-01-29 22:31
To get the document counts, the two web pages are querying eFolder differently, but it's unclear why eFolder is returning different counts for the same appeal and user. We can make the counts the same by querying eFolder in the same manner, but we want to make sure we're getting all the documents from eFolder. 

**Pages in question:**
Page 1 = "Case Details" = https://appeals.cf.ds.va.gov/queue/appeals/4007370
Page 2 = Queue>Reader "Claims Folder" = https://appeals.cf.ds.va.gov/reader/appeal/4007370/documents (the "View 716 docs" link from Page 1)

**Root cause:**
Page 1 calls `/appeal/4007370/document_count` (see `AppealsController.document_count`) 
* which calls **`EFolderService.document_count(appeal.veteran_file_number, current_user)`**
* which calls **`send_efolder_request("/api/v2/document_counts", user, headers)`**

Page 2 calls `/reader/appeal/4007370/documents?json` (see `DocumentsController.documents`)
* which calls `appeal.document_fetcher.find_or_create_documents!`
* which calls **`document_service.fetch_documents_for(appeal, ...`**, 
  * where `document_service ||= use_efolder ? EFolderService : VBMSService`
  * and `use_efolder` is effective true:
    * `use_efolder=true` for AMA appeals
    * `use_efolder: %w[reader queue hearings].include?(RequestStore.store[:application])` for legacy appeals
* which calls **`send_efolder_request("/api/v2/manifests", user, headers, method: :post)`**

**Replicated problem in the Rails console:**
```
user=User.find_by(css_id: "BVASHENEKS")
appeal=LegacyAppeal.find_by(vacols_id: 4007370)

resp=ExternalApi::EfolderService.fetch_documents_for(appeal,user)
resp[:documents].size
=> 382

respDC=ExternalApi::EfolderService.document_count(appeal.veteran_file_number,user)
=> 716
```

**Questions**
* Why is eFolder reporting different document counts? Are we using the appropriate API endpoints (`document_counts` vs `manifests`)?
* Which counts should we show on which pages?

**Comment by pkarman** [comment] 2020-01-29 23:00
Wondering if maybe https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/1137 is at play?

**Comment by kevmo** [comment] 2020-01-31 23:14
Related Sentry alert https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7307/

**Comment by msj0nes** [comment] 2020-02-07 21:01
# YourIT Tickets Impacted 
 
YourIT Ticket  Number | Date Ticket Created | Case Details URL 
-- | -- | -- 
INC0000000 | 00/00/00 |   Add case details page URL here

**Comment by pkarman** [comment] 2020-02-07 21:42
This is a bug in the new pagination service for VBMS. I can reproduce. I have opened https://github.com/department-of-veterans-affairs/connect_vbms/issues/249 to fix.

**Comment by pkarman** [comment] 2020-02-07 22:41
This should be fixed in the next release of caseflow efolder.

**Comment by pkarman** [comment] 2020-02-10 16:31
Confirmed fixed in production with example from https://github.com/department-of-veterans-affairs/caseflow/issues/13261#issuecomment-579992680

**Closed by pkarman** 2020-02-10 16:31 UTC
Labels: Bug, Reader, caseflow-queue, echo, priority-low
