### ISSUE TITLE
Intake Edit | Set issues to be pending for withdraw

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#9984] opened 2019-03-14 22:36 UTC
When "Withdraw issue" is selected, we should add that issue to a list of issue pending withdrawal.

All withdrawal/removal mocks: https://va-gov.invisionapp.com/share/BRQUJR5J5AE#/screens/351540954

requires #9983

## Acceptance Criteria
- When "Withdraw issue" is selected for an issue on the Add/remove issues page, Add that issue to a new section appearing beneath "Requested issues" called "Withdrawn issues". It should look like the mocks below.
- Additionally, if there are any issues pending withdraw on the add/remove issues page, show a box below the "Withdrawn issues" section prompting the user to enter the date the withdrawal request was received. It should show today's date as a helper/placeholder (NOT a default).
- The "Save" button should be disabled until a valid date is entered into the prompt.

## Mocks
<img width="1138" alt="Screenshot 2019-03-14 15 32 24" src="https://user-images.githubusercontent.com/1596259/54396028-cc554d00-466e-11e9-992f-b5cbcc747225.png">

## Notes
- Saving these issues as withdrawn is outside the scope of this story. This just impacts the UI.
- The date validation should just make sure that it's a date, more detailed validations will be added in another story.

**Comment by leikkisa** [comment] 2019-03-29 18:19
@carolaponce Should the number on the issues be as in the mock, or should the RequestIssues start with 1 also?  (I'm figuring the mock might have been due to copying an element and moving it, but that RequestIssues should still start with 1.

**Comment by carolaponce** [comment] 2019-04-01 18:23
@leikkisa The number of the issue is meant to be the same # of the original issue.  If issue #2 would be withdrawn, the withdrawn issues section would show issue #2...and the issues left in the requested issues would show issues #1 and #3.  Does that make sense?

**Comment by Sjones352** [comment] 2019-04-09 21:26
@leikkisa with this criteria `The "Save" button should be disabled until a valid date is entered into the prompt.` the Save button stays enabled. The prompt is already showing today's date. When I attempt to change it, the save button is still enabled
<img width="1358" alt="Screen Shot 2019-04-09 at 5 22 35 PM" src="https://user-images.githubusercontent.com/23080951/55836410-697b9800-5aec-11e9-9665-ecad78ca69a0.png">

**Closed** 2019-04-09 21:45 UTC
Labels: In-Progress, caseflow-intake, sierra
