### ISSUE TITLE
Update Error UI Copy | VBMS::CannotDeleteContention | The contention is connected to an issue in ratings and cannot be deleted

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13958] opened 2020-04-09 23:26 UTC
## Description
The issue reported stemmed from a VBMS sourced error. Our system currently shows an error that requires engineering effort with no ability to resolve via Caseflow team. 

## Acceptance criteria
- [ ] The updated copy is specific to 'VBMS::CannotDeleteContention' only
- [ ] The copy is replaced with the information below

**Copy:**
VBMS::CannotDeleteContention
A contention listed is connected to an issue that cannot be deleted by Caseflow. Please update via VBMS.  

## Background/context/resources
AMO Slack reported issue: Slack thread: https://dsva.slack.com/archives/CFBLH2LR4/p1586452071098900

[Associated GH](https://github.com/department-of-veterans-affairs/caseflow/issues/10571)
## Technical notes
**Sample backend error: **
`"#<VBMS::CannotDeleteContention: status_code=500, body=<env:Envelope xmlns:env=\"http://schemas.xmlsoap.org/soap/envelope/\"><env:Header/><env:Body><env:Fault><faultcode>env:Server</faultcode><faultstring>Removing Contention failed. System error. GUID: edc7dc32-b61c-422d-bffc-9101cace5454</faultstring><detail><ns2:serviceException xmlns:part=\"http://vbms.vba.va.gov/cdm/participant/v5\" xmlns:ns2=\"http://vbms.vba.va.gov/external/ClaimService/v5\" xmlns:doc=\"http://vbms.vba.va.gov/cdm/document/v5\" xmlns:com=\"http://vbms.vba.va.gov/cdm/common/v5\" xmlns:claim=\"http://vbms.vba.va.gov/cdm/claim/v5\" xmlns:aw=\"http://vbms.vba.va.gov/cdm/award/v4\"><ns2:exception>The contention is connected to an issue in ratings and cannot be deleted.</ns2:exception><ns2:message>Removing Contention failed. System error.</ns2:message></ns2:serviceException></detail></env:Fault></env:Body></env:Envelope>, request=#<VBMS::Requests::RemoveContention:0x00007f258d536470 @contention=#<VBMS::Responses::Contention id=\"00000\", text=\"UNIDENTIFIED ISSUE - Please click *Edit in Caseflow* button to fix\", start_date=Thu, 09 Apr 2020, submit_date=Wed, 25 Mar 2020, actionable_item=\"false\", awaiting_response=\"unknown\", claim_id=\"00000\", classification_cd=\"80000\", contention_category=nil, file_number=\"\", level_status_code=nil, medical=\"true\", participant_contention=\"unknown\", secondary_to_contention_id=\"00000\", type_code=\"SUP\", working_contention=\"unknown\">, @v5=true, @send_userid=true>>"`

Current System Error 
![image](https://user-images.githubusercontent.com/41164406/78948608-f6a65380-7a96-11ea-90e8-be566ce55b55.png)

**Comment by leikkisa** [comment] 2020-04-13 19:07
I am moving this to "Define" - I believe CannotDeleteContention can also happen in other scenarios (such as if the contention text is blank).  This error message - "Previous update not yet done processing" also handles a variety of scenarios so when updating the error message for this specific case, I think it's worth investigating whether we can include a more useful error message for the other cases as well (to keep one alert that handles multiple of these situations with more information instead of breaking off one customization).

The specific error message mentioned above is now preventable through using the new RatingAtIssue service.  See #13977 for a ticket to prevent this error.

**Comment by leikkisa** [comment] 2020-07-22 15:28
Closing as a dupe of #13977

**Closed by leikkisa** 2020-07-22 15:28 UTC
Labels: Eng: Backend Work Group, Eng: Frontend Work Group, Priority: Medium, Product: caseflow-intake, Source: AMO Reported, Team: Foxtrot 🦊, Type: Enhancement, Type: UI Change
