### ISSUE TITLE
AMA Intake | Don't show ineligible issues as having been added to an appeal

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#7656] opened 2018-10-31 23:39 UTC
Currently, ineligible issues are shown as having been added to an appeal. Even though we save them to the database, they should not considered to be issues on the appeal (similar to HLRs and SCs, where we do not create a contention)

## Acceptance Criteria
- Ineligible issues should not show up on the confirmation page of an appeal intake

## Screenshot
In this screen shot, one of these two issues was ineligible
![screen shot 2018-10-31 at 7 27 03 pm](https://user-images.githubusercontent.com/1596259/47824771-cc4e5380-dd44-11e8-966d-a9e0d40f42fe.png)

**Comment by pkarman** [comment] 2018-11-01 16:11
I think this is covered by #7308

**Comment by kencheeto** [comment] 2018-11-19 18:39
Dupe of #7308

**Closed by kencheeto** 2018-11-19 18:39 UTC
Labels: Ready-for-Dev, bug-medium-priority, caseflow-intake, sierra
