### ISSUE TITLE
IE | Add warning banner to use Chrome

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#2203] opened 2017-06-01 16:22 UTC
Add a warning banner to the top of Reader to say that Reader is not supported on IE, and that users should use Chrome.
## AC
- Use Warning banner [Current style guide issue](https://github.com/department-of-veterans-affairs/caseflow/issues/1084), [USWDS](https://standards.usa.gov/components/alerts/)

## Mock up
![image](https://cloud.githubusercontent.com/assets/13420618/26695830/518c348e-46da-11e7-8cff-bf731b451a34.png)

## Copy
Title: Reader is not supported in Internet Explorer 
Body: Please use Chrome to continue reviewing  cases in Caseflow.

**Comment by NickHeiner** [comment] 2017-06-01 18:55
Before we put this in, can we spend a few moments trying to fix it in IE? It may be that we can fix the root cause.

Also, how do we plan on determining what browser the user is on? UA sniffing can be really brittle.

**Comment by abbyraskinUSDS** [comment] 2017-10-12 13:46
@mdbenjam It seems unlikely we'll be ready to support IE before launch - do you think this is worth having in place in the meantime?

**Comment by mdbenjam** [comment] 2017-10-12 17:57
Agreed that we probably won't have IE in place before launch. Let me jump on a VA machine and check what happens when we open it in IE. I haven't investigated this in a while. If it seems straight forward we can try to fix it. If not, we'll investigate putting up this banner.

**Comment by abbyraskinUSDS** [comment] 2017-11-06 15:07
@mdbenjam do you have a better sense of how big of a lift it is to fix Reader in IE?

**Comment by mdbenjam** [comment] 2017-11-06 21:28
Not really, I just haven't looked at it, and likely won't have much time to. Let's prioritize this next sprint? Have someone take a look and assess what's going on, then make a decision.

**Comment by abbyraskinUSDS** [comment] 2017-12-14 00:01
Closing in favor of #4133

**Closed by abbyraskinUSDS** 2017-12-14 00:01 UTC
Labels: caseflow-reader, Triage, whiskey
