### ISSUE TITLE
Motions to vacate | As a dispatch worker, when I receive a grant ruling on a motion to vacate from a VLJ, I ... do what? 

### ISSUE THREAD

**Issue by carodew** [department-of-veterans-affairs/caseflow#11726] opened 2019-08-09 18:37 UTC
## User story 

As a dispatch worker, when I receive a grant ruling on a motion to vacate from a VLJ, I ... do what? 

## Outstanding questions 

- [ ] What do they do? 
- [ ] What data is involved? What systems? 

## AC

- [ ] ????

**Comment by rutvigupta-design** [comment] 2019-08-19 18:17
### 8/19: Draft of what we want to learn from dispatch

**UNDERSTAND**
- What is their current process for when they receive a grant ruling on a motion to vacate?
    - Who are these humans? Is this their main job? What else are they doing?
    - How familiar are they with MTVs?
    - How do they get the ruling?
    - What happens next?
    - What systems do they work in?
    - What data are they working with?

- Outcoding - need more clarification from Geronimo around this


**VALIDATE**
- How familiar are they with pulac-cerrulo checks? May be an important user group to get feedback on designs


**IDENTIFY**
- What do we need to design for them?

**Comment by carodew** [comment] 2019-08-19 19:47
To be defined by #11830

**Comment by leikkisa** [comment] 2020-01-29 04:26
This looks like a duplicate of: https://github.com/department-of-veterans-affairs/caseflow/issues/11830, which has the same information in it (I don't see extra information in here), so closing as a dupe.

**Closed by leikkisa** 2020-01-29 04:26 UTC
Labels: design 💅, foxtrot, priority-medium, size-dragon 🐉
