### ISSUE TITLE
Write tech spec to allow DVC & their Administrative Assistants to view and action on that DVC's work

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#10551] opened 2019-04-25 17:46 UTC
As a team admin, I can navigate to my judge's Assign Cases view, so I can either (1) assign cases to attorneys on my judge's team (2) reassign cases from one attorney to another on my judges team and (3) request cases on behalf of my judge.

The primary use case for this right now is DVC Admins being part of DVC judge teams.

## AC
- Team admins have the option to `Switch views` to their judge's Assign Cases page
- Team admins can view cases assigned to the judge (`JudgeAssignTask`s)
- Team admins can view attorney case loads
- Team admins can assign cases to attorneys
- Team admins can reassign cases from one attorney to another
- Team admins can assign cases to judges
- Team admins can assign cases from one judge to another

## Out of scope
I think requesting cases on behalf of the judge can be a separate ticket. LP needs to confirm this is required. 

## Resources
Discussion ticket where we explored options - https://github.com/department-of-veterans-affairs/caseflow/issues/9704

**Comment by lowellrex** [comment] 2019-04-25 17:51
Note: We need to make sure that there is still only one judge per judge team and that we can identify who that judge is by calling `JudgeTeam.find().judge`

**Comment by lowellrex** [comment] 2019-05-01 20:21
MEDIUM for a tech spec.

**Comment by lowellrex** [comment] 2019-05-16 17:51
In order to support SSC at the current moment they all have `JudgeTeam`s where they are the only member. The tech spec that comes out of this ticket needs to consider whether we want to continue that arrangement, what its implications are, and what some alternative arrangements might be. Here is a link to the Github comment that outlines how we did that: https://github.com/department-of-veterans-affairs/caseflow/issues/10048#issuecomment-493149110

**Comment by laurjpeterson** [comment] 2019-05-29 18:44
@lowellrex - we're thinking about just giving users the VLJ role in VACOLS as a stop gap for the engineering work that needs to be done here. what do you think about that?

Supervisory Senior Counsel could assign tasks to DVC team admins (judges). They could then assign tasks to other judges. 

It will have implications for Case Timeline, but maybe that's ok right to just solve their short term problem until we prioritize a longer term solution. 

cc: @nicholasholtz so he can see your response.

**Comment by lowellrex** [comment] 2019-05-30 12:12
> we're thinking about just giving users the VLJ role in VACOLS as a stop gap for the engineering work that needs to be done here.

I don't know exactly what these users want to be able to do but I don't think they'll be able to do whatever it is they want with the VLJ VACOLS role alone because judge tasks are [restricted to the judge](https://github.com/department-of-veterans-affairs/caseflow/blob/6c73a230dcb661c4092c184cb195239d19f12182/app/models/tasks/judge_task.rb#L17) that is assigned that task.

**Comment by msj0nes** [comment] 2019-05-30 12:55
SSC Team Admins (Jureka and Wendy) need to be able to:
>Be assigned a case from an SSC  
>Be able to assign to a VLJ. 

I have confirmed that is all they will be doing in Caseflow.

The SSC Team Admins currently have AVLJ roles in VACOLS because they currently perform this assignment role, transferring cases from SSCs to VLJ in VACOLS. If Caseflow can recognize them as a VLJ this should resolve the issue so they can receive and transfer cases. 


**_The main reason SSCs cannot do this themselves though they can via Caseflow VLJ to VLJ transfer is a DVC based policy where they are not allowed to assign a case to a Judge, it must go through the SSC Team Admin._**

**Comment by lowellrex** [comment] 2019-06-05 20:50
Did this manually Wednesday 5 June. https://dsva.slack.com/archives/CHX8FMP28/p1559754284017500

**Comment by lomky** [comment] 2019-06-18 14:21
**BLUF**: We have several needs that have converged in this ticket. I am going to hopefully pull these efforts apart in this ticket for context and open the needed multiple other tickets for the other efforts.                  
                                                                                                                        
## Efforts                                                                                                              
                                                                                                                        
### Overview                                                                                                            
                                                                                                                        
- Differentiating the needs and roles of:                                                                               
  - DVC & DVC Administrative Assistants                                                                                 
  - SSCs                                                                                                                
  - all Judges                                                                                                          
                                                                                                                        
- Both DVC & SSC needs have implications with                                                                           
  - reliance on VACOLs roles                                                                                               
  - working with or deprecating DAS                                                                                        
                                                                                                                           
- DVC may require a new org structure, not fitting nicely into JudgeTeams                                                  
  - DVC may also be a judge, but the role of DVC & DVC Administrative Assistants seems to be more about managing cases inside the system                                                                                                              
  - DVC Administrative Assistants play a very different role than either Judges or Attorneys on a JudgeTeam, both administratively in Caseflow and with regards to actions they take in their role.                                   
  - DVC & their assistants need to:                                                                                     
    - Move cases from anywhere to Judges for assignment                                                                 
    - Reassign cases from any judge to another                                                                          
    - request & assign cases as the DVC, if the DVC is acting in a Judge role as well.*                                
                                                                                                                        
* may come later                                                                                                       
                                                                                                                        
- SSCs fit relatively well into the existing JudgeTeam organization structure                                           
  - SSCs need to be able to                                                                                             
    - Reassign JudgeTasks from _any_ judge to _another_ judge                                                           
    - Act as a Judge                                                                                                    
      - Assign cases to Attorneys                                                                                       
      - Act as Acting Judges to Review Decisions                                                                        
    - Act as an Attorney                                                                                                
      - (all attorney abilities)                                                                                        
  - Possible we will either update JudgeTeam to hold SSCs, or subclass Judges to handle SSCs.                           
                                                                                                                        
- Judges have a missing ability that came out of this discussion                                                        
  - reassign any case assigned to a judge _to themselves_                                                               
  - reassign any _of their cases_ to another judge                                                                      
                                                                                                                        
### Moving Forward                                                                                                      
                                                                                                                           
This ticket has become a bit cluttered with multiple terminology & user needs. I'm going to focus this issue on DVC and move over:                                                                                                            
                                                                                                                          
 - Give judges reassign capability around their own tasks 
 - Handle users with Judge & Non-Judge Queue views
 - A Tech Spec tick for SSC Organization, task handling                                                                            
                                                                                                                        
This issue will focus on:                                                                                                          
                                                                                                                        
 - Tech Spec DVC & DVC Assistant Organization & task handling

**Comment by Chingujo** [comment] 2019-06-25 15:50
@laurjpeterson @lomky 

Added myself and Nichole to the issue since it's the most up to date one and for awareness =D. Will post some design artifacts before our call at 10 tomorrow here

**Comment by lomky** [comment] 2019-06-26 14:57
Discussion on cases: https://dsva.slack.com/archives/CJL810329/p1561559611094700

**Comment by lomky** [comment] 2019-06-26 18:48
Discussion with LRP: https://dsva.slack.com/archives/CJL810329/p1561572176104500

**Comment by lomky** [comment] 2019-06-27 13:20
After several discussions internally and with stakeholders, we're going to split the SuperAOD capability out completely from Super AOD. Tech spec updated & new ticket incoming for that.

**Comment by lomky** [comment] 2019-07-08 13:41
@laurjpeterson are you satisfied that our tech spec work is complete? I'm good to close this issue if you are!

**Comment by laurjpeterson** [comment] 2019-07-08 13:47
Yes!

**Closed** 2019-07-08 13:52 UTC
Labels: caseflow-queue, echo
