### ISSUE TITLE
AMA intake | Finish page duplicate issue validations

### ISSUE THREAD

**Issue by abbyraskinUSDS** [department-of-veterans-affairs/caseflow#5228] opened 2018-04-18 20:42 UTC
If a user attempts to create an identical AMA issue that is already pending in the system, we should show them an alert so they can take the necessary actions to notify the Veteran. Eventually, this alert will also tell users if they attempt to request an ineligible lane for other reasons (e.g., they try to go from higher-level review to higher-level review twice in a row for the same issue).

## AC
- The bullets include the name of the review lane associated with the issue in conflict, then the issue description (from rating profile)
- Users must select the checkbox to proceed to the next step - "Create" button is disabled if there is an alert present without the checkbox selected

## Mocks
![image](https://user-images.githubusercontent.com/4042181/40281509-f15f665e-5c30-11e8-8361-c44009d41f77.png)

**Comment by abbyraskinUSDS** [comment] 2018-04-18 20:57
Design ticket: https://github.com/department-of-veterans-affairs/appeals-design-research/issues/777

**Comment by abbyraskinUSDS** [comment] 2018-05-14 15:55
Work on this sprint

**Comment by leikkisa** [comment] 2018-07-03 18:08
While it's pending, it can't be taken through an AMA flow. After an EP is created, it can go through another flow but not another Higher Level Review.

**Comment by shanear** [comment] 2018-10-09 21:00
Duplicate of https://github.com/department-of-veterans-affairs/caseflow/issues/7292

**Closed by shanear** 2018-10-09 21:00 UTC
Labels: Triage, caseflow-intake, duplicate
