### ISSUE TITLE
Investigate bug where the user can't copy/paste on Sign & Certify page

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#2582] opened 2017-07-11 21:24 UTC
Investigate why the name of certifying official clears out when the user copies and pastes text into the field and changes the radio button of their title.

During St. Pete pilot, we saw a user copy & paste their name into the 'Name of certifying official' field on the Sign & Certify page. 'Other was selected by default as the 'Title of certifying official'. When the user changed her role to DRO, her name was cleared out.

This did not happen when the user typed in their name.

**Comment by amprokop** [comment] 2017-07-14 15:40
This may be IE only. @kierachell can you reproduce this?

**Comment by kierachell** [comment] 2017-07-18 12:20
### Tried Chrome/FF and IE... nothing
![iesign](https://user-images.githubusercontent.com/18075411/28316691-d4359354-6b91-11e7-9fa6-80617bbf5c9d.gif)

**Comment by astewarttistatech** [comment] 2017-12-06 14:32
Marked as obsolete due to inability to reproduce said bug.

**Closed** 2017-12-06 14:32 UTC
Labels: caseflow-certification, foxtrot, Obsolete, Ready-for-Dev
