### ISSUE TITLE
Change "Go back ..." link back to JavaScript

### ISSUE THREAD

**Issue by webinista** [department-of-veterans-affairs/caseflow#271] opened 2015-12-03 15:03 UTC
Needs to use history - 1 syntax to preserve state for now.

**Comment by plusjeff** [comment] 2015-12-03 15:57
#273 is submitted for this. Will close this issue.

**Closed by plusjeff** 2015-12-03 15:57 UTC
Labels: frontend

**Comment by plusjeff** [comment] 2015-12-03 15:59
Duplicate of #270 - this can be closed.
