### ISSUE TITLE
Litigation Support | Pulac-Cerullo reminders

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#11256] opened 2019-07-01 02:24 UTC
## Story
As a..
- Lit support lead (?)
- motions attorney
- judge
- decision-drafting attorney
- dispatch team member
.. working a post-decisional motion case, I need to remember to (1) check the CAVC website for conflicts of jurisdiction and (2) notify Litigation Support if I find a potential conflict.

#### _Flow 1: Alert + Action (motions attorney, judge, decision-drafting attorney users) _
- [_follow up with LP about this 120-day requirement: Caseflow users are reminded to check for "Pulac-Cerullo" if a case is within 120 days from its decision date_]
- A warning alert displays within the 'Currently active tasks' section of Case Details
  - Title copy: Check CAVC for conflict of jurisdiction
  - Body copy: If this decision has a Notice of Appeal (NOA) on file at the CAVC website, use the Actions menu to notify Litigation Support. See Chairman's Memorandum No. 01-10-18 for more information about how to conduct NOA checks.
  - (Body contains a link to the CAVC website: https://www.uscourts.cavc.gov/)
- A new option is added to the Actions menu: 'Notify Litigation Support of CAVC jurisdictional conflict'
- When the user selects the 'Notify Litigation Support' option, a modal displays:
  - Modal title: Notify Litigation Support of Conflict of Jurisdiction
  - Modal body: 
    - This case will be assigned to a Litigation Support team member to determine how to proceed. 
    - It will return to your Queue when it can be worked again.
  - Cancel link
  - Notify button
- Selecting the 'Notify' button:
  - (1) creates a [existing task name here] task and sends the case the Lit Support Chief's Pulac-Cerullo queue. 
  - (2) takes the user back to their queue and displays a success alert:
    - Title copy: Case assigned to Litigation Support
    - Body copy: Bob Smith's case will return to your Queue when it can be worked again.

![Flow 1-1 Check CAVC Alert - Case Details - Dropdown scrolled.png](https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/6a5c5f8e-82f0-489c-9dd0-be19c8e76d54)
![Flow 1-2 Check CAVC Alert - Modal.png](https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/a6d0034d-a215-4555-bb33-7dcb21984d6a)
![Flow 1-3 Check CAVC Alert - Confirmation.png](https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/b41dfb59-9b2d-4fe2-828a-7d49a4f79db8)

#### _Flow 2: Confirmation Modal before Sending to Dispatch (judge user) _
- When a case is post-decisional and the judge selects "Ready for Dispatch" in the Actions menu, a modal displays:
  - Modal title: Check CAVC for Conflict of Jurisdiction
  - Modal body: 
    - Before sending this case to Dispatch, be sure there is no Notice of Appeal (NOA) on file at the CAVC website.
    - (Body contains a link to the CAVC website: https://www.uscourts.cavc.gov/)
  - Radio input field with 2 options:
    - Field label: Does this decision have an NOA on file at CAVC?  (Appellant name: Bob Smith)
    - Option: Yes, assign to Litigation Support to determine jurisdiction
    - Option: No, continue sending for Dispatch
  - Cancel link
  - Submit button
- Selecting 'Yes' and the 'Submit' button:
  - (1) creates a [existing task name here] task and sends the case the Lit Support Chief's Pulac-Cerullo queue. 
  - (2) takes the user back to their queue and displays a success alert:
    - Title copy: Case assigned to Litigation Support
    - Body copy: Bob Smith's case will return to your Queue when it can be worked again.
- Selecting 'No' and the 'Submit' button takes the judge to the existing Ready for Dispatch flow

![Flow 2-1 Check CAVC before Dispatch - Case Details.png](https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/269f38d6-202c-4989-98f5-e685fe567377)
![Flow 2-2 Check CAVC before Dispatch - Modal.png](https://images.zenhubusercontent.com/5d07e8ae41e1974be7393f73/1c5d462c-7913-49e9-b6a0-7e3cee5312d5)

## Final Design
https://www.figma.com/file/o1sZ0MsecXAyyQ6XL7fkzB/Master-MTV-File?node-id=0%3A1

**Comment by carodew** [comment] 2019-08-09 18:45
There are some new questions that have come up in recent conversations that I'm capturing here: 

- [ ] Should we introduce more friction by changing the banner to a modal, so that users have to acknowledge it? 
- [ ] Would we need to audit whether or not  a user actually checked for PC? (don't need to track the checks but might be useful to see the last time it would checked)
- [ ] When is the pattern so annoying that people just ignore it, vs. is it a useful reminder? 
- [ ] Is there a way to have a machine ingest this information from the CAVC website _for_ users, instead of them having to check manually (or is that too heavy a lift?) 

Given that we have one set of designs already, one option is to proceed with shipping these designs and create a new ticket to further test different options to see what design pattern is more impactful, or we could continue iterating on these designs. I leave that to foxtrot and product to decide the best path forward.

**Comment by jimruggiero** [comment] 2019-09-03 18:45
@carodew @geronimoramos @rutvigupta-design @laurjpeterson I discussed with LP and Product would like to ship the functionality as designed above and use real world usage and feedback to inform future design iterations. I will queue this ticket for engineering estimation later this week and potential ENG work in the next two sprints.

**Comment by jimruggiero** [comment] 2019-09-03 19:59
@geronimoramos and @rutvigupta-design Please let me know what information I should pull forward into the new subsequent issue other than the five questions in @carodew comment above to ensure nothing is lost when research continues.

**Comment by jimruggiero** [comment] 2019-09-18 22:31
@geronimoramos Based on our earlier conversation should we move this back into Design/In Progress?

**Comment by carodew** [comment] 2019-09-23 18:01
Noting the accessibility issues around the click to copy functionality elsewhere in Caseflow: https://github.com/department-of-veterans-affairs/appeals-team/issues/1195

**Comment by jcq** [comment] 2019-09-25 23:42
Just to be clear, is this new nomenclature and flow replacing the existing "Notify OGC of Pulac-Cerullo" action?

**Comment by geronimoramos** [comment] 2019-09-25 23:51
@jcq correct, "Notify Litigation Support of CAVC jurisdictional conflict" will copy-wise replace "Notify OGC of Pulac-Cerullo" because it is incorrect nomenclature. The user is not notifying OGC, it is a Lit Support lead who communicates with OGC. 

I don't believe it will replace the action itself that already exists. "Notify Lit Support" will assign the task back to a Lit Support Lead/Admin which I believe puts the task on hold for the current user working the case.

**Comment by jcq** [comment] 2019-09-27 23:03
Notes from further convo w/ @geronimoramos:

- no 120-day check (for now at least)
- alert is displayed conditionally if there exists a `VacateMotionMailTask` related to the appeal
- "Notify Lit Support" action & modal copy replaces that from current OGC one, but uses same workflow
- judge flow has new modal inserted to branch during "ready for dispatch" action, but also has the same "notify lit support" action and alert due to the aforementioned condition

**Comment by geronimoramos** [comment] 2019-10-08 18:19
![Check CAVC before Dispatch Modal](https://user-images.githubusercontent.com/49766982/66421788-5e32f780-e9bd-11e9-8bc3-2d4d5c3599ca.png)
@jcq update is here!
-> yes will continue with 'Ready for Dispatch' flow
-> no will assign to Lit Support for Pulac-Cerullo check stuff

**Closed** 2019-11-04 19:37 UTC
Labels: BVA, caseflow-queue, design 💅, enhancement, foxtrot, priority-medium, size-badger 🦡
