### ISSUE TITLE
App Canvas | Links turn into blue buttons upon hover

### ISSUE THREAD

**Issue by lakohl** [department-of-veterans-affairs/caseflow#1246] opened 2017-03-20 22:01 UTC
When using IE if a user hovers over the Cancel button a dark blue box appears (with no text)

Related to #1219

**Comment by shanear** [comment] 2017-03-22 02:32
Is this related to #1219, or a duplicate of #1219?

**Comment by kierachell** [comment] 2017-03-23 18:21
duplicate of #1219

**Closed by kierachell** 2017-03-23 18:21 UTC
Labels: bug, caseflow-dispatch, tango, Triage
