### ISSUE TITLE
Standardize our open_timeout values

### ISSUE THREAD

**Issue by monfresh** [department-of-veterans-affairs/caseflow#11752] opened 2019-08-13 14:43 UTC
We are using various different numbers for `open_timeout` throughout our repos. I think we've all come to an agreement that open timeouts should be very small. Let's make them the same value everywhere. For example, in Caseflow, we use 600 for efolder, and 30 for va dot gov service. In the BGS and VBMS gems, we reduced those to 10.

**Comment by monfresh** [comment] 2019-08-13 14:43
cc @pkarman

**Comment by alisan16** [comment] 2020-04-01 20:37
Closing this as we have not heard complaints or issues caused by this

**Closed by alisan16** 2020-04-01 20:37 UTC
Labels: Type: Tech-Improvement
