### ISSUE TITLE
Improperly updating tasks after checkout flows

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#8095] opened 2018-12-04 17:07 UTC
Currently when completing a checkout flow we don't always properly update the tasks. i.e. if you do an attorney checkout flow the completed task doesn't end up under the completed tab. They do show up after reloading the page. We need to reload tasks after completing a checkout flow.

**Comment by joeyyang** [comment] 2018-12-11 18:32
Just want to chime in to say that this behavior also exists when adding an admin action to a task — i.e., the tab contents and numbers do not update when a task has been sent away for an admin action.

**Comment by lowellrex** [comment] 2018-12-12 14:18
Screencap of the on hold count decreasing (legacy appeals disappear) after an attorney creates an admin action for an AMA appeal:

![onholdcountmismatch](https://user-images.githubusercontent.com/32683958/49875410-ef156280-fdee-11e8-8ee9-e6f6d7674790.gif)

**Comment by lowellrex** [comment] 2018-12-18 17:09
One problem we are able to reproduce and pinpoint is the issue of tasks related to cases with new documents disappearing from the "on hold" tab. It appears as if the [`onHoldTasksByAssigneeCssIdSelector` selector](https://github.com/department-of-veterans-affairs/caseflow/blob/9079cd44ccfb30ec2af56627261b5862f627a345/client/app/queue/selectors.js#L207) is causing this because it is filtering out tasks related to cases with new documents.

### Steps to reproduce:
* Log in as `BVASCASPER1`
* Make sure there is a task related to a case with new documents (can probably spoof this by hard coding some appeal IDs locally [in `AppealsController.new_documents`](https://github.com/department-of-veterans-affairs/caseflow/blob/9079cd44ccfb30ec2af56627261b5862f627a345/app/controllers/appeals_controller.rb#L28)
* Load `/queue` (see a flicker in the count of tasks that are on hold, from larger number to smaller number)
* Comment out the request to [hit the new documents endpoint in `QueueLoadingScreen`](https://github.com/department-of-veterans-affairs/caseflow/blob/9079cd44ccfb30ec2af56627261b5862f627a345/client/app/queue/QueueLoadingScreen.jsx#L68)
* Load `/queue` (see only the larger number in the on hold tab count, no flicker)
* Click on the "on hold" tab.
  - This should fire requests to the new documents endpoint and the on hold count will decrease at this point in time.

**Comment by lowellrex** [comment] 2019-01-14 21:35
We can reproduce one bug by [replicating this test](https://github.com/department-of-veterans-affairs/caseflow/blob/82c86fb6523c20353427d37060dffde452b84ef6/spec/feature/queue/case_assignment_spec.rb#L41) that creates an admin action for a legacy appeal, makes the case disappear from the "assigned" tab but one does not appear in the "on hold" tab.

**Comment by tomas-nava** [comment] 2019-03-21 20:22
not pointed; we need more investigation to understand whether there's a single cause for every case.

**Comment by hschallhorn** [comment] 2019-04-01 19:10
So I've done some looking into adding an admin action to a legacy appeal and there are two separate issues. 
1. **The parent task does not show up in the on hold tab**
We don't actually handle the newly created tasks that are returned with the request as we do when we create an admin action on an [AMA task](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/AddColocatedTaskView.jsx#L114). This includes [colocated tasks that were assigned by this attorney/judge](https://github.com/department-of-veterans-affairs/caseflow/blob/f068585c136c6a8a5df89d9a2c79eec426e395ec/app/models/queues/attorney_queue.rb#L12) which will show up in the on hold tab the on hold tab. This is an easy fix that I already have written up and tested. ✅ 
2. **The parent task remains in the assigned tab**
The legacy tasks assigned to the user are not returned with this request. These are grabbed from a [separate endpoint](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/QueueLoadingScreen.jsx#L39) when the page is loaded, which is why the queue is correct after a reload.

**Comment by hschallhorn** [comment] 2019-04-02 16:10
> Screencap of the on hold count decreasing (legacy appeals disappear) after an attorney creates an admin action for an AMA appeal:
> 
> ![onholdcountmismatch](https://user-images.githubusercontent.com/32683958/49875410-ef156280-fdee-11e8-8ee9-e6f6d7674790.gif)

This issue is caused by calling `onReceiveAmaTasks` which [sets all amaTasks](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/reducers.js#L97) rather than [merging as `onReceiveTasks` does](https://github.com/department-of-veterans-affairs/caseflow/blob/master/client/app/queue/reducers.js#L91). This overwrites any colocated tasks from a legacy appeal that the attorney has assigned. Another easy and texted fix ✅

**Comment by laurjpeterson** [comment] 2019-05-15 20:44
hey @hschallhorn - i see your PR on this issue has been merged! can this ticket be closed?

**Closed** 2019-05-15 20:44 UTC
Labels: Bug, In-Progress, bug-medium-priority, caseflow-queue, foxtrot, queue-table-view
