### ISSUE TITLE
On dispositions screen, button text doesn't change correctly after dispositions are changed

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#5204] opened 2018-04-17 20:51 UTC
When an issue on an appeal is marked "Remand", then all dispositions are changed such that none is marked "Remand", the continue button still says "Select remand reasons".

# AC
- When one or more issues are marked "Remand" on an appeal, the continue button text should change to "Select remand reasons"
- If the dispositions are all then changed to something other than "Remand", the continue button text should change back to "Finish dispositions"
- Likewise, if all issues are marked with "Allowed", then one is changed to "Remand", the continue button text should change to "Select remand reasons"

**Comment by dannysellers** [comment] 2018-04-17 20:55
Dupe of #5092, closing

**Closed by dannysellers** 2018-04-17 20:55 UTC
Labels: Bug, caseflow-queue, foxtrot
