### ISSUE TITLE
Document Viewer | Display error when documents don't load

### ISSUE THREAD

**Issue by mdbenjam** [department-of-veterans-affairs/caseflow#3794] opened 2017-10-30 17:43 UTC
## Story
Currently when a document request fails we don't provide relevant UI to the user indicating that the document didn't load. Instead the user sees a gray page and the message: "loading document...".

## AC
1. Verify that when loading a document fails the user is shown the below UI.
1. Type should be treated like [status message from style guide](http://dsva-appeals-certification-demo-1715715888.us-gov-west-1.elb.amazonaws.com/styleguide#messages)
1. Add the [error alert icon](https://github.com/department-of-veterans-affairs/appeals-design-research/blob/master/Projects/Styleguide/Design%20files/Icons/Error%20Alert%20Icon.svg) in front of Title 

## Mock up 

![image](https://user-images.githubusercontent.com/32683958/32617926-4ff6ce48-c544-11e7-9caa-f3511d1ecde2.png)

## Copy

Title: Unable to load document 
Description: Caseflow is experiencing technical difficulties and cannot load [Insert document type in bold]. You can try [downloading the document] (hyperlink to download) or try again later.

**Comment by abbyraskinUSDS** [comment] 2017-11-02 18:08
Instead of "Please refresh this page" sentence, how about "You can try [downloading the document](hyperlink)", as refresh likely won't fix the issue.

**Comment by gnakm** [comment] 2017-11-02 19:19
+ 1 Abby.

**Comment by astewarttistatech** [comment] 2017-11-13 13:29
@lowellnava This message doesn't show up at all. The page is still stuck with the "loading documents" at the footer and the blank canvas in the background. 

Validated: Chrome | Preprod

Current View:
![errorunloading](https://user-images.githubusercontent.com/23038505/32727970-98798646-c84c-11e7-8314-6e1c3cf7f892.gif)

**Comment by astewarttistatech** [comment] 2017-11-21 16:21
Blocked because of 5XX errors in Reader. Current View:

**Comment by kierachell** [comment] 2017-11-23 15:34
### How is the `download the documents` page supposed to work?

<img width="783" alt="screen shot 2017-11-23 at 10 29 03 am" src="https://user-images.githubusercontent.com/18075411/33180157-cda7ef66-d039-11e7-8bbd-4ee10da2da98.png">
<img width="521" alt="screen shot 2017-11-23 at 10 29 06 am" src="https://user-images.githubusercontent.com/18075411/33180163-d03e21d2-d039-11e7-9323-11263b460777.png">

**Comment by lowellrex** [comment] 2017-11-27 22:06
@kierachell I can't trigger that issue in my local dev environment (the download link in the dialogue and the download link in the PDF viewer both work) but perhaps that because of an issue with the dev environment not being an accurate replica of production and I'm having trouble accessing UAT right now (beplinktest-piv.vba.va.gov is not resolving).

The way the "downloading this document" link is supposed to work is that it is supposed to be a link to the document that is exactly the same as the download icon in the the PDF viewer UI. Is the icon download link working? Do the addresses of those link match (I suspect perhaps the one in the dialog box has part of it that is no URL encoded)?

**Comment by kierachell** [comment] 2017-11-27 22:34
This happens when the user doesn't have appropriate access to eFolder (efolder 403 errors that you might've seen in Sentry)

**Comment by lowellrex** [comment] 2017-11-29 14:50
Since both of the links to download the document (icon and text link) are broken, that indicates that this change is not a regression, and I think that will need to be handled as part of a different ticket (perhaps https://github.com/department-of-veterans-affairs/caseflow-efolder/issues/742). If we need to hold off on releasing this ticket until the document download failure issue is addressed so we do not present reader users with meaningless calls to action, I am comfortable with that.

**Comment by kierachell** [comment] 2017-11-29 15:14
**PASSED**

Link is there...kinda works... I guess

**Closed by kierachell** 2017-11-29 15:14 UTC
Labels: bug-medium-priority, caseflow-reader, In-Progress, requirements-incorrect, whiskey
