### ISSUE TITLE
Handle undefined attorney in app/queue/AssignedCasesPage.jsx

### ISSUE THREAD

**Issue by yoomlam** [department-of-veterans-affairs/caseflow#12999] opened 2019-12-17 18:08 UTC
## Description

In `app/queue/AssignedCasesPage.jsx `, an error occurs when an attorney is not found and thus is undefined. Handle this case better: `app/queue/AssignedCasesPage in full_name: Cannot read property 'full_name' of undefined`

## Background/context/resources

During Bat Teaming, Sentry alert occurred: https://dsva.slack.com/archives/CLRTL92TW/p1576600351014300

Sentry alert: https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7605/

## Technical notes

```
const attorneyName = attorneysOfJudge.filter((attorney) => attorney.id.toString() === attorneyId)[0].full_name;
```
initiated by `./app/queue/QueueActions.js in dispatch at line 372`

**Comment by hschallhorn** [comment] 2020-01-23 14:56
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/7686/?query=is%3Aunresolved%20%22app%2Fqueue%2FAssignedCasesPage%20in%20full_name%22

**Comment by hschallhorn** [comment] 2020-01-23 14:58
_[What is this graph?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```
1 | 
2 | ||||||||||
3 | ||||
5 | 
8 |  
```
Timebox this to a two as it has only occurred twice to a couple of users.

**Comment by jcq** [comment] 2020-04-23 16:28
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/8849/

FYI, while this issue is marked as low priority, it is preventing me from loading the case assignment page mentioned in that sentry alert. I assume this is likely a large issue for that particular user.

If you like shiny new things, this might be a good candidate for using the [optional chaining](https://github.com/department-of-veterans-affairs/caseflow/wiki/Frontend-Things-to-Avoid#prefer-concise-syntax) and/or [nullish coalescing](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator) operators.

**Comment by hschallhorn** [comment] 2020-04-23 19:59
Prioritize'd! Thanks for bringing this up!

**Comment by yoomlam** [comment] 2020-05-04 21:52
I'm able to replicate and see the error in the console by going to an acting judge (who doesn't have attorneys) and manually entering http://localhost:3000/queue/BVAACTING/assign/88 (the resulting page is blank).

@jcq Can you describe how I can replicate the error you described here?
> FYI, while this issue is marked as low priority, it is preventing me from loading the case assignment page mentioned in that sentry alert.

**Comment by yoomlam** [comment] 2020-05-05 13:41
BEFORE|AFTER PR
 ---|---
<img width="722" alt="image" src="https://user-images.githubusercontent.com/55255674/81072228-77484c00-8eab-11ea-9ac3-87d7a17176cb.png"> (blank screen; unhandled error in devtools) | <img width="1226" alt="image" src="https://user-images.githubusercontent.com/55255674/81072035-27698500-8eab-11ea-8167-615ff54d1f3f.png">

**Comment by hschallhorn** [comment] 2020-05-05 20:38
Based on the [breadcrumbs](https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/8849/?referrer=webhooks_plugin) of these alerts it looks like this could be a stale link the user has bookmarked?
Clicking the link on the judge assign page|Modifying the url
---|---
![Screen Shot 2020-05-05 at 4 28 57 PM](https://user-images.githubusercontent.com/45575454/81113212-dcbd2c80-8eed-11ea-83ac-e68e70279516.png)|![Screen Shot 2020-05-05 at 4 29 13 PM](https://user-images.githubusercontent.com/45575454/81113238-e777c180-8eed-11ea-9c84-02ff689a185f.png)

```diff
+ 88
+ tasks?user_id=3&role=Judge
+ 3
+ users?role=Attorney
+ users?role=Attorney&judge_id=3
+ BVAAABSHIRE
88?role=judge
tasks?user_id=88&role=attorney
BVAEERDMAN?role=judge
```

**Comment by jcq** [comment] 2020-05-05 20:43
> @jcq Can you describe how I can replicate the error you described as:
> 
> > it is preventing me from loading the case assignment page mentioned in that sentry alert.

Sorry, missed this until now. That said, it looks like Yoom identified the issue in the intervening time, as your before/after shots demonstrate. The "before" shot shows the issue I encountered as that user.

**Comment by hschallhorn** [comment] 2020-05-05 21:06
I agree that we should handle this more gracefully, but I'm not sure the judge being unable to access this page is a concern. The attorney is not on their team, so they should not be able to see the attorney's cases.

**Comment by yoomlam** [comment] 2020-05-05 21:31
My PR will restrict judges from viewing other judge's assign queue.  Once we enable the CM (case movement) feature flag (`:scm_view_judge_assign_queue`), then CM users will be able to view any judge's assign queue.

Ann-Marie sent a note to the Board noting that we are fixing the bug (judge's being able to see other JudgeTeam's assign queue).

[complete convo](https://dsva.slack.com/archives/CJL810329/p1588713796284300?thread_ts=1588711468.282100&cid=CJL810329)

**Comment by hschallhorn** [comment] 2020-05-05 21:35
I didn't realize these were related. W confirmed that a judge viewing another judge's queue is what is causing the error? I don't have any errors showing in this scenario
### Random attorney viewing a judge assign queue with `scm_view_judge_assign_queue` turned off (as it is in production)
![Screen Shot 2020-05-05 at 5 33 34 PM](https://user-images.githubusercontent.com/45575454/81118296-a33cef00-8ef6-11ea-9192-a3ef2abeeaaf.png)
### Random attorney viewing an attorney's queue within a judge assigmn queue with `scm_view_judge_assign_queue` turned off (as it is in production)
![Screen Shot 2020-05-05 at 5 33 47 PM](https://user-images.githubusercontent.com/45575454/81118295-a33cef00-8ef6-11ea-98e4-8d8f097c9783.png)

**Comment by yoomlam** [comment] 2020-05-05 22:08
I was able recreate error by logging in as judges as described in [prior comment](https://github.com/department-of-veterans-affairs/caseflow/issues/12999#issuecomment-623727624). I did not test when logged in as an attorney.

So back on the master, I'll test as an attorney.
Logging in as `BVASCASPER1` (who is in JudgeTeam `BVAOSCHOWALT`), I go to 
http://localhost:3000/queue/BVAGSPORER/assign/92 and get the 403 status from the `tasks_controller` but the page is not blank:
<img width="909" alt="image" src="https://user-images.githubusercontent.com/55255674/81120341-1f810380-8ef2-11ea-9701-e3379ad0a60d.png">

When I go to http://localhost:3000/queue/BVAAABSHIRE/assign/92, I don't get the 403 status, but the page is blank:
<img width="1243" alt="image" src="https://user-images.githubusercontent.com/55255674/81120768-fb71f200-8ef2-11ea-8e59-d4173e4bb1e0.png">

Feature flag `scm_view_judge_assign_queue` is not active:
<img width="921" alt="image" src="https://user-images.githubusercontent.com/55255674/81120395-3f182c00-8ef2-11ea-9a0a-537258d61394.png">

**Comment by yoomlam** [comment] 2020-05-06 01:05
Updated error message:

 BEFORE|AFTER
 ---|---
<img width="722" alt="image" src="https://user-images.githubusercontent.com/55255674/81072228-77484c00-8eab-11ea-9ac3-87d7a17176cb.png"> (blank screen; unhandled error in devtools) | <img width="1159" alt="image" src="https://user-images.githubusercontent.com/55255674/81129474-07b57980-8f0a-11ea-81f1-250f71d91ebd.png"> (Atty 92 is not part of BVAAABSHIRE's JudgeTeam), <img width="994" alt="image" src="https://user-images.githubusercontent.com/55255674/81129529-3df2f900-8f0a-11ea-8ba2-f853018e6bdc.png"> (Atty 92 is part of BVAGSPORER's JudgeTeam, which BVAAABSHIRE is not a part of)

**Closed** 2020-05-08 20:51 UTC
Labels: Priority: Low, Product: caseflow-queue, Source: Sentry Alert, Stakeholder: BVA, Team: Echo 🐬
