### ISSUE TITLE
Search | Delay search execution

### ISSUE THREAD

**Issue by abbyraskin** [department-of-veterans-affairs/caseflow#1201] opened 2017-03-14 21:53 UTC
**Current**
The application currently sends a search query after every keypress, which sometimes creates a jumpy experience for users.

**Expected**
Only trigger the search after:
 - A user stops typing (1-2 second delay)
-  A user presses return on their keyboard
-  A user presses the blue search icon next to the search field

**Comment by NickHeiner** [comment] 2017-05-02 15:26
@mdbenjam can we chat about this? I'd like to know more about the problem we're trying to solve.

**Comment by tejans24** [comment] 2017-05-12 19:37
The searching in the application is really slow because of the amount of redux store updates being made. 
When a store has a lot of documents, every time a reducer returns a new state by performing a shallow-copy of the store, the app feels much slower and clunky.

Few ways to fix the problem:
* Don't update the store as frequently (use component state)
* Look into immutability js

**Comment by NickHeiner** [comment] 2017-05-12 22:33
After an in-person discussion, we are going to close this for now. It is better to address the root cause with #1983.

**Closed by NickHeiner** 2017-05-12 22:33 UTC
Labels: bug, caseflow-reader, In Progress, whiskey
