### ISSUE TITLE
DUPLICATE | UAT | Caseworker | Canceling EP results in unexpected page

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow#1288] opened 2017-03-22 15:13 UTC
**Description:**
Currently as a caseworker in Dispatch UAT, if you cancel an EP during its creation, after you receive the cancelation confirmation page and try to establish the next claim in the queue, you are taken to a page that only says "{"next_task_id":1187}".

**Expectation:** Caseworker is directed to their next task in the queue.

**Environment found:** UAT
**Browser found:** FF and Chrome

**Steps to Recreate:**
1. Go to Dispatch as a caseworker in UAT and start establishing an EP.
2. On the Review Decision page, select the cancelation button.
3. When the cancelation modal is shown, give an appropriate explanation.
4. After the Cancelation confirmation page is shown, select the establish next claim button.
5. Verify that the page the caseworker is taken to, matches the screenshot posted below. 

**Screenshots:**
<img width="1096" alt="screen shot 2017-03-22 at 11 08 55 am" src="https://cloud.githubusercontent.com/assets/23038505/24205054/aebdae84-0ef0-11e7-8a4b-7f6d48c262a9.png">

**Related Issues/Stories:**

**Reported By:** Alexis Stewart

**Comment by kierachell** [comment] 2017-03-23 00:54
duplicate of #1238

**Closed** 2017-04-06 17:38 UTC
