### ISSUE TITLE
Fix ratings call when there are zero ratings

### ISSUE THREAD

**Issue by kahlouie** [department-of-veterans-affairs/caseflow#6326] opened 2018-07-24 17:18 UTC
NoMethodError: undefined method `[]' for nil:NilClass
	from app/models/rating.rb:65:in `ratings_from_bgs_response'
	from app/models/rating.rb:46:in `fetch_timely'
	from app/models/veteran.rb:104:in `timely_ratings'
	from (irb):27

**Comment by abbyraskinUSDS** [comment] 2018-07-25 19:12
Is this now a duplicate of #5868?

**Comment by kahlouie** [comment] 2018-07-25 20:10
This is slightly different in that it is how we're failing on the backend when there are no ratings. This is the fix to not require ratings at all. The other is about adding a user friendly error message when there are no ratings. I believe if this is fixed, the #5868 won't be needed. @leikkisa is that correct?

**Comment by abbyraskinUSDS** [comment] 2018-07-25 20:13
OK - it sounds like this is the one that needs to take priority then? Or can we combine them?

**Comment by abbyraskinUSDS** [comment] 2018-07-25 21:11
Cool, i'm going to close this one out - I copied the backend error into the other ticket (#5868)

**Closed** 2018-07-25 21:12 UTC
Labels: Ready for Dev, caseflow-intake, sierra
