### ISSUE TITLE
Styleguide Component | Document Preview

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow#1010] opened 2017-02-24 13:22 UTC
[WIP]
For reader, we took out the option to print and download because we want to refrain users from doing so. We also learned from research that users were printing and downloading as a workaround for working from home or working offline. 

1. Do we want to add options for printing and downloading or do we want our products biased against doing so? 
1. It looks like right now on Dispatch and Certification, we only need a zoom and page number option. Should we create two versions of a doc viewer and keep the reader version separate?
1. Are there any other missing tools?

**Story**
As a user, I want to know the options that are available for me on a document viewer.

As a developer, I want to know how document previews should look like so they are consistent across all caseflow apps. 

### Reader

![image](https://cloud.githubusercontent.com/assets/13420618/25458319/794f4dfc-2aa7-11e7-923b-b36d299c332d.png)

### Dispatch

**_Notes this is for dispatch but the viewer on certification is very similar_**

**Reader version** 
![image](https://cloud.githubusercontent.com/assets/13420618/25459490/768dd05c-2aac-11e7-96f1-20a8fd6b50c4.png)

Lighter version (no bottom tool bar)
![image](https://cloud.githubusercontent.com/assets/13420618/25460096/bc14cbe6-2aaf-11e7-9153-1632c59a5a58.png)

Document name and page can probably be flipped in this view if consistency with reader is not a priority. 

## AC Draft
- There is a toolbar at the top and bottom of document viewer (height 40px)
- Users should have the ability to jump to a page by editing the page number out of total pages
- Users should be able to zoom (in, out and fit to page).
- Users should have the option to open the document in a different tab (depending on the product)
- Users should have the option to go back to a previous page if necessary (for reader)

This is affected by this:
https://github.com/department-of-veterans-affairs/caseflow/issues/773

**Comment by gnakm** [comment] 2017-03-06 16:09
Copy:

Document Preview (all caps)

Caseflow often pulls documents from other systems and displays them to users so that they don’t have to use multiple applications to accomplish their work. We display these documents in a preview pane over a dark grey background to make documents (which are often mostly white) jump out. The document preview usually takes up the same width as a normal white container (`918px`) so that the page contents stay aligned. This also gives a large and easy to read viewport for the user.

**Comment by shellicious** [comment] 2017-04-27 13:59
I like the lighter version for Certification @gnakm!

**Comment by lakohl** [comment] 2017-06-23 16:35
@gnakm I think this might be a duplicate of what we discussed in our design mtg yesterday

**Comment by gnakm** [comment] 2018-03-22 15:12
Closing this. Currently we have two types of document viewers -- one for Reader, one for Certification. From discussions, there isn't a need to make them the same because there are different use cases for each.

**Closed by gnakm** 2018-03-22 15:12 UTC
Labels: Triage, feature-definition, styleguide
