### ISSUE TITLE
VLJ Support: Task auto-distribution discrepancy 

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14084] opened 2020-04-24 13:35 UTC
## User or job story
VLJ Support's task assignments are distributed in a round robin fashion to ensure tasks are evenly distributed among the team. There appears to be an issue with the distribution logic as the tasks are not being evenly distributed at this time. 

## Acceptance criteria
- [ ] VLJ Support tasks are distributed equally among the team

### Background/context
Issue was flagged by the Deputy Branch Chief Veteran Law Judge Support Branch

### Technical notes
Investigation: https://hackmd.io/@hschallh/rJyoSPJYL

**Comment by yoomlam** [comment] 2020-04-30 17:19
https://github.com/department-of-veterans-affairs/caseflow/wiki/Automatic-Task-Distribution#vlj-support-round-robin

**Comment by ajspotts** [comment] 2020-04-30 17:20
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |
3 | |||||||
5 | ||||
8 | 
```

#### Why 2?
- Investigation optimism

#### Why 3?
- Time for investigation (same reasons as 5)

#### Why 5?
- Investigation uncertainty
- Commit to the time to make sure we fix the problem

**Comment by lomky** [comment] 2020-05-12 15:35
[Investigation complete](https://hackmd.io/@lomky/S1enY7_9I)

 - The very low number of tasksonly shows up for Admin users, who are assigned manually. These results can be disregarded as the auto-distribution applies to non-admin members of the team
 - The bug is traced back to how we re-architectued putting tasks on timed holds.
    - The VLJ Support round robin is based off of the generic `Task` class, as we want to account for both `ColocatedTask`s and `MailTasks` assigned to the team.
    - However, when we migrated timed holds from being _on_ a task to being their own task type, they _also_ appear if you query `Task` without any extra checks
    - **Fix:** confirm that our query analyzing who was most recently assigned a task to pick thte next person _does not consider_ 'user invisible' tasks, such as `TimedHoldTask`s

**Comment by lomky** [comment] 2020-05-12 15:46
The other consumer of the RoundRobin logic is BvaDispatch, however they explicitly look for `BvaDispatchTask` and are thus unaffected by this bug

**Comment by lomky** [comment] 2020-05-12 21:08
@araposo-tistatech The fix for this is merged and will go out tomorrow! 

I suggest we keep this issue open for another week or two and keep an eye on tasks assigned moving forward to watch for any other potential issues.

**Comment by araposo-tistatech** [comment] 2020-05-18 20:30
@lomky unfortunately, the VLJ Support team has reported that this issue has not been resolved. Please see their findings below: 

"It appears that the work distribution issue for VLJ Support has not been resolved.  Please see below chart which shows the amount of work assigned to each employee during the period of May 9 through May 16,  2020.  I pulled this information from Tableau because we are not able to get a clear/accurate number from the VLJ Work Queue.  I am hopeful that your team will be able to correct this issue to ensure that work is being distributed evenly.  Any assistance you can provide with getting this corrected is much appreciated.  Please note that Tirza Austin-Jenkins departed the Board on May 8th and she was given admin rights at the end of April so that she would not receive any additional work that she couldn’t complete.

Employee Name | Legacy Tableau View | AMA Tableau View |  
-- | -- | -- | --
Bergeron, Ronald | 49 | 17 |  
Clanton, Lazette | 42 | 24 |  
Crews, Tashauna | 25 | 8 |  
Drayton, Maleka | 49 | 14 |  
Jenkins, Michael | 9 | 2 |  
Johnson, Andre | 39 | 12 |  
Jones, Maurice | 33 | 9 |  
Koroma, Marvin | 26 | 13 |  
Lewis, Lofrandra | 42 | 8 |  
Maiden, Linda | 28 | 11 |  
Marshall, Patrice | 40 | 3 |  
Moss, Andrea | 30 | 9 |  
Seay, Randy | 31 | 9 |  
Totten-Browning, Pam | 38 | 9 |  
Wiggins, Gwen | 37 | 7 |  
Tirza-Austin-Jenkins | 3 | 0 |  
Totals | 512 | 153 | 665
"

I realize it is probably very unlikely, but is it possible that the data in Tableau could be off?

**Comment by yoomlam** [comment] 2020-05-18 22:47
@araposo-tistatech My 2 cents: I wouldn't expect the numbers to even out immediately since cases that have already been assigned (before the fix) will stay with the current assignee.

**Comment by araposo-tistatech** [comment] 2020-05-19 12:36
@yoomlam appreciate the input! I've gone back to VLJ Support with your note and will await feedback.

**Comment by hschallhorn** [comment] 2020-05-19 18:20
>  Please note that Tirza Austin-Jenkins departed the Board on May 8th and she was given admin rights at the end of April so that she would not receive any additional work that she couldn’t complete.

We should direct them to make this user inactive in caseflow rather than making them an admin. This will ensure they are not assigned any more tasks, but the correct way

**Comment by lomky** [comment] 2020-05-19 18:50
@araposo-tistatech The round robin is now working as intended:

```
# Gather all the Tasks assigned the VLJ Support in the past 6 days
> org_tasks = Task.where(assigned_to: Colocated.singleton, created_at: 6.days.ago..Time.zone.now)
# Gather all the individual user tasks assigned to members of VLJ Support under those Org Tasks
>  tasks = ColocatedTask.where(parent: org_tasks, assigned_to_type: User.name, created_at: 6.days.ago..Time.zone.now) 
# How many tasks?
> tasks.count

**Comment by araposo-tistatech** [comment] 2020-06-04 14:01
Maria from the VLJ support team got back to us stating two users (Lazette Clanton & Ronald Bergeron) are still receiving more tasks then other users. Below is the report she provided (May 25th - June 3rd): 

![Legacy Task Table](https://user-images.githubusercontent.com/59883609/83766008-daafd000-a649-11ea-8bdb-d2d507106f47.jpg)
![AMA Task Table](https://user-images.githubusercontent.com/59883609/83766014-db486680-a649-11ea-8f77-5314e1938ba8.jpg)

Based on the previous note Kat provided it does appear the tasks are being distributed evenly. Can we pull an updated report to ensure nothing has changed? I suspect the discrepancy is some users are completing their tasks faster than others, but I would like to present some data when I respond.

**Closed** 2023-04-25 15:48 UTC
Labels: Type: Investigation, Product: caseflow-queue, Type: Bug, Feature: generic-queue, Stakeholder: BVA, Team: Echo 🐬, release-notes, Priority: Medium
