### ISSUE TITLE
End Product: Decision Type determines "Modifier" based on "EP & Claim Label"

### ISSUE THREAD

**Issue by kierachell** [department-of-veterans-affairs/caseflow#652] opened 2017-01-09 20:40 UTC
As a Caseworker, I would like to have the "Modifier" value determined by the "Decision Type" selected on the Decision Review page and cannot be edited so that it reduces the chance of user error.

## Acceptance Criteria
1. Verify that the when the value of _"Decision Type"_ is "Full Grant" on the Decision Review page, the _"Modifier"_ value set to "172" corresponding to "EP & Claim Label" value of "172BVAG - BVA Grant" on the End Product page (refer to mockup).
1. Verify that the when the value of _"Decision Type"_ is "Partial Grant" on the Decision Review page, the _"Modifier"_ value is set to "170 corresponding to "EP & Claim Label" value of "170PGAMC - AMC-Partial Grant" on the End Product page.
1. Verify that the when the value of _"Decision Type"_ is "Remand"on the Decision Review page, the _"Modifier"_ value is set to "170" corresponding to "EP & Claim Label" value of "170RMDAMC - AMC-Remand" on the End Product page.
1. Verify that the _"Modifier"_ field cannot be edited and grayed out. **for now!**

# Current Functionality
**_View - Decision Review Page - Decision Type Selected_**
<img width="457" alt="screen shot 2017-01-09 at 13 01 43" src="https://cloud.githubusercontent.com/assets/18075411/21782361/276adb84-d681-11e6-9fb4-73d1b7ce4737.png">

**_View - End Product Page - Modifier_**
<img width="459" alt="screen shot 2017-01-09 at 15 31 38" src="https://cloud.githubusercontent.com/assets/18075411/21782364/29766380-d681-11e6-9359-bd955189e220.png">
<img width="451" alt="screen shot 2017-01-09 at 15 31 52" src="https://cloud.githubusercontent.com/assets/18075411/21782365/298a9fee-d681-11e6-986e-0c221692539a.png">

Just make it the same as EP & Claim Label works right now. Later, the 170 value will be editable (but not 172).

# Related Stories
Decision Review: Add "Decision Type" dropdown and prepopulated from VACOLS #624 
End Product: Decision Type determines EP & Claim Label #623

**Comment by kierachell** [comment] 2017-01-10 00:23
@lakohl If you have clarifications on the specifications, feel free to edit the issue.

**Comment by mdbenjam** [comment] 2017-01-13 16:09
This is a duplicate of https://github.com/department-of-veterans-affairs/caseflow/issues/622

**Closed by mdbenjam** 2017-01-13 16:09 UTC
Labels: caseflow-dispatch, In Progress
