### ISSUE TITLE
BSE 65146 - Capability for Caseflow to Support Non-Veteran Payees

### ISSUE THREAD

**Issue by tomjadams87** [department-of-veterans-affairs/caseflow#14846] opened 2020-07-31 20:06 UTC
## User or job story
User story: As a [user], I need [x], so that [y]
Job story: When a [user] does [x], they need [y], so that [z]

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by alisan16** [comment] 2020-07-31 22:36
Closing as this is a duplicate of https://github.com/department-of-veterans-affairs/caseflow/issues/11997

**Closed by alisan16** 2020-07-31 22:36 UTC
