### ISSUE TITLE
Fix date bug in form 8

### ISSUE THREAD

**Issue by maryannbrody** [department-of-veterans-affairs/caseflow#573] opened 2016-02-01 15:55 UTC
@paultag I think this one's for you, but feel free to re-assign. 

During usability testing, there was a bug in the way dates displayed in IE9 for all users (displayed: aN/aN/aNaN) (they were not getting automatically pulled in from VACOLS as they should.)

LMK if you need a screen shot!!

**Comment by paultag** [comment] 2016-02-01 20:29
Dupe of #558 - let's roll with 558

**Closed by paultag** 2016-02-01 20:29 UTC
