### ISSUE TITLE
[Frontend] | 'Last Saved At' not updating

### ISSUE THREAD

**Issue by sharonwarner** [department-of-veterans-affairs/caseflow#4663] opened 2018-02-16 18:14 UTC
AC:
- 'Last Saved At' time stamps update on the hearing worksheet and the daily docket after a save successfully completes.

**Comment by lakohl** [comment] 2018-02-16 21:55
I think this might be a duplicate of #4660

**Comment by lakohl** [comment] 2018-03-17 00:03
Is currently updating every minute. Thumbs up!

**Closed by lakohl** 2018-03-17 00:03 UTC
Labels: In-Validation, bug-medium-priority, caseflow-hearing-prep, tango
