### ISSUE TITLE
Create progress bar

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#1116] opened 2017-03-06 20:57 UTC
Note that the current mock shows 4 steps, but at this point we want it to only show 3 steps. "Confirm Case Details" will not be in the progress bar yet since we won't have built it.

**Comment by shanear** [comment] 2017-03-07 13:58
Is this a duplicate of: https://github.com/department-of-veterans-affairs/caseflow/issues/835?

**Comment by amprokop** [comment] 2017-03-07 16:12
yep, closing

**Closed** 2017-03-07 16:12 UTC
