### ISSUE TITLE
Asynchronous Claims | Resolution Time Reduction and Reporting 

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13444] opened 2020-02-18 14:57 UTC
## Background/context
In an effort to calculate ROI and properly account for issue resolution time as it relates to 'Asynchronous Claims', the Caseflow team is task with depicting and and highlighting progression via a stakeholder report. 

**Report Content**
_In Progress_
- Async Error Name
- Time between error creation and resolution
- Calculation of total time to resolve over one month
- Historical monthly resolution time 

## Goals
Over a period of time, issues relating to 'asynchronous claims' must show a monthly gradual reduction with regards to resolution time. 

## Success criteria
[to be added]

## Stakeholders
AMO

## Requirements/stories

- As an AMO stakeholder, I have access to view and edit the 'async resolution time' report available. 
- As an AMO stakeholder, I can export the 'async resolution time' report in csv format. 

## Open questions
-  Calculation for total resolution time in one month time frame

**Comment by leikkisa** [comment] 2020-06-26 01:14
I'm closing this as a dupe of #13338, I moved some of the info above about reporting to that epic. A weekly report is being produced and presented to the stakeholders.

**Closed by leikkisa** 2020-06-26 01:14 UTC
Labels: Epic, Priority: Low, Product: caseflow-intake, Source: AMO Reported, Stakeholder: AMO, Team: Foxtrot 🦊, User: VBA Intake
