### ISSUE TITLE
Field VSOs

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#8961] opened 2019-01-25 20:52 UTC
## AC
- Only all cases view
- No actioning on tasks
- Only `TrackVeteran` task (exclude from Case timeline)
- Create field VSO organizations

**Comment by lowellrex** [comment] 2019-02-26 16:27
Closing this one out as a duplicate of #9647 since the new ticket adds a little more information about approach.

**Closed by lowellrex** 2019-02-26 16:27 UTC
Labels: In-Progress, caseflow-queue, foxtrot, vso
