### ISSUE TITLE
BVA Cases index page does not filter correctly

### ISSUE THREAD

**Issue by wdrougas-tista** [department-of-veterans-affairs/caseflow#15716] opened 2020-12-21 15:20 UTC
Users are presented with the option to sort BVA cases by "<<blank>>" Type in Queue. When selecting the filter, no cases are presented

![Screen Shot 2020-12-21 at 10.16.19 AM.png](https://images.zenhubusercontent.com/5e976ddfed689a8dc52aee6c/5ed28f42-b699-4290-869e-d20c0778ea87)

![Screen Shot 2020-12-21 at 10.16.27 AM.png](https://images.zenhubusercontent.com/5e976ddfed689a8dc52aee6c/9df25f5c-f59a-45c0-9cab-9e440521c490)

**Comment by hschallhorn** [comment] 2020-12-21 16:26
Dupe of https://github.com/department-of-veterans-affairs/caseflow/issues/12129!

**Comment by wdrougas-tista** [comment] 2020-12-21 16:28
Thanks @hschallhorn ! I'll close this out

**Closed** 2020-12-21 16:28 UTC
Labels: Product: caseflow-queue, Type: Tech-Improvement
