### ISSUE TITLE
Refactor to use DB id of certification, not VACOLS id for routes and searches

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow#465] opened 2016-11-18 18:00 UTC
Our routing scheme currently relies on the VACOLS id. We should instead use the certification db id.

So, instead of  `certifications/new/VACOLS_ID`, it would be `certifications/new/CERTIFICATION_DB_ID`.

 We should accompany this refactor with changes to eliminate the querying of form8s and certifications based on their vacols id.

**Comment by nickheiner-usds** [comment] 2017-11-13 20:07
This seems like a duplicate of #431.

Also:

This ticket is old, and we haven't done it yet, so I'm going to close it. Please re-open the ticket if you think this should be prioritized.

![image](https://user-images.githubusercontent.com/25331532/32746623-3b303344-c884-11e7-97ef-7be8d527fb78.png)

**Closed by nickheiner-usds** 2017-11-13 20:07 UTC
Labels: tech-improvement, Tech-Improvement-Backlog
