### ISSUE TITLE
Canceled/Deleted Appeals Still Showing In User Queues

### ISSUE THREAD

**Issue by araposo-tistatech** [department-of-veterans-affairs/caseflow#14219] opened 2020-05-07 16:39 UTC
## User or job story
Job story: When intake deletes (cancels by removing all issues) an appeal the appeal should no longer display as needing to be worked in a VLJ or Attorneys queue. Also, if you search for a Veterans cases using their Veteran ID and not the docket ID, etc. The cancelled appeal should still display in the search results. 

### Background/context
There appears to be inconsistencies with deleted (canceled) appeals. Per the Board, some appeals do appear as canceled; however, some appeals disappear completely, while other appeals that have been deleted, were later discovered not to be deleted at all. 

### Technical notes
Examples provided by the Board: 
https://appeals.cf.ds.va.gov/queue/appeals/08f8d0da-2937-4022-a184-1e9050f9956a - Deleted appeal was still active in Attorneys queue. 

https://appeals.cf.ds.va.gov/queue/appeals/e9f08767-9ecb-447e-92a1-b10c304f7ca9 - Deleted appeal was still active in Attorneys queue. 

https://appeals.cf.ds.va.gov/queue/appeals/5a3c20c5-eb38-42ac-9278-ac600f94d4ec - Completely disappeared from Caseflow after it was deleted. (I looked into this myself and I want to specify that the user is searching using the Veterans ID and the deleted appeal does not display in the cases found list) 

https://appeals.cf.ds.va.gov/search?veteran_ids=421632 - Deleted appeal (cancelled one) is not displaying in search results.

**Comment by hschallhorn** [comment] 2020-05-07 17:49
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | |||||||
5 | 
8 | 
```

Cancelled appeals should not appear in a user's queue.

Out of scope of this ticket: Search. Assure the cancelled appeals showing up in search results is unchanged

#### Why 2?
- If able to reproduce, should be an easy fix
- since this applies to any sort of cancelled appeals, should be straightforward

#### Why 3?
- Because this seems to be working for the majority of instances, might be a tougher bug to track down (removing all issues cancels all open tasks, cancelled tasks do not show up in users queues)

**Comment by lomky** [comment] 2020-06-26 14:06
I am unable to recreate this situation. My hypothesis is we have either solved this problem as a part of some other fix, or that the users were expected another tab with their Queue to reload automatically (it does not).

[Investigation Notes](https://hackmd.io/kgFGE_J8TtugddC1SN0PpA?edit)

**Closed** 2020-06-26 20:50 UTC
Labels: Priority: Medium, Product: caseflow-queue, Stakeholder: BVA, Team: Echo 🐬, Type: Bug, Type: Investigation
