### ISSUE TITLE
Correctly display dispatched from Board date in case timeline

### ISSUE THREAD

**Issue by lowellrex** [department-of-veterans-affairs/caseflow#8938] opened 2019-01-25 00:55 UTC
Currently we do not show the date when an appeal was dispatched from the Board in case timeline. We [correctly change the text](https://github.com/department-of-veterans-affairs/caseflow/blob/2fb7b02db05e3fe2854e75a6232d19dcfc46f3aa/client/app/queue/components/TaskRows.jsx#L212), but we do not show the date the decision was dispatched nor do we show the green dot indicating that the decision has been dispatched.

![image](https://user-images.githubusercontent.com/32683958/51717226-170efd00-200e-11e9-9f76-4acb9d5f289f.png)

## Acceptance criteria
* [ ] Show a green instead of grey dot if the decision has been dispatched from the Board
* [ ] Show the date the decision was dispatched from the Board if it has been

**Comment by laurjpeterson** [comment] 2019-02-20 21:58
Closing, because I created a duplicate of this ticket (whoops) and the other one has related support tickets attached to it - https://github.com/department-of-veterans-affairs/caseflow/issues/9511

**Closed by laurjpeterson** 2019-02-20 21:58 UTC
Labels: case-details, case-timeline, caseflow-queue, foxtrot
