### ISSUE TITLE
Intake fails to recognize is_unidentified flag

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#10985] opened 2019-06-03 18:39 UTC
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/5265/events/359989/

Prelim investigation shows that the payload being sent from the Javascript browser side does not include the `is_unidentified` boolean flag, and so the `decision_text` is not being saved on the request issue.

From the AWS logs

dsva-appeals-certification-prod/opt/caseflow-certification/src/log/caseflow-certification.out i-0c920f201c4433b59 [appeals.cf.ds.va.gov] [a5320e07-f125-480e-bfca-3f89cc312924] [172.xxxxxx] [VRCJBRIT2318 xxx] [2019-06-03 11:17:03 -0400]

```
Parameters: {"request_issues"=>[
{"decision_text"=>"After a review of this information it was decided that feasibility of a vocational goal is currently undetermined.  [redacted for brevity]", 
"vacols_id"=>nil, "vacols_sequence_id"=>nil, "withdrawal_date"=>nil}], 
"1559575024017"=>nil, "id"=>"181726"}
```

**Comment by aroltsch** [comment] 2019-08-14 18:00
I think I should manually set these two request issues to be unidentified.  

![image](https://user-images.githubusercontent.com/3811786/63044267-dab4c880-be9b-11e9-9b5b-993f9bb681dd.png)

**Comment by aroltsch** [comment] 2019-08-15 12:29
1. Add a validation check in RequestIssue that confirms the issue is explicitly rating, nonrating or is_unidentified.
1. Update these 8 issues in production to unidentified
1. Add data integrity job to catch cases in the future

**Comment by aroltsch** [comment] 2019-09-10 17:57
Closing in favor of https://github.com/department-of-veterans-affairs/caseflow/issues/12032

**Closed by aroltsch** 2019-09-10 17:57 UTC
Labels: bug-high-priority, caseflow-intake, foxtrot, sentry-alert
