### ISSUE TITLE
HTTPClient::ReceiveTimeoutError

### ISSUE THREAD

**Issue by mmlumba** [department-of-veterans-affairs/caseflow#3567] opened 2017-10-11 14:54 UTC
### Reader job sometimes times out, but succeeds on retry

```
FetchDocumentsForReaderUserJob (user_id: 983) ERROR. Retrieved 0 / 4 appeals

2017-11-13T04:34:08Z 3268 TID-gmxyp0848 ActiveJob/FetchDocumentsForReaderUserJob/caseflow_prod_low_priority/cb1231f0-9cb7-4aea-8ec2-9dd04ac0debc INFO: Message cb1231f0-9cb7-4aea-8ec2-9dd04ac0debc failed, will be retried in 300 seconds
```

Associated BFKEYS: - '2874129','2971872','3577962','3623187'

> HTTPClient::ReceiveTimeoutError: execution expired
app/services/external_api/efolder_service.rb in block in get_efolder_response at line 49

```
    MetricsService.record("eFolder GET request to #{url}",
                          service: :efolder,
                          name: endpoint) do
      HTTPI.get(request)
```
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/470/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/579/
https://sentry.ds.va.gov/department-of-veterans-affairs/caseflow/issues/540/

- Subsequent retry succeeded:
```
[2017-11-12 23:39:44 -0500] FetchDocumentsForReaderUserJob (user_id: 983) SUCCESS. Retrieved 4 / 4 appeals
```

### Do we need these in Sentry?
- What is actionable here?
- Retry logic seems to handle this fine.
- Should we rely on watching the dead letter queue for real problems?

**Comment by nickheiner-usds** [comment] 2017-11-09 20:16
[Sample error trace in NR](https://rpm.newrelic.com/accounts/1788458/applications/80608544/filterable_errors#/show/e4c479ae-c54e-11e7-8afe-0242ac110009_0_21886/stack_trace?top_facet=transactionUiName&primary_facet=error.class&barchart=barchart&filters=%5B%7B%22key%22%3A%22error.class%22%2C%22value%22%3A%22HTTPClient%3A%3AReceiveTimeoutError%22%2C%22like%22%3Afalse%7D%5D&_k=b34317)

[List of errors in NR](https://rpm.newrelic.com/accounts/1788458/applications/80608544/traced_errors/e4c479ae-c54e-11e7-8afe-0242ac110009_0_21886/similar_errors?original_error_id=e4c479ae-c54e-11e7-8afe-0242ac110009_0_21886)

**Comment by sunil-sadasivan** [comment] 2017-11-13 16:11
Thanks for the file here.  For now these can be muted.  

I'll be thinking of the right solution here, created a ticket here:
https://github.com/department-of-veterans-affairs/caseflow/issues/3905

**Comment by mdbenjam** [comment] 2017-11-30 15:31
Pretty sure this is a duplicate of https://github.com/department-of-veterans-affairs/caseflow/issues/3163. Closing in favor of that ticket.

**Closed by mdbenjam** 2017-11-30 15:31 UTC
Labels: caseflow-reader, Current-Sprint, prod-alert, whiskey
