### ISSUE TITLE
Attorney Fees | Specify issue category as ‘Attorney Fees’ 

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13807] opened 2020-03-27 03:44 UTC
## User or job story
As a BVA Intake user, I need the ability to specify issue category as ‘Attorney Fees’ in the Intake workflow

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [attorney_fees]
- [ ] This feature should be accessible to the following user groups: 
- [ ] the 'contested claims (other than apportionment)' issue category should be replaced with the issue categories displayed below
> Contested Claim 
- [ ] Update documentation: [link]

### [Designs](https://github.com/department-of-veterans-affairs/caseflow/issues/13745)

![image](https://user-images.githubusercontent.com/41164406/80404916-e3b1c280-888f-11ea-866b-fab593e66917.png)

### Background/context

Prior Caseflow design accounted for the addition of 'Contested Claims' and as a result the issue categories, 'Apportionment' and 'Contested Claims - other than apportionment' .  In this requirement, BVA would like to be able to specify 'attorney fees'. Based on prior research 'attorney fees' is a sub category of 'Contested Claims - other than apportionment'. 
![image](https://user-images.githubusercontent.com/41164406/76896456-34350980-6868-11ea-9c56-5cf44cb09add.png)

**Comment by leikkisa** [comment] 2020-05-28 15:31
@nanotone I think this is a dupe of #14137 and is in [Sandra's PR](https://github.com/department-of-veterans-affairs/caseflow/pull/14227).

**Comment by leikkisa** [comment] 2020-07-08 14:47
Closing as a dupe

**Closed by leikkisa** 2020-07-08 14:47 UTC
Labels: Eng: Backend Work Group, Eng: Frontend Work Group, Product: caseflow-intake, Stakeholder: BVA, Team: Foxtrot 🦊, Type: New Development, User: BVA Intake
