### ISSUE TITLE
Amount of whitespace between form questions is inconsistent

### ISSUE THREAD

**Issue by alex** [department-of-veterans-affairs/caseflow#383] opened 2015-12-14 20:16 UTC
<img width="790" alt="screen shot 2015-12-14 at 3 15 37 pm" src="https://cloud.githubusercontent.com/assets/772/11792737/997af75e-a275-11e5-9496-91aa6d23692b.png">

**Comment by webinista** [comment] 2015-12-14 23:06
Duplicate of #241

**Closed by webinista** 2015-12-14 23:06 UTC
Labels: design, frontend
