### ISSUE TITLE
EXPECTED DEC 9: WSCR request to open up DocumentService in Prod

### ISSUE THREAD

**Issue by leikkisa** [department-of-veterans-affairs/caseflow#7199] opened 2018-10-01 17:54 UTC
# Story
We added DocumentService to ruby-bgs, and so it's likely that it is not available in BGS prod. So we need to submit the WSCR service request to make it available in Prod.

I am not sure what all this entails, but here is some information that might be useful:
Git version number: 2d0e08ea4157b725242777a6f876fc199f503b61
Pull request: https://github.com/department-of-veterans-affairs/ruby-bgs/pull/66

**Comment by shanear** [comment] 2018-10-01 23:14
@nikitarockz should be able to help you out with this.

**Comment by mc-usds** [comment] 2018-10-05 20:00
Had a call with John regarding access to DocumentService. He said that Caseflow has access to the service on the Internal domain, but not the External domain.

I thought we were using the Internal domain and the only time we were going to the External domain was when we made calls to VBMS. If direct calls are going to Internal domain, we should have access. 

I'm not sure why my test call was failing in preprod, I will retry. John is going to ask one of the devs to check the Tuxedo transactions and verify which domain direct calls are going to. I'll follow up with them on Tuesday.

**Comment by leikkisa** [comment] 2018-10-08 17:42
Hmm, this doesn't make sense to me because it should be using the same URL as the rest of ruby-bgs (I'm guessing the internal domain).

Maybe he's confusing giving access with turning the service on.

**Comment by mc-usds** [comment] 2018-10-09 16:30
I followed up with John today. I'm reiterated that we are using the internal domain for direct calls to BGS and asked if the service is "on" in the domain. Waiting to hear back from their end.

**Comment by mc-usds** [comment] 2018-10-12 22:37
DocumentService was not available in preprod because MapD was not deployed to the internal domain. That was deployed and now the call in preprod is working. My understanding is that service is already deployed in prod, but when I tested, the call is still failing. I'm following up with John to find out what else needs to be done for prod to work.

**Comment by mc-usds** [comment] 2018-10-15 14:49
Had a call with John this morning and learned a couple more things. Baseline is the term for the build deployed. MapD is a legacy application that has the functionality for developing a claim (contentions, tracked items...and stuff). John confirmed that the Mapd baseline 11752 is deployed to Prod internal domain. He has asked a developer Nain Hwu to investigate further.

**Comment by mc-usds** [comment] 2018-10-15 16:08
Had another call with John. The dev found out that DocumentService is not deployed to Prod internal domain. It can be deployed in the Dec CI. There is no Nov CI, if we would like to have the DocumentService deployed before Dec CI, we will need to escalate. 

Additional learning: The BGS team (John's team) does not have access to Production. There is a webpage that they look at to see what has been installed to each domain. The webpage determines what is "installed" by looking to see if certain files exist in certain directories. The webpage is showing that the DocumentService is "installed" and that is incorrect.

**Comment by mc-usds** [comment] 2018-10-18 22:19
Plot twist. DocumentService was removed from preprod.

Prod ETA is still Dec CI

**Comment by shanear** [comment] 2018-10-19 15:47
> Plot twist. DocumentService was removed from preprod.

lol. I love this movie

**Comment by steve-gov** [comment] 2019-01-04 01:11
@mc-usds How would you recommend testing that this exists and works in production?

**Comment by leikkisa** [comment] 2019-01-04 01:48
@steve-gov I added a find_claimant_letters(document_id) on DocumentService just in case we thought it'd be useful. I tried it on Prod and on UAT and it's working for me on UAT, but I believe it's not working on prod.  I'm getting a "Not found" error. Let me know if you want to see the detailed version.

**Comment by mc-usds** [comment] 2019-01-04 18:18
I get this error in pre-prod. I wasn't seeing this before, I will reach out to BGS:

</env:Header><env:Body><tns:findClaimantLetters><documentId>12345</documentId></tns:findClaimantLetters></env:Body></env:Envelope>
D, [2019-01-04T13:13:13.291805 #345] DEBUG -- : HTTPI /peer POST request to bepprep.vba.va.gov (httpclient)
I, [2019-01-04T13:13:14.265016 #345]  INFO -- : SOAP response (status 500)
D, [2019-01-04T13:13:14.265087 #345] DEBUG -- : <?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><S:Fault xmlns:ns4="http://www.w3.org/2003/05/soap-envelope"><faultcode>S:Server</faultcode><faultstring>An application error has occurred which does not have a descriptive message to display for error code 936, please contact your System Administrator.</faultstring><detail><ns2:BenefitsException xmlns:ns2="http://services.mapd.benefits.vba.va.gov/"><message>An application error has occurred which does not have a descriptive message to display for error code 936, please contact your System Administrator.</message></ns2:BenefitsException></detail></S:Fault></S:Body></S:Envelope>
Traceback (most recent call last):
        1: from (irb):9
Savon::SOAPFault ((S:Server) An application error has occurred which does not have a descriptive message to display for error code 936, please contact your System Administrator.)

**Comment by leikkisa** [comment] 2019-01-04 22:55
@mc-usds When a document didn't exist in UAT, I got the same error that you posted above. But in Prod, I think that the whole service isn't available yet.

@steve-gov the find_claimant_letters call uses the same service, but the nice thing about it is that it's read-only (so we don't have to actually generate a tracked item to see if the service is available).
<img width="1042" alt="screen shot 2019-01-03 at 5 45 39 pm" src="https://user-images.githubusercontent.com/6589610/50715147-b0ab4600-1030-11e9-8692-b4b5da1e0936.png">

**Comment by mc-usds** [comment] 2019-01-04 23:13
D'oooooooh

**Comment by mc-usds** [comment] 2019-01-07 20:41
Nain Hwu (Weblogic server team) confirmed that the DocumentService was not deployed to the Prod Internal domain. 

Seeing if it can be deployed as part of the deployment this weekend.

**Comment by mc-usds** [comment] 2019-01-08 15:40
Had a call this morning. Found out that the DocumentService was only partially deployed to the prod internal domain. 

Created an Incident: INC3803441
https://yourit.va.gov/nav_to.do?uri=%2Fincident.do%3Fsys_id%3Dded84f72dbba2b48356a7e0e0f96194d%26sysparm_view%3Dess%26sysparm_record_target%3Dincident%26sysparm_record_row%3D1%26sysparm_record_rows%3D1%26sysparm_record_list%3Dcaller_id%253Djavascript%253Ags.getUserID%2528%2529%255Eactive%253Dtrue%255EORDERBYDESCwork_start

**Comment by mc-usds** [comment] 2019-01-08 16:31
Updated from Michael Simpson (BGS team): 
CO525848FY19  has been updated with Incident and scheduled for maintenance window this weekend (during CI). 

Change Order: CO525848FY19
https://vaww.nsd.va.gov/CAisd/pdmweb.exe?OP=SEARCH+FACTORY=chg+SKIPLIST=1+QBE.EQ.id=953005

**Comment by mc-usds** [comment] 2019-01-15 17:02
Tested in prod. No more 404 errors. I'm not sure if this is the expected response though.

irb(main):007:0> BGSService.new.find_claimant_letters(717228)
[2019-01-15 11:57:30 -0500] STARTED BGS: find claimant letter for document 717228
D, [2019-01-15T11:57:30.997066 #3990] DEBUG -- : HTTPI /peer GET request to localhost (httpclient)
I, [2019-01-15T11:57:31.192807 #3990]  INFO -- : SOAP request: https://bepprod.vba.va.gov/DocumentService/DocumentService
I, [2019-01-15T11:57:31.192859 #3990]  INFO -- : Host: bepprod.vba.va.gov, SOAPAction: "findClaimantLetters", Content-Type: text/xml;charset=UTF-8, Content-Length: 898
D, [2019-01-15T11:57:31.192892 #3990] DEBUG -- : <?xml version="1.0" encoding="UTF-8"?><env:Envelope xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:tns="http://services.mapd.benefits.vba.va.gov/" xmlns:env="http://schemas.xmlsoap.org/soap/envelope/"><env:Header>  <wsse:Security xmlns:wsse="http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd">
    <wsse:UsernameToken>
      <wsse:Username>CSFLOW</wsse:Username>
    </wsse:UsernameToken>
    <vaws:VaServiceHeaders xmlns:vaws="http://vbawebservices.vba.va.gov/vawss">
      <vaws:CLIENT_MACHINE>10.236.66.134</vaws:CLIENT_MACHINE>
      <vaws:STN_ID>283</vaws:STN_ID>
      <vaws:applicationName>CASEFLOW</vaws:applicationName>
    </vaws:VaServiceHeaders>
  </wsse:Security>
</env:Header><env:Body><tns:findClaimantLetters><documentId>717228</documentId></tns:findClaimantLetters></env:Body></env:Envelope>
D, [2019-01-15T11:57:31.193115 #3990] DEBUG -- : HTTPI /peer POST request to bepprod.vba.va.gov (httpclient)
I, [2019-01-15T11:57:32.146110 #3990]  INFO -- : SOAP response (status 200)
D, [2019-01-15T11:57:32.146173 #3990] DEBUG -- : <?xml version='1.0' encoding='UTF-8'?><S:Envelope xmlns:S="http://schemas.xmlsoap.org/soap/envelope/"><S:Body><ns2:findClaimantLettersResponse xmlns:ns2="http://services.mapd.benefits.vba.va.gov/"/></S:Body></S:Envelope>
[2019-01-15 11:57:32 -0500] FINISHED BGS: find claimant letter for document 717228:   0.006171   0.006465   0.012636 (  1.151317)

**Comment by leikkisa** [comment] 2019-01-15 23:31
That's not a real document ID in prod so it's probably good.

**Comment by shanear** [comment] 2019-01-22 21:30
good enough for me. we'll close this one and reopen it if we see something else

**Closed by shanear** 2019-01-22 21:30 UTC
Labels: In-Validation, caseflow-intake, sierra
