### ISSUE TITLE
Form 8:  Question skipping from Q7 to Q9

### ISSUE THREAD

**Issue by shellicious** [department-of-veterans-affairs/caseflow#478] opened 2016-11-21 17:53 UTC
DRO from Waco was unable to answer question 8 on Form 8, to report that a veteran had a private attorney, because form 8 skipped from Q7 to Q9. Unfortunately, he was not able to provide more detail. We should try to replicate this error. If we can't, we should close this issue, as it was only reported once.

**Comment by amprokop** [comment] 2016-12-05 17:58
Have we verified this? If we have, can we add that info in the issue? If not, can we verify it before it goes into the current sprint? Not sure this is really "Ready for dev"

**Comment by nikitarockz** [comment] 2016-12-19 16:13
I have tried to reproduce this issue in the demo environment, but I am unable to reproduce it.  I vote we close this ticket.  @shellicious

**Comment by shellicious** [comment] 2016-12-19 16:23
I'm ok closing it @nikitarockz, thanks for trying to reproduce it.

**Closed** 2016-12-19 18:39 UTC
Labels: bug, caseflow-certification, foxtrot, Ready for Dev
