### ISSUE TITLE
BSE 66139 - Capability to Create Separate Contentions for Effective Date and Evaluation Level

### ISSUE THREAD

**Issue by tomjadams87** [department-of-veterans-affairs/caseflow#14848] opened 2020-07-31 20:08 UTC
BSE   66139 - Capability to Create Separate Contentions for Effective Date and Evaluation Level

## User or job story
User story: As a [user], I need [x], so that [y]
Job story: When a [user] does [x], they need [y], so that [z]

## Acceptance criteria
- [ ] Please put this work behind the feature toggle: [toggle name]
- [ ] This feature should be accessible to the following user groups:
- [ ] Include screenshot(s) in the Github issue if there are front-end changes
- [ ] Update documentation: [link]

**Comment by alisan16** [comment] 2020-07-31 22:37
Closing as this is a duplicate of https://github.com/department-of-veterans-affairs/caseflow/issues/12383
@tomjadams87 remember to search through existing issues before creating an issue so we are only tracking work in one place for each item and we don't need to sort through duplicates.

**Closed by alisan16** 2020-07-31 22:37 UTC
