### ISSUE TITLE
Attorney check out | Enter issue dispositions

### ISSUE THREAD

**Issue by laurjpeterson** [department-of-veterans-affairs/caseflow#4471] opened 2018-01-26 19:08 UTC
When an attorney is checking out a draft decision, they need to update each issue disposition on the appeal, so that the judge knows the appeals draft outcome.

### Acceptance Criteria
- [ ] Verify that there are the following table headers: "Issues", "Actions", "Dispositions" in bold
- [ ] Verify that the issue display under the issues header in the following hierarchy: 
   - Program
   - Issue
   - Levels 1-3 (i.e. 5237 - Lumbosacral or cervical strain
   - Notes (if there)
- [ ] Verify that underneath the "Action" label there is a link that says "Edit issue" that opens the "Edit issue" page
- [ ] Verify that underneath the "Dispositions" label there is a dropdown labeled "Select Disposition" 
   - Attorney can select a disposition for each issue:
      - "1" => "Allowed",
      - "3" => "Remanded",
      - "4" => "Denied",
      - "5" => "Vacated",
      - "6" => "Dismissed, Other",
      - "8" => "Dismissed, Death",
      - "9" => "Withdrawn",
   - Issue dispositions update in VACOLS
- [ ] If attorney selects 'Vacated', another check box appears with copy "Vacate and readjudicate this issue. Automatically duplicate vacated issue."
- [ ] If attorney selects that checkbox, verify that the issue is duplicated in VACOLS
    - From Jed: "If an attorney selects disposition 5-Vacate the prompt above displays, if they answer ‘Yes’ it will duplicate the vacated issue with a null disposition."
- [ ] Verify that at the end of the last issue there is a link called "Add issue" that opens the "Add issue" page
- [ ] Verify that at the bottom left of the app canvas there is a link that navigates the user back a page with the following format < Go back to [page title of previous page]
- [ ] Verify that there is a button to the bottom right of the App Canvas that says "Finish dispositions"
- [ ] Verify that the user cannot advance to the next screen unless all issues have dispositions filled out.

### Style guide components (top to bottom)
- Header
- App Canvas
- Table (w/o lines)
- Dropdown
- Primary button 
- Footer 

### Mocks and Specs
Title: Header
Body styling: Body
Spacing should following existing Queue specs for table and ticket
#### Default
![select disposition](https://user-images.githubusercontent.com/23316107/37414828-6b6d6b2a-2780-11e8-8841-47ae9b6b2608.png)

#### Default if choosing from the drop down
_If Review Draft Decision was selected there is no point in sending them back to the ticket view. Wasn't sure if this was clear in the mocks, so adding a specific placeholder for it_
![select disposition table](https://user-images.githubusercontent.com/23316107/37414892-9013d0b8-2780-11e8-97a4-e5e96a1945c4.png)

#### Dropdown 
![select disposition - dropdown](https://user-images.githubusercontent.com/23316107/37414840-711aea66-2780-11e8-863a-bcccdc8c8774.png)

#### Vacate disposition selected
![select disposition - vacate](https://user-images.githubusercontent.com/23316107/37414848-7759106a-2780-11e8-8d48-7657df7f1edc.png)

### Related issues
#4472 Edit Issue 
#4477 Add Issue

**Comment by Chingujo** [comment] 2018-01-29 13:48
A.C. details added and mock uploaded

**Comment by laurjpeterson** [comment] 2018-02-05 17:30
@Chingujo made some updates. I think we need better copy for the vacate box - let me know what you think.

**Comment by amprokop** [comment] 2018-03-14 15:03
Going to add a few tweaks here.

![image](https://user-images.githubusercontent.com/3781835/37410470-1920c5be-2777-11e8-8039-6e626c5ed5e6.png)

The AC said the default dropdown text should be "Select Dispositions". Each dropdown selects only one disposition. I've adjusted the AC to say "Select Disposition" for the default dropdown text.

**Comment by amprokop** [comment] 2018-03-14 15:14
Some more navigation w

![dispos](https://user-images.githubusercontent.com/3781835/37410995-212587da-2778-11e8-8aaf-af227b22901d.gif)

- When navigating forward and backward in the flow, the top breadcrumbs are duplicated
- When using the browser back button, disposition values are not saved in React state (this may have not been implemented yet, sorry if this is just forthcoming and not a bug!)

**Comment by Chingujo** [comment] 2018-03-14 15:55
@dannysellers @amprokop 

The mocks and ac are updated with the following changes: 
- [ ] "Go back to draft decision" has been replaced with "Go back to [Veteran name] following the 
<Go back to [page title of previous page] pattern
 - < Back to Vera Marshall (22222222)

- [ ] The bolding and the indent right on the diagnostic is correct see [Displaying Issues](https://github.com/department-of-veterans-affairs/appeals-design-research/issues/684)

**Comment by dannysellers** [comment] 2018-03-23 18:45
Phillip and Alex—I added these changes to #4847, gonna close this issue 👍

**Closed by dannysellers** 2018-03-23 18:45 UTC
Labels: In-Validation, caseflow-queue, foxtrot

**Comment by laurjpeterson** [comment] 2018-09-18 19:35
Note: We were asked to remove disposition 6 "Dismissed, Other".
