### ISSUE TITLE
Hearing Worksheet | update efolder to claims folder

### ISSUE THREAD

**Issue by annienguyenUSDS** [department-of-veterans-affairs/caseflow#4532] opened 2018-02-02 19:55 UTC
**Story:** to be more consistent with content and Reader, we are moving from eFolder to Claims Folder.

**AC:** 
- On the Hearing Worksheet, update "Docs in eFolder: 400" to "Docs in Claims Folder: 400"
- On the Hearing Worksheet, update "Review eFolder" button to "Review claims folder" button. (lower case)

**Comment by sharonwarner** [comment] 2018-02-13 22:01
Duplicate of #4228

**Closed** 2018-02-13 22:01 UTC
Labels: Current-Sprint, caseflow-hearing-prep, tango
