### ISSUE TITLE
Facilitate Lane Switching | Ability to Edit Specific Intake Field | Docket Date

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13796] opened 2020-03-25 23:00 UTC
## Request 
The ability for certain BVA users to edit specific intake fields

o	change the docket date

**Justification**
Lane switching scenario justification for ability to edit docket change: 

Veterans can choose an appeal lane, but can change their mind at any time; Caseflow should always honor the original docket date (i.e. the very first time the 10182 was submitted) each time a lane change happens. 
 - Can the Caseflow team either build/support the above, or provide the ability to edit the docket date to specific users (i.e. the Board’s Intake team)? 

## Open questions
- Would there be instances where if we honored the original docket dates, human error would still require us to provide the ability to edit.?

**Comment by RebeccaBaumTT** [comment] 2020-07-20 22:27
This is a duplicate of two other tickets Docket 13978 and NOD 11128

**Closed** 2020-07-20 22:26 UTC
Labels: Epic, Priority: Low, Product: caseflow-intake, Source: BVA Reported, Stakeholder: BVA, Team: Foxtrot 🦊, Type: Enhancement, User: BVA Intake
