### ISSUE TITLE
Facilitate Lane Switching | Ability to Edit Specific Intake Field | Receipt Date

### ISSUE THREAD

**Issue by msj0nes** [department-of-veterans-affairs/caseflow#13090] opened 2020-01-05 20:31 UTC
## Request 
The ability for certain BVA users to edit specific intake fields
o	change the receipt date

**Justification**
Lane switching scenario justification for ability to edit docket change: 

Veterans can choose an appeal lane, but can change their mind at any time; Caseflow should always honor the original docket date (i.e. the very first time the 10182 was submitted) each time a lane change happens. 
 - Can the Caseflow team either build/support the above, or provide the ability to edit the docket date to specific users (i.e. the Board’s Intake team)? 

## Open questions
- Would there be instances where if we honored the original docket dates, human error would still require us to provide the ability to edit.?

**Comment by leikkisa** [comment] 2020-01-28 21:57
Slack conversation about implementation details and questions:
https://dsva.slack.com/archives/CFBLH2LR4/p1579883108011900

**Comment by leikkisa** [comment] 2020-06-26 01:26
I believe this is a duplicate of two other things that now have epics:
- [Ability to change docket type](https://github.com/department-of-veterans-affairs/caseflow/issues/13978)
- [Ability to change NOD receipt date](https://github.com/department-of-veterans-affairs/caseflow/issues/11128)

I copied some of the info above and am closing this ticket.

**Closed by leikkisa** 2020-06-26 01:26 UTC
Labels: Epic, Priority: Low, Product: caseflow-intake, Source: BVA Reported, Stakeholder: AMO, Stakeholder: BVA, Team: Foxtrot 🦊, User: BVA Intake
