### ISSUE TITLE
Identify problem with or collect information on RoundRobin Automatic Task Assignments 

### ISSUE THREAD

**Issue by lomky** [department-of-veterans-affairs/caseflow#14629] opened 2020-06-30 20:02 UTC
## Description
We are seeing unexpectedly unbalanced distribution of tasks from the round robin assignment of VLJ support tasks. We want to collect what is actually happening in order to correct this.

## Data we would like to capture
 - Org Task generating the assignment
 - user task being assigned
 - appeal
 - assignee_pool 
 - last task being used to generate the last assignee
 - the next_assignee we will use

## Background/context/resources
[Investigation](https://dsva.slack.com/archives/CJL810329/p1593528787348700)
* [HackMD notes](https://hackmd.io/vFZVGBb_SaqseVeZTIP48Q?both)

## Technical notes
- [RoundRobin code](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/round_robin_task_distributor.rb)
- [VLJ Support Overrides](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/colocated_task_distributor.rb)
 - [Invocation](https://github.com/department-of-veterans-affairs/caseflow/blob/master/app/models/task.rb#L604)

**Comment by yoomlam** [comment] 2020-07-02 17:17
_[what is this chart?](https://github.com/department-of-veterans-affairs/caseflow/issues/11533)_
```bash
1 | 
2 | |||||
3 | ||||
5 | 
8 | 
```

Current algorithm only uses the last assignment made.
Want to know what the algorithm's state is with each restart.

Implement as a rails log 
- Use a greppable string
- Consider appropriate format

#### Why 2?
* Straightforward work

#### Why 3?
* Consideration to do it thoughfully so we don't miss data

**Comment by yoomlam** [comment] 2020-08-07 16:06
Created PR #14897 for adding logging but we won't need to merge it.
I identified 2 root causes for the `RoundRobinTaskDistributor` not working as expected for the Colocated Team. When a task is created and assigned to this team, it a new (duplicate) child task that is assigned to a team member (i.e., a `User` from the `assignee_pool`): 
https://github.com/department-of-veterans-affairs/caseflow/blob/79907ddecbbb746be25e917c442189e1521e7763/app/models/task.rb#L604-L612
because `automatically_assign_org_task?` returns true for the `Colocated` org:
https://github.com/department-of-veterans-affairs/caseflow/blob/79907ddecbbb746be25e917c442189e1521e7763/app/models/task.rb#L614-L616

The root causes occur when assigning this new child task:
- If there exists an open task assigned to a user in the `assignee_pool`, then the distributor assigns the new task to that user (this is desired behavior): https://github.com/department-of-veterans-affairs/caseflow/blob/79907ddecbbb746be25e917c442189e1521e7763/app/models/colocated_task_distributor.rb#L10-L22
- End-user manually reassigned a (Colocated) task to user in the `assignee_pool`. Reassigning a task cancels the task and creates a _new_ task assigned to the new user.

These cause the `latest_task` to change, which causes `last_assignee` to jump/skip from the expected round-robin ordering. 
https://github.com/department-of-veterans-affairs/caseflow/blob/e5d5df6207ede8d00ef1a95bd3c0a1bbade9e418/app/models/round_robin_task_distributor.rb#L22-L36

These 2 causes (plus new Collocated members being added) explain the [4531 task assignments made between May 15th and Aug 5th](https://docs.google.com/spreadsheets/d/11Y5cmt79VeoTGrlqEj4fk_HUJMTNKd5Fah8PIuNO5fM/edit?usp=sharing).  I could not explain 2 assignments having task IDs 1011751 and 1071485. Notes about the spreadsheet:
* purple text indicates mismatches (i.e., task assignment did not match expected round-robin ordering)
* yellow highlight indicates when that user was added to the Colocated Team
* pink highlight indicates unexplained mismatch

See [hackMD](https://hackmd.io/0ekslnh7RAaoimlXVcDzGQ?edit) for detailed notes, but here's how to create the spreadsheet:
```ruby
# Kat's code fix was made on May 12th, so start in mid-May
interval = DateTime.new(2020,5,15,0,0,0)..DateTime.new(2020,8,5,0,0,0)
assignee_pool = Colocated.singleton.non_admins.sort_by(&:id);
assignee_ids = assignee_pool.pluck(:id);
# this will make it easier to tell if assignment is out of order
pool=assignee_pool.each_with_index.map {|a,i| [a.id,i]}.to_h;
assigned_tasks = Task.visible_in_queue_table_view.where(assigned_to: assignee_ids, created_at: interval).order(:id);
require 'csv'
CSV.open( 'rr.csv', 'w' ) do |writer|
  counter=pool[assigned_tasks.first.assigned_to_id]
  pool_size=assignee_pool.size
  match_list = assigned_tasks.map{|t| 
    # does assignee match round-robin ordering
    match = (counter % pool_size) == pool[t.assigned_to_id]
    # what the next assignee should be
    counter = pool[t.assigned_to_id] + 1
    # count of tasks that were closed at (almost) the same time this task was created; captures task reassignment
    closed_count = t.appeal.tasks.order(:id).where(closed_at: (t.created_at-0.5)..(t.created_at+0.5)).count
    # are there prior tasks in this appeal assigned to the same assignee?
    prior_task = t.appeal.tasks.order(:id).where(assigned_to_id: t.assigned_to_id).where('created_at < ?', t.created_at).last
    writer << [ pool[t.assigned_to_id], match, closed_count, t.id, prior_task&.id, t.created_at ]
  };  
end
```

**Comment by hschallhorn** [comment] 2020-08-10 14:25
Replaced with #14914

**Closed by hschallhorn** 2020-08-10 14:25 UTC
Labels: Priority: Medium, Product: caseflow-queue, Source: User Feedback, Stakeholder: BVA, Team: Echo 🐬, Type: Metrics or Reporting
