### ISSUE TITLE
Closed tasks being re-opened

### ISSUE THREAD

**Issue by pkarman** [department-of-veterans-affairs/caseflow#12274] opened 2019-10-02 00:55 UTC
Investigation into bug surfaced in #12157

Steps to follow:

* `tasks = Task.open.where.not(closed_at: nil)`
* `pp tasks.sort_by(&:updated_at).map { |t| t.versions.first }`

Seems to be a lot of RootTask and HearingTask going from `completed` or `cancelled` to `on_hold`.

Definitely happening as a result of user interaction with the app, not via manual engineer clean up.

## Acceptance criteria
* [ ] Determine why closed tasks are being re-opened
* [ ] Prevent TrackVeteranTask creation from re-opening closed appeals #12574

**Comment by hschallhorn** [comment] 2019-10-03 19:45
There have been 24 reopened tasks in 2 weeks

**Comment by kevmo** [comment] 2019-10-03 19:47
1 |
2 |
3 | ||||||
5 | |||||
8 | |

3. This is a distressing ticket that needs to get fixed, somewhat irrespective of level of effort.  In the event that a fix is not found after 2-3 points worth of effort, implement an alert.

**Comment by lowellrex** [comment] 2019-10-31 15:57
## [In progress] Investigation notes:

When were these tasks that were re-opened closed?
[_Source: Looker_](https://caseflow-looker.va.gov/sql/dxhk6j3pkvfvtp) (31 October 2019)
![image](https://user-images.githubusercontent.com/32683958/67962632-bda6b080-fbd3-11e9-9688-ff28852edbd5.png)
Looks like two main clusters, October and June of this year.
* Possible avenues for further exploration:
    * Precise `closed_at` dates
    * Investigate the solo buddies because it may be easier to determine what happened to the oddballs here.

Let's look at when they were most recently updated to see if there is a trend there:
[_Source: Looker_](https://caseflow-looker.va.gov/sql/k42jcys2nwx7ps) (31 October 2019)
![image](https://user-images.githubusercontent.com/32683958/67963065-605f2f00-fbd4-11e9-896a-b8fc42c050e6.png)
Only this month and last. Let's get more specific!

[_Source: Looker_](https://caseflow-looker.va.gov/sql/txsgfhbtjyj7mh) (31 October 2019)
![image](https://user-images.githubusercontent.com/32683958/67963421-f5fabe80-fbd4-11e9-8a7f-f3caebe72229.png)
Spread out on a bunch of different dates. Intriguing!

Let's take a look at what type these tasks have.
[_Source: Looker_](https://caseflow-looker.va.gov/sql/nqvwds424cp5yd) (31 October 2019)
![image](https://user-images.githubusercontent.com/32683958/67963556-2cd0d480-fbd5-11e9-8383-f47550fb890d.png)
Interesting. Let's dive deeper into one of the more recent tasks affected by this bug.

[_Source: Looker_](https://caseflow-looker.va.gov/sql/4myh9xhbtg5xr8) (31 October 2019)
![image](https://user-images.githubusercontent.com/32683958/67963732-73263380-fbd5-11e9-91df-a9f47cacac33.png)
Does not look like the tasks were affected by the same event. Let's dive in!

TODO: Return to investigating a single task affected by this issue after the break!

**Comment by lowellrex** [comment] 2019-11-04 16:39
Spun one ticket out of this one to address a specific scenario where new `TrackVeteranTask`s are re-opening `RootTask`s (#12574)

**Comment by lowellrex** [comment] 2019-11-04 17:46
I propose finishing this ticket by taking the following two actions:
* [ ] Writing a data integrity checker that notifies us whenever we have a task with a value in the `closed_at` field that is not actually closed, so that we can investigate closer to when the precipitating event occurs.
* [ ] Updating the status of the affected tasks in production.

@pkarman how does that sound to you?

**Comment by pkarman** [comment] 2019-11-04 18:40
there is already a data integrity checker for this. (it's how we know it's a problem.)

yes, manually fixing affected tasks is good.

are we confident we have stemmed the root cause?

**Comment by lowellrex** [comment] 2019-11-04 21:43
[Still investigating](https://docs.google.com/spreadsheets/d/1cUTMDbVBhe4We3rckb6QQ4lb3C0BKsfWXskJAOE8YwY/edit?usp=sharing) the remaining 11, but 58 of the 69 tasks with `closed_at` values that are not closed fall into 3 categories
* 13 `RootTask`s re-opened by new `TrackVeteranTask`s ([Looker](https://caseflow-looker.va.gov/sql/f4v3jd8ykqj6cf))
    * The root cause here is fixed by #12574
* 14 `RootTask`s re-opened by new `MailTask`s ([Looker](https://caseflow-looker.va.gov/sql/rxsj9x8cc45vfn))
    * The root cause here is fixed by #12574
* 31 `HearingTask`s re-opened by action being taken on open child `ScheduleHearingTask`s ([Looker](https://caseflow-looker.va.gov/sql/jcj2xywfkr5dbp))
    * It appears as if the parent `HearingTask` was closed for these appeals but the child `ScheduleHearingTask`s were not closed. Therefore when the hearing were scheduled (and the child task was closed), the parent task [was updated to `on_hold`](https://github.com/department-of-veterans-affairs/caseflow/blob/0984143c50af430785c640867c529bdec1d51eb2/app/models/task.rb#L444)

**Comment by lowellrex** [comment] 2019-11-07 16:48
Closed 239 `ScheduleHearingTask`s that should have been closed by the cancellation of their parent task in [an earlier cleanup this June](https://github.com/department-of-veterans-affairs/caseflow/issues/10630#issuecomment-550353088). This should prevent more `HearingTask`s from being re-opened.

[There are now 34 `HearingTask`s](https://caseflow-looker.va.gov/sql/rrwzqnk4gjrycp) with non-null `closed_at` values and closed child `ScheduleHearingTask`s. Let's tackle these one-by-one.
```ruby
  rails c> reopened_hearing_tasks = HearingTask.open.where.not(closed_at: nil)
  rails c> reopened_hearing_tasks.count
  # 34
  rails c> closed_child_schedule_tasks = ScheduleHearingTask.closed.where(parent_id: reopened_hearing_tasks.pluck(:id))
  rails c> closed_child_schedule_tasks.count
  # 34
  rails c> candidate_hearing_tasks = HearingTask.where(id: closed_child_schedule_tasks.pluck(:parent_id))
  rails c> candidate_hearing_tasks.count
  # 34
  # Maybe that was overly cautious. Oh well.
  # That means we can dig in more speedily though which is nice.
  rails c> puts reopened_hearing_tasks.first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # HearingTask 165398 actually look alright. Has two sibling HearingTasks.
  # It looks like they were all closed as roughly the same time and this is the one
  # that has the children tasks attached to it that should actually be worked on.
  # Removed the closed_at value so that it falls off this report.
  rails c> HearingTask.find(165398).update!(closed_at: nil)

  # Next task!
  rails c> puts reopened_hearing_tasks.first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # HearingTask 188981 has a child AssignHearingDispositionTask 505355 that is active.
  # This appeal has a completed AssignHearingDispositionTask 317282 so I suspect that
  # the appeal's hearing has already passed and had a disposition assigned to it.
  # Let's determine for sure if the hearing associated with AssignHearingDispositionTask
  # 505355 has passed.
  rails c> AssignHearingDispositionTask.find(505355).hearing.scheduled_for
  # Fri, 06 Dec 2019
  # Nope, it's in the future. Let's hold off on doing anything with this task until
  # we can confirm with the Tango team whether it is in an expected state or not.
  # TODO: Follow up on what should be happening here.

  # Next!
  rails c> puts reopened_hearing_tasks.second.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> AssignHearingDispositionTask.find(423633).hearing.scheduled_for
  # Thu, 07 Nov 2019 17:30:00 EST -05:00
  # Child AssignHearingDispositionTask 423633 is scheduled for the future. Let's clear
  # the closed_at value out of the parent HearingTask.
  rails c> HearingTask.find(189225).update!(closed_at: nil)

  # Next!
  rails c> puts reopened_hearing_tasks.second.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Two open HearingTasks with ScheduleHearingTask children. One of them resulted in
  # a hearing being scheduled. Let's close the other one since it is erroneously open.
  rails c> HearingTask.find(189774).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> ScheduleHearingTask.find(189775).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> puts HearingTask.find(189774).appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Looks good. Let's confirm that the hearing is still scheduled for the future.
  rails c> AssignHearingDispositionTask.find(506299).hearing.scheduled_for
  # Wed, 18 Dec 2019
  # Yup! Looks good!
  # Let's remove the closed_at timestamp from the properly open HearingTask.
  rails c> HearingTask.find(189772).update!(closed_at: nil)

  # How many do we have left?
  rails c> reopened_hearing_tasks = HearingTask.open.where.not(closed_at: nil)
  rails c> reopened_hearing_tasks.count
  # 31
```

Work in progress. Still need to:
* [ ] Finish up the remaining 31 tasks.
* [ ] Come back to HearingTask 188981 and figure out how to resolve that buddy.

**Comment by lowellrex** [comment] 2019-11-07 23:28
Including the 3 `HearingTask`s corrected above, we corrected the state of 33 `HearingTask`s. They fall into two categories:
1. Task tree is in correct state but `HearingTask` was reopened after incorrectly being closed so the `closed_at` value stuck around. These were corrected by updating the value of the `closed_at` field to `nil`. Fixed **14** appeals in this situation.
2. A hearing has been scheduled and has not yet occurred but a `ScheduleHearingTask` remains open because the cancelation did not cascade as expected (see [related ticket](https://github.com/department-of-veterans-affairs/caseflow/issues/10630#issuecomment-550353088)). These were corrected by cancelled the open scheduling task and null-ing out the `closed_at` value. Fixed **17** appeals in this situation.

14 and 17 only sum to 31 but that is because two appeals contained 2 open `HearingTask`s with non-null `closed_at` values.

```ruby
  rails c> HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).count
  # 30
  # As expected now that we're excluding the HearingTask that we're not handling yet.
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # One completed schedule hearing task
  rails c> AssignHearingDispositionTask.find(475369).hearing.scheduled_for
  # Mon, 13 Jan 2020
  # We can close the other schedule hearing task.
  rails c> ScheduleHearingTask.find(191415).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(191412).update!(closed_at: nil)

  # Next.
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Just need to update the closed_at value to null.
  rails c> HearingTask.find(191834).update!(closed_at: nil)

  # Next.
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Just need to update the closed_at value to null.
  rails c> HearingTask.find(192969).update!(closed_at: nil)

  # Next.
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Two HearingTasks. One looks like the hearing has been scheduled. Let's confirm.
  rails c> AssignHearingDispositionTask.find(438521).hearing.scheduled_for
  # Tue, 19 Nov 2019
  # Let's cancel the open ScheduleHearingTask for the other HearingTask
  rails c> ScheduleHearingTask.find(201592).update!(status: Constants.TASK_STATUSES.cancelled)
  # Clear the closed_at value for the open HearingTask
  rails c> HearingTask.find(201589).update!(closed_at: nil)

  # Next. 
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Just need to update the closed_at value to null.
  rails c> HearingTask.find(201613).update!(closed_at: nil)

  # I've got Andrew's attention. Let's figure out what to do with the case that
  # I've been delaying addressing.
  rails c> puts HearingTask.find(188981).appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Let's take a look at the hearing date of the associated hearing for the assign
  # disposition task that is still open. 
  rails c> AssignHearingDispositionTask.find(505355).hearing.scheduled_for
  # Fri, 06 Dec 2019
  rails c> AssignHearingDispositionTask.find(317282).hearing.scheduled_for
  # Fri, 20 Sep 2019
  rails c> AssignHearingDispositionTask.find(317282).hearing.disposition
  # "held"
  rails c> AssignHearingDispositionTask.find(317282).appeal.location_code
  # "CASEFLOW"
  # Offloaded determining how to handle this to Andrew
  # https://dsva.slack.com/archives/C3EAF3Q15/p1573164656173300

  # Next. 
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Let's see if the hearing is in the future. If it is close the open schedule task.
  rails c> AssignHearingDispositionTask.find(424436).hearing.scheduled_for
  # Tue, 10 Dec 2019
  rails c> ScheduleHearingTask.find(201649).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(201646).update!(closed_at: nil)

  # Next. How many do we have left?
  rails c> HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).count
  # 24
  # Alright! Let's keep chugging.
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Looks like the same situation.
  rails c> AssignHearingDispositionTask.find(480003).hearing.scheduled_for
  # Tue, 28 Jan 2020
  # Hearing has yet to occur. No need to schedule another hearing.
  rails c> ScheduleHearingTask.find(202748).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(202745).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Same again.
  rails c> AssignHearingDispositionTask.find(475350).hearing.scheduled_for
  # Mon, 13 Jan 2020
  # In the future. Let's cancel the task to schedule a new hearing.
  rails c> ScheduleHearingTask.find(204458).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(204455).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Only need to update the closed_at value here.
  rails c> HearingTask.find(205506).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Open schedule task when it looks like we already have a pending hearing.
  # Let's confirm.
  rails c> AssignHearingDispositionTask.find(493965).hearing.scheduled_for
  # Thu, 12 Dec 2019
  # Let's close the other scheduling task.
  rails c> ScheduleHearingTask.find(210598).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(210595).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Only need to update the closed_at value here.
  rails c> HearingTask.find(212634).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> AssignHearingDispositionTask.find(480216).hearing.scheduled_for
  # Tue, 28 Jan 2020
  rails c> ScheduleHearingTask.find(216895).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(216892).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> HearingTask.find(216901).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> AssignHearingDispositionTask.find(454524).hearing.scheduled_for
  # Tue, 10 Dec 2019
  rails c> ScheduleHearingTask.find(216915).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(216912).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> AssignHearingDispositionTask.find(452618).hearing.scheduled_for
  # Wed, 22 Jan 2020
  rails c> ScheduleHearingTask.find(217915).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(217912).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> HearingTask.find(218395).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> AssignHearingDispositionTask.find(500021).hearing.scheduled_for
  # Tue, 17 Dec 2019
  rails c> ScheduleHearingTask.find(220421).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(220418).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> HearingTask.find(220941).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> AssignHearingDispositionTask.find(435968).hearing.scheduled_for
  # Fri, 08 Nov 2019
  rails c> ScheduleHearingTask.find(224228).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(224225).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> AssignHearingDispositionTask.find(483104).hearing.scheduled_for
  # Fri, 22 Nov 2019
  rails c> ScheduleHearingTask.find(224502).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(224499).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> AssignHearingDispositionTask.find(452173).hearing.scheduled_for
  # Wed, 13 Nov 2019
  rails c> ScheduleHearingTask.find(230998).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(230995).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> AssignHearingDispositionTask.find(449869).hearing.scheduled_for
  # Wed, 13 Nov 2019
  rails c> ScheduleHearingTask.find(232063).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(232060).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> AssignHearingDispositionTask.find(491278).hearing.scheduled_for
  # Wed, 11 Dec 2019
  rails c> ScheduleHearingTask.find(232780).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(232777).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> AssignHearingDispositionTask.find(467423).hearing.scheduled_for
  # Mon, 16 Dec 2019
  rails c> ScheduleHearingTask.find(235520).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(235517).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> HearingTask.find(238305).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> HearingTask.find(238314).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> HearingTask.find(240790).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> HearingTask.find(240865).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> AssignHearingDispositionTask.find(494096).hearing.scheduled_for
  # Wed, 25 Mar 2020
  rails c> ScheduleHearingTask.find(242080).update!(status: Constants.TASK_STATUSES.cancelled)
  rails c> HearingTask.find(242077).update!(closed_at: nil)

  # Next!
  rails c> puts HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  rails c> HearingTask.find(244708).update!(closed_at: nil)

  rails c> HearingTask.open.where.not(closed_at: nil).where.not(id: 188981).count
  # 0
  # All done!
```

* [ ] Consult with Sal to determine what state task tree associated with `HearingTask` 188981 should be in ([related Slack thread](https://dsva.slack.com/archives/C3EAF3Q15/p1573164656173300))

**Comment by lowellrex** [comment] 2019-11-08 15:12
Closed 11 `RootTask`s re-opened by the `TrackVeteranTask`s

```ruby
  rails c> open_root_tasks_prev_closed = RootTask.open.where.not(closed_at: nil)
  rails c> open_root_tasks_prev_closed.count
  # 36
  # Got a bunch of these. Let's limit our scope to only those that were re-opened by
  # the addition of TrackVeteranTasks.
  rails c> tracking_tasks = TrackVeteranTask.open.where(parent_id: open_root_tasks_prev_closed.pluck(:id))
  rails c> tracking_tasks.count
  # 29
  # Our sql query expects only 14 (https://caseflow-looker.va.gov/sql/f4v3jd8ykqj6cf).
  # Let's start investigating!
  rails c> puts TrackVeteranTask.open.where(parent_id: RootTask.open.where.not(closed_at: nil).pluck(:id)).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # RootTask 185540 has an open VacateMotionMailTask attached to the appeal. Come back
  # to this case later. Seems more complex than the simple case we're trying to resolve
  # right now.

  rails c> puts TrackVeteranTask.open.where(parent_id: RootTask.open.where.not(closed_at: nil).where.not(id: 185540).pluck(:id)).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # RootTask 311638 looks like the simple case. Let's fix it.
  rails c> TrackVeteranTask.find(439596).update!(status: Constants.TASK_STATUSES.completed)
  # Didn't need to do it this way. Closing the RootTask would have closed the child
  # tracking task.
  # https://github.com/department-of-veterans-affairs/caseflow/blob/cb8f97e09f39105f08454e2d22eccd29797dd31d/app/models/tasks/root_task.rb#L29
  rails c> RootTask.find(311638).update!(status: Constants.TASK_STATUSES.completed)

  # Next
  rails c> puts TrackVeteranTask.open.where(parent_id: RootTask.open.where.not(closed_at: nil).where.not(id: 185540).pluck(:id)).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Open EvidenceOrArgumentMailTask created after RootTask 1102 was closed. Complex
  # case. Return to it later. Let's hone our query so that we're only getting appeals
  # with a single open tracking task.
  rails c> root_task_only_one_open_child_ids = Task.open.where(parent_id: RootTask.open.where.not(closed_at: nil).where.not(id: 185540).pluck(:id)).group(:parent_id).count.select { |id, cnt| cnt == 1 }.keys
  rails c> root_task_only_one_open_child_ids.count
  # 17

  rails c> puts TrackVeteranTask.open.where(parent_id: root_task_only_one_open_child_ids).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # RootTask's updated_at and the child TrackVeteranTask's opened_at timestamps match.
  # This is the simple case of a TrackVeteranTask re-opening a RootTask. Solved by
  # https://github.com/department-of-veterans-affairs/caseflow/issues/12574
  # Let's get this RootTask in the correct state.
  rails c> RootTask.find(293990).update!(status: Constants.TASK_STATUSES.completed)

  # Next.
  rails c> puts TrackVeteranTask.open.where(parent_id: root_task_only_one_open_child_ids).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Same simple case.
  rails c> RootTask.find(37014).update!(status: Constants.TASK_STATUSES.completed)

  # Next.
  rails c> puts TrackVeteranTask.open.where(parent_id: root_task_only_one_open_child_ids).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Same simple case.
  rails c> RootTask.find(181867).update!(status: Constants.TASK_STATUSES.completed)

  # Next.
  rails c> puts TrackVeteranTask.open.where(parent_id: root_task_only_one_open_child_ids).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Same simple case.
  rails c> RootTask.find(63591).update!(status: Constants.TASK_STATUSES.completed)

  # Next.
  rails c> puts TrackVeteranTask.open.where(parent_id: root_task_only_one_open_child_ids).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Same simple case.
  rails c> RootTask.find(1144).update!(status: Constants.TASK_STATUSES.completed)

  # Next.
  rails c> puts TrackVeteranTask.open.where(parent_id: root_task_only_one_open_child_ids).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Same simple case.
  rails c> RootTask.find(194553).update!(status: Constants.TASK_STATUSES.completed)

  # Next.
  rails c> puts TrackVeteranTask.open.where(parent_id: root_task_only_one_open_child_ids).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Same simple case.
  rails c> RootTask.find(127124).update!(status: Constants.TASK_STATUSES.completed)

  # Next.
  rails c> puts TrackVeteranTask.open.where(parent_id: root_task_only_one_open_child_ids).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Same simple case.
  rails c> RootTask.find(69404).update!(status: Constants.TASK_STATUSES.completed)

  # Next.
  rails c> puts TrackVeteranTask.open.where(parent_id: root_task_only_one_open_child_ids).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # MailTask 492761 re-opened this one but did not close it. The MailTask has since
  # been completed, but the RootTask (and a child TrackVeteranTask that was created
  # while this has been open) remain open. Let's close them
  rails c> RootTask.find(221891).update!(status: Constants.TASK_STATUSES.completed)

  # Next.
  rails c> puts TrackVeteranTask.open.where(parent_id: root_task_only_one_open_child_ids).first.appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Same simple case again.
  rails c> RootTask.find(358211).update!(status: Constants.TASK_STATUSES.completed)

  # All done!
  rails c> TrackVeteranTask.open.where(parent_id: root_task_only_one_open_child_ids).count
  # 0

  # Why did we count 17 RootTasks at the beginning but only update 11 in the simple case?
  # Let's look at the task trees for all 17.
  rails c> root_task_only_one_open_child_ids.each { |id| puts Task.find(id).appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at) }
  # Some of these RootTasks have 1 open child but that child is not a tracking task.
```

**Comment by lowellrex** [comment] 2019-11-12 15:41
Closed a re-opened `RootTask` and `TrackVeteranTask` previously missed:

```ruby
  rails c> task_id = 283885
  rails c> RootTask.find(task_id).appeal.location_code
  # "99"
  rails c> puts RootTask.find(task_id).appeal.structure_render(:id, :status, :created_at, :updated_at, :closed_at)
  # Just need to close out the parent RootTask here.
  rails c> RootTask.find(task_id).update!(status: Constants.TASK_STATUSES.cancelled)
```

And created a ticket to address active `HearingTask`s related to re-opened `RootTask`s: #12678.

**Comment by lowellrex** [comment] 2019-11-13 00:38
A [handful of tasks](https://caseflow-looker.va.gov/sql/hbbxrcvfbxkrhx) were incorrectly routed to Board teams when they should have raised ["Appeal is not active at the Board."](https://github.com/department-of-veterans-affairs/caseflow/blob/639a10bba1c0c4c70bedff37c04a8744dcf467aa/lib/caseflow/error.rb#L191) errors.

`MailTask`s have always been created [as the children of `RootTask`s](https://github.com/department-of-veterans-affairs/caseflow/blob/639a10bba1c0c4c70bedff37c04a8744dcf467aa/app/models/tasks/mail_task.rb#L47). Because of [the `Task.tell_parent_task_child_task_created` `after_create`](https://github.com/department-of-veterans-affairs/caseflow/blob/639a10bba1c0c4c70bedff37c04a8744dcf467aa/app/models/task.rb#L31) (and its predecessors), creating child `MailTask`s would change the parent `RootTask`'s status to `on_hold`. This was mostly harmless since when an AMA `Appeal` (the [only types of appeal](https://github.com/department-of-veterans-affairs/caseflow/blob/639a10bba1c0c4c70bedff37c04a8744dcf467aa/app/models/tasks/root_task.rb#L50) to which `MailTask`s can be attached) is active at the Board, we expect the `RootTask` to be on hold.

However, this behaviour resulted in `MailTask`s that were not [active at the Board](https://github.com/department-of-veterans-affairs/caseflow/blob/639a10bba1c0c4c70bedff37c04a8744dcf467aa/app/models/tasks/mail_task.rb#L76) never being identified as such since the [creation of the first child `MailTask`](https://github.com/department-of-veterans-affairs/caseflow/blob/639a10bba1c0c4c70bedff37c04a8744dcf467aa/app/models/tasks/mail_task.rb#L47) changes the status of the `RootTask` from `completed` to `on_hold`, ["activating" the case](https://github.com/department-of-veterans-affairs/caseflow/blob/639a10bba1c0c4c70bedff37c04a8744dcf467aa/app/models/appeal.rb#L152) and incorrectly routing the `MailTask` to a Board team instead of raising the aforementioned error.

This bug was fixed last week by [a PR that prevented closed `RootTask`s](https://github.com/department-of-veterans-affairs/caseflow/issues/12574) from being re-opened by child task creation.

I will follow up tomorrow with precise steps we can take to restore the task trees of appeals affected by this bug. We will likely communicate with the mail team and confirm that this correspondence should be routed to ROs instead of the Board and close these mail tasks, but I will follow up tomorrow.

In the event that Looker goes away tomorrow, I've included the query to determine which appeals (IDs 205, 680, 911, 1859, 2406, 3087, 3515, 6604, 9970, 10300) are in this situation below:

```sql
select rt.id root_task_id
, rt.type root_task_type
, rt.status root_task_status
, rt.updated_at root_task_updated_at
, rt.appeal_type
, rt.appeal_id
, mt.id mail_task_id
, mt.type mail_task_type
, mt.status mail_task_status
, mt.created_at mail_task_created_at
from tasks rt
inner join tasks mt
  on rt.appeal_type = mt.appeal_type
  and rt.appeal_id = mt.appeal_id
  and rt.type = 'RootTask'
  and rt.status not in ('completed', 'cancelled')
  and rt.closed_at is not null
  and mt.status not in ('completed', 'cancelled')
  and mt.type like '%MailTask'
order by root_task_id;
```

**Comment by lowellrex** [comment] 2019-11-13 15:47
There are now [fewer than 20 re-opened `RootTask`s](https://caseflow-looker.va.gov/sql/msnpwyngkhfbjb). These fall into two main categories:

* `MailTask`s that were incorrectly routed to Board teams when they should have been sent to ROs. We are waiting to hear back from @jimruggiero before closing these errantly opened tasks are closed (https://dsva.slack.com/archives/CJL810329/p1573655233027400).
* `LegacyAppeal`s in VACOLS location 99 (closed) with closed `RootTask`s but open `HearingTask`s. Ticket to be completed by the Tango team (https://github.com/department-of-veterans-affairs/caseflow/issues/12678).

There are also two unique situations that are being addressed:
* Single appeal needs to be distributed. Waiting for response from @pshahVA about whether this appeal still needs to have a hearing (https://dsva.slack.com/archives/C3EAF3Q15/p1573657070021700).
* Dispatched appeal back in the process due to cancellation of tasks causing us to be in a weird state. Waiting for @D-L-Ware to confirm that this case can be closed (https://dsva.slack.com/archives/C3AT1CRGC/p1573658023187600)

**Comment by lowellrex** [comment] 2019-11-18 17:57
Closing this ticket since all categories of re-opened appeals have been corrected or accounted for in follow-up tickets.

**Closed by lowellrex** 2019-11-18 17:57 UTC
Labels: Data, Investigation, echo, metrics
