### ISSUE TITLE
End Product:  Submit: Create the End Product Integration

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow#417] opened 2016-11-05 01:12 UTC
As a Caseworker, I want to be able to submit information for an End Product so that VACOLS and VBMS systems can be updated. 

**Acceptance Criteria**

1. Verify that on the End Product page, there is a “Submit End Product” button.
1. Verify that on the End Product page when the "Submit End Product" button is clicked, all of the collected information is integrated into VBMS.
1. Verify that on the End Product page when the "Submit End Product" button is clicked, the value for Location Status/Code is updated to "98" in VACOLS.
1. Verify that on the End Product page when the "Submit End Product" button is clicked, the "Action" value display on the Caseworker Landing page in the Work History section of the current task is set to "EP [ep_code]".
1. Verify that on the End Product page when the "Submit End Product" button is clicked and successful synchronization of VACOLS and VBMS, the "Status" value on the Managers Landing page in the Current Cases section is set to "Completed" for the current appeal.

Developer Notes
- If an integration error occurs with VBMS or VACOLS, throw an exception.
- UX for handling these errors will be handled in another user story.
- After completion, redirect to an empty confirmation page. The details of this page will be handled in https://github.com/department-of-veterans-affairs/caseflow/issues/420

### Sub-Tasks

- [ ] Integration into VACOLS (collaborate with Shane)
- [ ] QA discovery and scripting

# Related Stories
EPIC: End Product: Ability to create and submit an end product - https://github.com/department-of-veterans-affairs/appeals-pm/issues/1120

**Comment by shanear** [comment] 2016-11-17 18:23
I can assist with the VBMS integration required for this. I'll be working on the `connect_vbms` integration in parallel.

**Comment by joofsh** [comment] 2016-12-01 19:04
example request
```
VBMS::Requests.soap(more_namespaces: NAMESPACES) do |xml|
          xml['cla'].establishClaim do
            xml['cla'].veteranInput('fileNumber' => '796164121', 'gender' => 'F', 'marriageStatus' => 'Unknown') do
              xml['participant'].preferredName('firstName' => "vicki", 'lastName' => 'schmidt')
              xml['participant'].personalInfo('ssn' => "796164121") do
                xml['participant'].address(
                  'addressLine1' => "Shrek's Swamp",
                  'city' => "Charleston",
                  'countryCode' => "USA",
                  'postalCode' => "29401",
                  'preferredAddr' => "true",
                  'stateCode' => "SC",
                  'type' => ""
                )
              end
            end
            xml['cla'].claimToEstablish(
              'benefitTypeCd' => '1',
              'claimLevelStatusCd' => 'PEND',
              'payeeCd' => '00',
              'label' => end_product.label,
              'modifiedEndProductCd' => end_product.modifier,
              'sectionUnit' => '499',
              'stationOfJurisdiction' => '499',
              'disposition' => 'M',
              'folderWithClaim' => 'N',
              'priority' => '1',
              'preDischarge' => 'false'
            ) do
              xml['cdm'].endProductClaimType('code' => end_product.code, 'name' => end_product.label)
              xml['cdm'].claimDateDt 20.days.ago.to_date.iso8601
            end
          end
        end
```

**Comment by joofsh** [comment] 2016-12-02 18:40
Fixed in https://github.com/department-of-veterans-affairs/caseflow/pull/511

**Comment by astewarttistatech** [comment] 2016-12-05 15:18
Moved back to "Current Sprint" due to it being currently incomplete.

**Comment by abbyraskin** [comment] 2017-01-09 16:05
@shanear handling fields hidden in the UI: 
**Claim Type** should default to **Claim**. 
Ignore **Intake Site**, **Suspense Date**, and **Suspense Reason**.

Ignore POA and POA Code for now. We have usability testing on Wednesday and will investigate hiding these fields.

**Comment by kierachell** [comment] 2017-01-13 14:27
Unable to check the code because...unable.
Do not see "Submit End Product" button.
We have multiple "Create End Product" pages.

**Comment by shanear** [comment] 2017-01-19 20:58
confirmed in UAT testing

**Closed by shanear** 2017-01-19 20:58 UTC
Labels: caseflow-dispatch, In Validation, tango
